#+TITLE: Week 8 lecture notes - PSYC 3435
#+AUTHOR:
#+DATE: Mar 6-10, 2017 
#+OPTIONS: toc:nil num:nil

This week, we'll talk about issues related to experiments with one independent variable, called *single factor designs*

* Between subjects designs
  - In a between-subjects design, participants experience /only one/ level of the independent variable.
  - participants randomly assigned to one of the levels

** Threat to validity -- group differences
  - random assignment usually eliminates individual differences by dispersing them across groups, so only difference between the groups is the manipulation
  - may not be sufficient with small sample!
  - Solution 1: use a /matched design/
    - participants matched across groups on some characteristic
    - Ex: O'Hanlon and Roberson (2006) - studied children's learning of color words.  
    - different groups taught color words under different feedback conditions
    - created matched sets of participants based on age and vocabulary ability, then randomly assigned one member of each matched set to each feedback condition
  - Solution 2: measure individual differences, then use them as /covariates/ in statistical analysis
  - Solution 3: use a /within-subjects/ design

* Within subjects designs
  - in a within-subjects design, participants experience /all/ levels of the independent variable

** Threat to validity -- order effects
  - the order in which participants experience the experimental conditions may affect the results
    - Example: test effect of problem format (digits/words) on arithmetic performance.  
    - within-subjects design -- give digit problems first, then word problems
    - suppose you find that word problems result in lower performance.  Why?
    - could be something about word problems that affects encoding?
    - OR, could be fatigue (since word problems ALWAYS occurred at end of experiment)
  - solution: use /counterbalancing/
    - two conditions: 2 possible orders (AB, BA).  Half of participants randomly assigned to AB order, other half assigned to BA
    - three conditions: 6 possible orders (ABC, ACB, BAC, BCA, CBA, CAB).  Assign participants randomly to these orders
    - four conditions: 24 possible orders!
    - five conditions: 120 possible orders!

Note: when you have four or more conditions, it is difficult to use ALL possible orders.  So, you have to do a /partial counterbalancing/.  This is done with a /Latin-square/ design.
 - Example: notice that each condition appears in each possible order position

| Order 1 | A | B | C | D |
| Order 2 | B | C | D | A |
| Order 3 | C | D | A | B |
| Order 4 | D | A | B | C | 

However, notice that A appears before B on 3/4 of orders.  So, there might still be an order effect of A before B.

Solution: use a /balanced/ Latin square

| Order 1 | A | B | D | C |
| Order 2 | B | C | A | D |
| Order 3 | C | D | B | A |
| Order 4 | D | A | C | B |

Here, each condition appears *before* and *after* all the others equally.  For example, A appears before B in half of orders, and A after B in the other half.

* Assignment for Wednesday
You will be randomly assigned to one of the following 3 articles.  For the article you read, please be prepared to answer the following questions:

1. Consider the design of the study. What is the independent variable? What are the levels of the IV?  What is the DV?
2.  Was the independent variable in the experiments manipulated between-subjects or within-subjects?  How do you know?
3. Do you think the study could have been conducted as the other type of design (opposite to your answer in #2)?  Why?

Articles: 
  - Storm, B. C., & Stone, S. M. (2015). Saving-enhanced memory: The benefits of saving on the learning and remembering of new information. /Psychological Science, 26/, 182-188. (look at Experiment 1)
  - Ferre, E. R., Lopez, C., & Haggard, P. (2014). Anchoring the self to the body: Vestibular contribution to the sense of self. /Psychological Science, 25/, 2106-2108.
  - Bastian, B., Jetten, J., & Ferris, L. J. (2014). Pain as social glue: Shared pain increases cooperation. /Psychological Science, 25/, 2079-2085. (look at Experiment 1.)
