#+TITLE: PSYC 4390/5090: Bayesian Statistics
#+AUTHOR: 
#+DATE: Summer 2022
#+OPTIONS: toc:nil
#+OPTIONS: num:nil
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [10pt]
#+LATEX_HEADER: \usepackage[left=1in,right=1in,bottom=1in,top=1in]{geometry}
#+LATEX_HEADER: \setlength{\parindent}{0pt}
#+LATEX_HEADER: \setlength{\parskip}{2mm}

** Contact info
- Professor: Thomas J. Faulkenberry, Ph.D
- Office: Math 301
- Office hours: MTRF 9-11 am
- Email: faulkenberry@tarleton.edu
- Website: [[http://tomfaulkenberry.github.io]]
- Phone: 254-968-9816
  
** Course description

Bayesian statistics is becoming an increasingly popular tool for scientific inference in the behavioral sciences. This course is designed to walk you through the "what", "why", and "how" of Bayesian statistics. We will begin with a review of the familiar statistical concepts of hypothesis testing and estimation, both of which form the cornerstone of statistical inference that you already know from previous courses. Then you will learn what it means to do these things from a /Bayesian/ perspective. Once the necessary background and motivation is provided, we will walk through several "case studies" that describe how to do Bayesian statistics for several common research designs that are ubiquitous across many fields of study, including correlation, two-group comparisons, designs with multiple variables, covariate designs, and linear regression.  

Students taking this course are expected to have *previously* taken a course in statistics (or equivalent statistical training). 

** Course materials

There is no required textbook for the course. However, I recommend you have access to a good statistics textbook ([[https://www.amazon.com/Psychological-Statistics-Basics-Thomas-Faulkenberry-dp-1032020954/dp/1032020954][mine]] is cheap).  In addition, you'll need to have access to a computer on which you can install the following software packages:

- R statistical software (free download from [[http://www.r-project.org][https://www.r-project.org]])
- RStudio (free download from [[http://www.rstudio.com][https://www.rstudio.com]])
- JASP (free download from https://jasp-stats.org)
  
** Student learning outcomes
   
1. perform and interpret basic techniques of statistical inference in both a traditional (frequentist) and Bayesian framework.
2. understand the basic concepts of prior, likelihood, and posterior, and describe how Bayes' rule links all three.
3. use both JASP and R to perform Bayesian inference on simple one-parameter models (e.g., binomial models)
4. perform and interpret techniques of Bayesian inference for common designs in the behavioral sciences, including correlations, two-group comparisons, multivariate designs, and linear regression.

** Requirements and grading

- Homework exercises (70 pts)
- Research proposal (30 pts)
- /Total = 100 points/

Grades will be assigned based on the percentage of points you accumulate out of a total possible 100 points.  I will use the standard grading scale of A=90%, B=80%, etc.

*** Homework exercises (70% of grade)
There will be 7 content units delivered during the 4-week session (approximately 2 per week). For each unit, I will provide you with a detailed video lecture and an accompanying set of lecture notes. To practice the concepts you learn in each unit, you will complete a short set of exercises.  Each exercise set will be worth 10 points, giving a total of 70 points for the session.

*** Research proposal (30% of grade)
Before the last day of the course, you will submit a short research proposal that demonstrates your knowledge of how to apply Bayesian statistics to answer some empirical question in the behavioral sciences. Studies that propose replication and confirmation are especially encouraged (see [[https://psyarxiv.com/5je9u/][here]] for an example of such a study)!  Your research proposal must contain the following three sections: (1) brief description of the research question; (2) brief description of the data collection method; and (3) details on the proposed Bayesian analyses of the data you would collect.  An example proposal will be provided early in the course.  

** Course Communication

This course is designed to be an intensive, interactive course on Bayesian statistics, which is my field of expertise.  That means that I will be available for one-on-one consultation most any time.  Just stop by my office or give me a call.

All official course communication (questions, setting up a meeting, etc.) will be conducted by email.  Any time you need to contact me, feel free to send me an email at faulkenberry@tarleton.edu.  I only ask that you adhere to two guidelines:
  - please include the course name (Bayesian statistics) in the subject line.  For example, one good way to do this is:  Subject: [Bayesian statistics] Question about problem set 3
  - please use proper email etiquette.  Include a salutation (e.g., Dear Dr. Faulkenberry), complete sentences, and a closing (e.g., "Regards, Your Name").  You might be surprised how many times I get an email from a nondescript email address with no indication from WHOM the email was sent!

Also, I will be sending periodic emails to each of you that update you on course progress, due dates, etc.  It is imperative that you check your /Tarleton email address/ regularly so that you don't miss any of these messages.

** University Policy on "F" Grades
Beginning in Fall 2015, Tarleton will begin differentiating between a failed grade in a class because a student never attended (F0 grade), stopped attending at some point in the semester (FX grade), or because the student did not pass the course (F) but attended the entire semester. These grades will be noted on the official transcript. Stopping or never attending class can result in the student having to return aid monies received.  For more information see the Tarleton Financial Aid website.

** Academic Honesty

Tarleton State University expects its students to maintain high standards of personal and scholarly conduct. Students guilty of academic dishonesty are subject to disciplinary action. Cheating, plagiarism (submitting another person’s materials or ideas as one’s own), or doing work for another person who will receive academic credit are all disallowed. This includes the use of unauthorized books, notebooks, or other sources in order to secure of give help during an examination, the unauthorized copying of examinations, assignments, reports, or term papers, or the presentation of unacknowledged material as if it were the student’s own work. Disciplinary action may be taken beyond the academic discipline administered by the faculty member who teaches the course in which the cheating took place.

In particular, any exam taken online must be completed without the aid of any unauthorized resource (including using any search engine, Google, etc.).  Authorized resources are limited only to the official textbook and any lecture notes from the course.  Any other authorized resources will be provided to you before the exam.  The minimum sanction for violation of this policy is a grade of 0 on the affected exam.

Each student’s honesty and integrity are taken for granted. However, if I find evidence of academic misconduct I will pursue the matter to the fullest extent permitted by the university. ACADEMIC MISCONDUCT OR DISHONESTY WILL RESULT IN A GRADE OF F FOR THE COURSE.  Students are strongly advised to avoid even the /appearance/ of academic misconduct. 

** Academic Affairs Core Value Statements

*** Academic Integrity Statement
Tarleton State University's core values are integrity, leadership, tradition, civility, excellence, and service.  Central to these values is integrity, which is maintaining a high standard of personal and scholarly conduct.  Academic integrity represents the choice to uphold ethical responsibility for one’s learning within the academic community, regardless of audience or situation.

*** Academic Civility Statement 
Students are expected to interact with professors and peers in a respectful manner that enhances the learning environment. Professors may require a student who deviates from this expectation to leave the face-to-face (or virtual) classroom learning environment for that particular class session (and potentially subsequent class sessions) for a specific amount of time. In addition, the professor might consider the university disciplinary process (for Academic Affairs/Student Life) for egregious or continued disruptive behavior.

*** Academic Excellence Statement
Tarleton holds high expectations for students to assume responsibility for their own individual learning. Students are also expected to achieve academic excellence by:
- honoring Tarleton’s core values, upholding high standards of habit and behavior.
- maintaining excellence through class attendance and punctuality, preparing for active participation in all learning experiences. 
- putting forth their best individual effort.
- continually improving as independent learners.
- engaging in extracurricular opportunities that encourage personal and academic growth.
- reflecting critically upon feedback and applying these lessons to meet future challenges.

** Students with Disabilities Policy

It is the policy of Tarleton State University to comply with the Americans with Disabilities  Act (www.ada.gov) and other applicable laws.  If you are a student with a disability seeking accommodations for this course, please contact the Center for Access and Academic Testing, at 254.968.9400 or caat@tarleton.edu. The office is located in Math 201. More information can be found at www.tarleton.edu/caat or in the University Catalog.​
 
*Note:  any changes to this syllabus will be communicated to you by the instructor!*
 
** Tentative schedule

| Unit | Due Date | Topics covered                                   |
|------+----------+--------------------------------------------------|
|    1 | 6/15     | Review of traditional (frequentist) inference    |
|    2 | 6/17     | The language and concepts of Bayesian statistics |
|    3 | 6/22     | Tools for Bayesian statistics                    |
|    4 | 6/24     | Bayesian inference with correlation designs      |
|    5 | 6/29     | Bayesian inference with two-group comparisons    |
|    6 | 7/1      | Bayesian inference with multivariate designs     |
|    7 | 7/6      | Bayesian linear regression                       |

