#+TITLE: PSYC 3320: Psycholinguistics
#+AUTHOR: 
#+DATE: Summer 2017
#+OPTIONS: toc:nil
#+OPTIONS: num:nil
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [10pt]
#+LATEX_HEADER: \usepackage[left=1in,right=1in,bottom=1in,top=1in]{geometry}

** Contact info
- Professor: Thomas J. Faulkenberry, Ph.D
- Office: Math 319
- Office hours: MWF 8-11 am /(or by appointment)/
- Email: faulkenberry@tarleton.edu
- Website: [[http://tomfaulkenberry.github.io]]
- Phone: 254-968-9816

** Course description

(from catalog) /The course emphasizes the study of language, understanding languages, producing language and speech, language development, and related topics such as reading, language and the brain, linguistic diversity, and universals./

Psycholinguistics is an area of specialization within cognitive psychology that focuses on the psychological mechanisms of language processing.  This course provides an introduction to the field of psycholinguistics. Psycholinguistics is the field that studies the information processing mechanisms that govern the use of language in comprehension and production, acquisition, and representation.  A common misconception is that one learns about the specifics of particular languages in a course on psycholinguistics.  This is not the case.  Rather, like most of cognitive psychology, this course emphasizes the /commonalities/ that underlie human languages everywhere, and we will focus on what these commonalities tell us about the human ability to construct and understand language. 

** Course materials
- /The Psychology of Language: From Data to Theory (4th ed.)/ by Harley [[https://www.amazon.com/Psychology-Language-Data-Theory/dp/1848720890][Amazon link]]

** Student learning outcomes
1. Define the basic vocabulary of psycholinguistics
2. Discuss the biological bases of human communication.
3. Describe how humans perceive and produce speech.
4. Describe how sentences and discourse are processed and comprehended. 
5. Discuss the acquisition of language. 
6. Describe the psychological processes involved in reading.
7. Identify and explain problems in speech and language processes.
8. Explain bilingualism and second language acquisition.

** Requirements and grading
- Exam 1 (100 pts)
- Exam 2 (100 pts)
- Exam 3 (100 pts)
- Exam 4 (100 pts)
- Unit quizzes (100 pts)
- /Total = 500 points/

Grades will be assigned based on the percentage of points you accumulate out of these 500 points.  I will use the standard grading scale of A=90%, B=80%, etc.

*** Exams (80% of grade)
There will be four total exams throughout the semester, occurring 
approximately once every 2  weeks.  They will cover material 
from your reading, online lectures, and quizzes.  Exam questions will be a mix of multiple choice and short answer.  Exams are due by 11:59 pm on 
the due date (see below).  Each exam will have a time limit and may only 
be attempted once.

Due dates:

- Exam 1 (Wednesday, June 28 at 11:59 pm)
- Exam 2 (Wednesday, July 12 at 11:59 pm)
- Exam 3 (Wednesday, July 26 at 11:59 pm)
- Final exam (Wednesday, August 9 at 11:59 pm)
  
*** Unit quizzes (20% of grade)
At the end of each unit, you will complete a quiz over the content of that 
unit. Each quiz will be graded as number correct out of 10 possible points.  Your total quiz grade will be computed by scaling your average quiz percentage up to a 100 point score.  For example, if you average 8.6/10 on your unit quizzes, your total quiz grade for the semester will be 86/100. 

** Course Communication

Email is the primary means of communication for this course.  If you have questions about the course, always feel free to send me an email at faulkenberry@tarleton.edu.  I only ask that you adhere to two guidelines:
  - please include the course number (PSYC 3320) in the subject line.  For example, one good way to do this is:  Subject: [PSYC 3320] Question about Exam 2
  - please use proper email etiquette.  Include a salutation (e.g., Dear Dr. Faulkenberry), complete sentences, and a closing (e.g., "Regards, Your Name").  You might be surprised how many times I get an email from a nondescript email address with no indication from WHOM the email was sent!

Also, I will be sending periodic emails to each of you that update you on course progress, due dates, etc.  It is imperative that you check your /Tarleton email address/ regularly so that you don't miss any of these messages.

** University Policy on "F" Grades
Beginning in Fall 2015, Tarleton will begin differentiating between a 
failed grade in a class because a student never attended (F0 grade), 
stopped attending at some point in the semester (FX grade), or because 
the student did not pass the course (F) but attended the entire semester. 
These grades will be noted on the official transcript. Stopping or never 
attending class can result in the student having to return aid monies 
received.  For more information see the Tarleton Financial Aid website.

** Academic Honesty

Tarleton State University expects its students to maintain high standards of
personal and scholarly conduct. Students guilty of academic dishonesty are
subject to disciplinary action. Cheating, plagiarism (submitting another person’s materials or ideas as one’s own), or doing work for another person who will receive academic credit are all disallowed. This includes the use of unauthorized books, notebooks, or other sources in order to secure of give help during an examination, the unauthorized copying of examinations, assignments, reports, or term papers, or the presentation of unacknowledged material as if it were the student’s own work. Disciplinary action may be taken beyond the academic discipline administered by the faculty member who teaches the course in which the cheating took place.  

In particular, any exam taken online must be completed without the aid of any unauthorized resource (including using any search engine, Google, etc.).  Authorized resources are limited only to the official textbook and any lecture notes from the course.  Any other authorized resources will be provided to you before the exam.  The minimum sanction for violation of this policy is a grade of 0 on the affected exam.

Each student’s honesty and integrity are taken for granted. However, if I find
evidence of academic misconduct I will pursue the matter
to the fullest extent permitted by the university. ACADEMIC MISCONDUCT OR
DISHONESTY WILL RESULT IN A GRADE OF F FOR THE COURSE.  Students are
strongly advised to avoid even the /appearance/ of academic misconduct. 

** Academic Affairs Core Value Statements

*** Academic Integrity Statement
Tarleton State University's core values are integrity, leadership, tradition, civility, excellence, and service.  Central to these values is integrity, which is maintaining a high standard of personal and scholarly conduct.  Academic integrity represents the choice to uphold ethical responsibility for one’s learning within the academic community, regardless of audience or situation.

*** Academic Civility Statement 
Students are expected to interact with professors and peers in a respectful manner that enhances the learning environment. Professors may require a student who deviates from this expectation to leave the face-to-face (or virtual) classroom learning environment for that particular class session (and potentially subsequent class sessions) for a specific amount of time. In addition, the professor might consider the university disciplinary process (for Academic Affairs/Student Life) for egregious or continued disruptive behavior.

*** Academic Excellence Statement
Tarleton holds high expectations for students to assume responsibility for their own individual learning. Students are also expected to achieve academic excellence by:
- honoring Tarleton’s core values, upholding high standards of habit and behavior.
- maintaining excellence through class attendance and punctuality, preparing for active participation in all learning experiences. 
- putting forth their best individual effort.
- continually improving as independent learners.
- engaging in extracurricular opportunities that encourage personal and academic growth.
- reflecting critically upon feedback and applying these lessons to meet future challenges.

** Students with Disabilities Policy

It is the policy of Tarleton State University to comply with the Americans
with Disabilities Act and other applicable laws. If you are a student with a
disability seeking accommodations for this course, please contact Trina
Geye, Director of Student Disability Services, at 254.968.9400 or
geye@tarleton.edu. Student Disability Services is
located in Math 201. More information can be found at www.tarleton.edu/sds or in the University Catalog.


**Note:  any changes to this syllabus will be communicated to you by the instructor!**
 
** Semester Schedule

| Unit               | Topic                                             | Book chapter(s) |
|--------------------+---------------------------------------------------+-----------------|
| 1 (June 14-20)     | The basics (cognitive psychology and linguistics) |             1,2 |
| 2 (June 21-27)     | The foundations of language                       |               3 |
|                    | *Exam 1 (due Wednesday, June 28)*                 |                 |
| 3 (June 28-July 4) | Language development                              |               4 |
| 4 (July 5-11)      | Perception of words (visual and spoken)           |             6,9 |
|                    | *Exam 2 (due Wednesday, July 12)*                 |                 |
| 5 (July 12-18)     | Reading                                           |             7,8 |
| 6 (July 19-25)     | Understanding the structure of sentences          |              10 |
|                    | *Exam 3 (due Wednesday, July 26)*                 |                 |
| 7 (July 26-Aug 1)  | Word meaning                                      |              11 |
| 8 (Aug 2-8)        | Language production                               |              13 |
|                    | *Exam 4 (due Wednesday, Aug 9)*                   |                 |

