#+TITLE: PSYC 5316: Advanced Quantitative Methods & Experimental Design
#+AUTHOR: 
#+DATE: Fall 2018
#+OPTIONS: toc:nil
#+OPTIONS: num:nil
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [10pt]
#+LATEX_HEADER: \usepackage[left=1in,right=1in,bottom=1in,top=1in]{geometry}
#+LATEX_HEADER: \setlength{\parindent}{0pt}
#+LATEX_HEADER: \setlength{\parskip}{2mm}

** Contact info
- Professor: Thomas J. Faulkenberry, Ph.D
- Office: Math 319
- Office hours: MWF 1-3 pm; TR 9:30-11:30 am
- Email: faulkenberry@tarleton.edu
- Website: [[http://tomfaulkenberry.github.io]]
- Phone: 254-968-9816
  
** Course description

This course is designed to teach you the advanced quantitative methods and techniques of experimental design that are necessary to read and conduct modern empirical research in the psychological sciences. We will do this through replicating three classic experiments, each illustrating a unique experimental design and technique for data analysis.  Students taking this course are expected to have *previously* taken a graduate level course in statistics (or equivalent statistical training). 

Some of the specific skills you'll learn this semester are:
- using a computer to program behavioral experiments and collect response time data 
- efficiently pre-processing raw data and implement sophisticated statistical models using R
- writing technical manuscripts to report results of experiments

** Course materials

There is no required textbook for the course. However, I recommend you have access to a good statistics text (e.g., Gravetter or Field are great ones to have).  In addition, you'll need to have access to a computer (laptop is best) on which you can install the following software packages:

- R statistical software (free download from [[http://www.r-project.org][http://www.r-project.org]])
- RStudio (free download from [[http://www.rstudio.com][http://www.rstudio.com]])
- OpenSesame (free download from http://osdoc.cogsci.nl/

All readings/videos/etc. will be posted on Github: http://github.com/tomfaulkenberry/courses/

** Student learning outcomes
   
1. perform and interpret basic techniques of statistical inference, both in a frequentist and Bayesian framework
2. program and administer behavioral experiments using computer software
3. understand various methods of cleaning data for analysis in R
4. develop skills for communicating technical material, especially through writing scientific manuscripts in APA format.

** Requirements and grading

- Lab 1 (100 pts)
- Lab 2 (100 pts)
- Lab 3 (100 pts)
- In class participation (100 pts)
- /Total = 400 points/

Grades will be assigned based on the percentage of points you accumulate out of these 400 points.  I will use the standard grading scale of A=90%, B=80%, etc.

*** Labs (75% of grade)
There will be three lab experiments conducted throughout the semester.  Each lab will take approximately four weeks to complete using the schedule below:

- first week (online): video lecture describing to construct experiment and collect data
- second week (face to face): in class discussion on how to analyze the data you've collected
- third week (online): video lecture describing how to analyze data in R
- fourth week (face to face): in class discussion of the results of experiment and writeup of final manuscript

*** In class participation (25% of grade)

We meet face-to-face in Stephenville every other week this semester.  In total, there will be 8 meetings (see schedule below for specific dates).  It is /imperative/ that you attend these face-to-face sessions, because this is where we will discuss the material needed to successfully complete the labs that we will complete.  The participation will be assigned as a percent of the classes you attend. For example, if you attend 5 out of 8 classes, your attendance grade will be 62.5 points.

** Course Communication

This course is designed to be an intensive, interactive seminar on modern statistical methods and experimental design.  That means that I will be available for one-on-one consultation most any time.  Just stop by my office or give me a call.

All official course communication (questions, setting up a meeting, etc.) will be conducted by email.  Any time you need to contact me, feel free to send me an email at faulkenberry@tarleton.edu.  I only ask that you adhere to two guidelines:
  - please include the course number (PSYC 5316) in the subject line.  For example, one good way to do this is:  Subject: [PSYC 5316] Question about problem set 3
  - please use proper email etiquette.  Include a salutation (e.g., Dear Dr. Faulkenberry), complete sentences, and a closing (e.g., "Regards, Your Name").  You might be surprised how many times I get an email from a nondescript email address with no indication from WHOM the email was sent!

Also, I will be sending periodic emails to each of you that update you on course progress, due dates, etc.  It is imperative that you check your /Tarleton email address/ regularly so that you don't miss any of these messages.

** University Policy on "F" Grades
Beginning in Fall 2015, Tarleton will begin differentiating between a failed grade in a class because a student never attended (F0 grade), stopped attending at some point in the semester (FX grade), or because the student did not pass the course (F) but attended the entire semester. These grades will be noted on the official transcript. Stopping or never attending class can result in the student having to return aid monies received.  For more information see the Tarleton Financial Aid website.

** Academic Honesty

Tarleton State University expects its students to maintain high standards of personal and scholarly conduct. Students guilty of academic dishonesty are subject to disciplinary action. Cheating, plagiarism (submitting another person’s materials or ideas as one’s own), or doing work for another person who will receive academic credit are all disallowed. This includes the use of unauthorized books, notebooks, or other sources in order to secure of give help during an examination, the unauthorized copying of examinations, assignments, reports, or term papers, or the presentation of unacknowledged material as if it were the student’s own work. Disciplinary action may be taken beyond the academic discipline administered by the faculty member who teaches the course in which the cheating took place.

In particular, any exam taken online must be completed without the aid of any unauthorized resource (including using any search engine, Google, etc.).  Authorized resources are limited only to the official textbook and any lecture notes from the course.  Any other authorized resources will be provided to you before the exam.  The minimum sanction for violation of this policy is a grade of 0 on the affected exam.

Each student’s honesty and integrity are taken for granted. However, if I find evidence of academic misconduct I will pursue the matter to the fullest extent permitted by the university. ACADEMIC MISCONDUCT OR DISHONESTY WILL RESULT IN A GRADE OF F FOR THE COURSE.  Students are strongly advised to avoid even the /appearance/ of academic misconduct. 

** Academic Affairs Core Value Statements

*** Academic Integrity Statement
Tarleton State University's core values are integrity, leadership, tradition, civility, excellence, and service.  Central to these values is integrity, which is maintaining a high standard of personal and scholarly conduct.  Academic integrity represents the choice to uphold ethical responsibility for one’s learning within the academic community, regardless of audience or situation.

*** Academic Civility Statement 
Students are expected to interact with professors and peers in a respectful manner that enhances the learning environment. Professors may require a student who deviates from this expectation to leave the face-to-face (or virtual) classroom learning environment for that particular class session (and potentially subsequent class sessions) for a specific amount of time. In addition, the professor might consider the university disciplinary process (for Academic Affairs/Student Life) for egregious or continued disruptive behavior.

*** Academic Excellence Statement
Tarleton holds high expectations for students to assume responsibility for their own individual learning. Students are also expected to achieve academic excellence by:
- honoring Tarleton’s core values, upholding high standards of habit and behavior.
- maintaining excellence through class attendance and punctuality, preparing for active participation in all learning experiences. 
- putting forth their best individual effort.
- continually improving as independent learners.
- engaging in extracurricular opportunities that encourage personal and academic growth.
- reflecting critically upon feedback and applying these lessons to meet future challenges.

** Students with Disabilities Policy

It is the policy of Tarleton State University to comply with the Americans with Disabilities  Act (www.ada.gov) and other applicable laws.  If you are a student with a disability seeking accommodations for this course, please contact the Center for Access and Academic Testing, at 254.968.9400 or caat@tarleton.edu. The office is located in Math 201. More information can be found at www.tarleton.edu/caat or in the University Catalog.​
 
*Note:  any changes to this syllabus will be communicated to you by the instructor!*
 
** Tentative schedule

| Week | Date  | Location     | Topic                                                                      |
|------+-------+--------------+----------------------------------------------------------------------------|
|    1 | 8/27  | Stephenville | Install software, introduce flanker task                                   |
|    2 | 9/3   | online       | Video lecture: programming flanker task and collect data                   |
|    3 | 9/10  | Stephenville | Discussion: stats background on repeated measures designs                  |
|    4 | 9/17  | online       | Video lecture: analyzing flanker task data in R                            |
|    5 | 9/24  | Stephenville | Discussion: results of flanker task & final manuscript                     |
|    6 | 10/1  | online       | Video lecture: programming Sternberg memory scanning task and collect data |
|    7 | 10/8  | Stephenville | Discussion: stats background on linear modeling                            |
|    8 | 10/15 | online       | Video lecture: analyzing Sternberg data in R                               |
|    9 | 10/22 | Stephenville | Discussion: results of Sternberg task & final manuscript                   |
|   10 | 10/29 | online       | Video lecture: programming mental arithmetic task and collect data         |
|   11 | 11/5  | Stephenville | Discussion: stats background on factorial designs                          |
|   12 | 11/12 | online       | Video lecture: analyzing mental arithmetic data in R                       |
|   13 | 11/19 | Stephenville | Discussion: results of mental arithmetic task & final manuscript           |
|   14 | 11/26 | online       | TBA                                                                        |
|   15 | 12/3  | Stephenville | Wrap up                                                                    |
