#+TITLE: PSYC 2317: Statistical Methods for Psychology
#+AUTHOR: 
#+DATE: Fall 2021
#+OPTIONS: toc:nil
#+OPTIONS: num:nil
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [10pt]
#+LATEX_HEADER: \usepackage[left=1in,right=1in,bottom=1in,top=1in]{geometry}

** Contact info
- Professor: Thomas J. Faulkenberry, Ph.D
- Office: Math 301
- Office hours: /TBA/
- Email: faulkenberry@tarleton.edu
- Website: [[http://tomfaulkenberry.github.io]]
- Phone: 254-968-9816

** Course description

Statistical methods are the primary tool for research in psychology. They are what allow us as researchers to make consistent, data-driven decisions.  As such, this is an extremely important course and one that I take very seriously as your professor. The topics we will cover this semester will include descriptive statistics (how we describe data) and inferential statistics (how we make decisions about data).  Specifically, this includes central tendency, variability, the distinction between populations and samples, parameter estimation, and hypothesis testing (both classical and Bayesian).

** Course materials
- Primary textbook: Faulkenberry, T. J. (2022). /Psychological Statistics: The Basics/. Forthcoming book to be published by Routledge / Taylor & Francis.
  - I am currently under contract to deliver this book to the publisher by December 1, 2021. Throughout the course, I will be providing you with draft chapters (for free!) for download on Canvas. I hope you will help me by reading the chapters carefully, spotting errors, and generally letting me know how to make it better. Thanks!

- Optional reference book: For reference, I recommend our book /Learning Statistics with JASP: A Tutorial for Psychology Students and Other Beginners/ by Navarro, Foxcroft, and Faulkenberry (2019), which is a textbook that can be downloaded (for free!) from [[http://learnstatswithjasp.com][www.learnstatswithjasp.com]].

- Online statistical calculator: throughout the semester, we will use the /PsyStat/ calculator developed over the past few years by me and my student Keelyn Brennan. The calculator can be accessed (for free!) on any computer or mobile device at https://tomfaulkenberry.shinyapps.io/psystat
   
- Statistical software: Later in the course, we will also learn to use the JASP statistical software package; this can be downloaded (you guessed it -- for free!) from [[http://www.jasp-stats.com][www.jasp-stats.com]]

** Student learning outcomes
1. Identify variables under study (including independent and dependent variables)
2. Choose appropriate measures of descriptive statistics
3. Select and perform appropriate inferential statistics
4. Draw appropriate statistical conclusions from results of analyses

** Course format

This course will be delivered in a hybrid-flexible format, giving you the option of attending the course face-to-face and/or online in whatever way makes the most sense for you. The basic structure of each week is as follows:

- early in the week (i.e., Monday), you will watch an online video lecture (given by me) explaining the week's topic and take a short quiz to assess your understanding. This quiz will always be due on Monday night at 11:59 pm.

- on Tuesday, I will use our class time to briefly review the week's topic and work through examples of homework problems that are assigned for the given week. I will refer to this as the /Tuesday problem session/.

- on Thursday, I will finish up anything that I was not able to cover on Tuesday, and the rest of the time will be yours to ask questions. These questions can be related to the homework, or they can be completely unrelated...for example, you can ask questions about psychological research or graduate school; whatever piques your interest! The time is yours to do with as you please. Please note that questions about the course content will always be given priority. I will refer to this as the /Thursday review session/.
  
Note that you are not /required/ to attend any face-to-face class meetings at all! You may certainly wish to attend face-to-face, and I encourage all who can to do so. However, there are other ways to "attend" class:
  - You may attend virtually by Zoom (that is, you can participate in the class meeting /live/ on your computer during class time).
  - You may choose to simply watch the recorded Tuesday problem sessions at a convenient time later in the week. These recordings will be posted on Canvas.

It does not matter which mode of attendance you choose -- that is the point of our "hybrid-flexible" course format. And, you can change the way you attend each week. The only thing that is /required/ is that you complete the quizzes, homeworks, and exams, which I'll describe in the next section.

** Requirements and grading
- Exam 1 (100 pts)
- Exam 2 (100 pts)
- Exam 3 (100 pts)
- Weekly quizzes (100 pts)
- Homework exercises (100 pts)
- /Total = 500 points/

Grades will be assigned based on the percentage of points you accumulate out of these 500 points.  I will use the standard grading scale of A=90%, B=80%, etc.

*** Exams
There will be three exams throughout the semester, occurring approximately once every four to five weeks.  They will cover material from lectures, quizzes, and homework exercises. Exams will be "take-home", primarily consisting of short-answer questions. Exams (and homework; see below) will be submitted online on Canvas -- in my experience, it is probably easiest to hand-write your solutions neatly on clean paper and either scan or take a photo of the completed work to submit. 

Tentative exam dates:

- Exam 1 (due Sunday, September 26 at 11:59 pm)
- Exam 2 (due Sunday, October 31 at 11:59 pm)
- Exam 3 (due Sunday, December 5 at 11:59 pm)
  
*** Weekly quizzes 

At the beginning of each non-exam week, you will watch a video posted on Canvas where I introduce the week's concepts. After watching this video, you will complete an online multiple-choice quiz, the aim of which is to check for understanding of the concepts presented. Each quiz counts for 10 possible points. There will 10 of these quizzes, and these quiz scores will earn you up to 100 points for your overall quiz grade.

*** Homework exercises 
In order to practice the statistical concepts you learn this semester, you will complete a short homework assignment every week. A set of homework exercises (usually around 4-5 problems) will be provided to you each week. You may work collaboratively on the homework exercises, but any work submitted must reflect your own understanding of the material (in other words, don't just copy someone else's work to submit). /Please note that all work must be shown on computational problems in order to receive full credit./ Each homework assignment will be due at 11:59 pm on Sunday immediately following the week it was assigned.

** Course Communication

Email is the primary means of official communication for this course.  If you have questions about the course, always feel free to send me an email at faulkenberry@tarleton.edu.  I only ask that you adhere to two guidelines:
  - please include the course number (PSYC 2317) in the subject line.  For example, one good way to do this is:  Subject: [PSYC 2317] Question about Exam 2
  - please use proper email etiquette.  Include a salutation (e.g., Dear Dr. Faulkenberry), complete sentences, and a closing (e.g., "Regards, Your Name").  You might be surprised how many times I get an email from a nondescript email address with no indication from WHOM the email was sent!

Also, I will send periodic class announcements via email.  Thus, it is imperative that you check your /Tarleton email address/ regularly so that you don't miss any of these messages.

** University Policy on "F" Grades
Beginning in Fall 2015, Tarleton will begin differentiating between a failed grade in a class because a student never attended (F0 grade), stopped attending at some point in the semester (FX grade), or because the student did not pass the course (F) but attended the entire semester. These grades will be noted on the official transcript. Stopping or never attending class can result in the student having to return aid monies received.  For more information see the Tarleton Financial Aid website.
** Academic Honesty

Tarleton State University expects its students to maintain high standards of personal and scholarly conduct. Students guilty of academic dishonesty are subject to disciplinary action. Cheating, plagiarism (submitting another person’s materials or ideas as one’s own), or doing work for another person who will receive academic credit are all disallowed. This includes the use of unauthorized books, notebooks, or other sources in order to secure of give help during an examination, the unauthorized copying of examinations, assignments, reports, or term papers, or the presentation of unacknowledged material as if it were the student’s own work. Disciplinary action may be taken beyond the academic discipline administered by the faculty member who teaches the course in which the cheating took place.

In particular, any exam taken online must be completed without the aid of any unauthorized resource (including using any search engine, Google, etc.).  Authorized resources are limited only to the official textbook and any lecture notes from the course.  Any other authorized resources will be provided to you before the exam.  The minimum sanction for violation of this policy is a grade of 0 on the affected exam.

Each student’s honesty and integrity are taken for granted. However, if I find evidence of academic misconduct I will pursue the matter to the fullest extent permitted by the university. ACADEMIC MISCONDUCT OR DISHONESTY WILL RESULT IN A GRADE OF F FOR THE COURSE.  Students are strongly advised to avoid even the /appearance/ of academic misconduct. 

** Academic Affairs Core Value Statements
*** Academic Integrity Statement
Tarleton State University's core values are integrity, leadership, tradition, civility, excellence, and service.  Central to these values is integrity, which is maintaining a high standard of personal and scholarly conduct.  Academic integrity represents the choice to uphold ethical responsibility for one’s learning within the academic community, regardless of audience or situation.

*** Academic Civility Statement 
Students are expected to interact with professors and peers in a respectful manner that enhances the learning environment. Professors may require a student who deviates from this expectation to leave the face-to-face (or virtual) classroom learning environment for that particular class session (and potentially subsequent class sessions) for a specific amount of time. In addition, the professor might consider the university disciplinary process (for Academic Affairs/Student Life) for egregious or continued disruptive behavior.

*** Academic Excellence Statement
Tarleton holds high expectations for students to assume responsibility for their own individual learning. Students are also expected to achieve academic excellence by:
- honoring Tarleton’s core values, upholding high standards of habit and behavior.
- maintaining excellence through class attendance and punctuality, preparing for active participation in all learning experiences. 
- putting forth their best individual effort.
- continually improving as independent learners.
- engaging in extracurricular opportunities that encourage personal and academic growth.
- reflecting critically upon feedback and applying these lessons to meet future challenges.

** Students with Disabilities Policy

It is the policy of Tarleton State University to comply with the Americans with Disabilities  Act (www.ada.gov) and other applicable laws.  If you are a student with a disability seeking accommodations for this course, please contact the Center for Access and Academic Testing, at 254.968.9400 or caat@tarleton.edu. The office is located in Math 201. More information can be found at www.tarleton.edu/caat or in the University Catalog.​
 
*Note:  any changes to this syllabus will be communicated to you by the instructor!*

** Semester Schedule

| Week beginning | Topic                                                 |
|----------------+-------------------------------------------------------|
| Aug 19         | Course introduction - no homework assignment          |
| Aug 23         | Unit 1 - Measures of central tendency and variability |
| Aug 30         | Unit 2 - Transformations of scores / standardization  |
| Sep 6          | Unit 3 - The normal distribution                      |
| Sep 13         | Unit 4 - Distributions of sample means                |
| Sep 20         | *Exam 1* due Sunday, 9/26, at 11:59 pm                |
| Sep 27         | Unit 5 - Estimation and hypothesis testing            |
| Oct 4          | Unit 6 - Introduction to the \( t \)-test             |
| Oct 11         | Unit 7 - \( t \)-tests for independent samples        |
| Oct 18         | Unit 8 - Confidence intervals for \( t \)-tests       |
| Oct 25         | *Exam 2* due Sunday, 10/31, at 11:59 pm               |
| Nov 1          | Unit 9 - JASP / analysis of variance                  |
| Nov 8          | Unit 10 - Bayesian hypothesis testing                 |
| Nov 15         | Topic TBA -- depends on time and interest             |
| Nov 22         | /no class due to Thanksgiving/                        |
| Nov 29         | *Exam 3* due Sunday, Dec 5, at 11:59 pm               |


