#+TITLE: PSYC 2317: Statistical Methods for Psychology
#+AUTHOR: 
#+DATE: Fall 2021
#+OPTIONS: toc:nil
#+OPTIONS: num:nil
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [10pt]
#+LATEX_HEADER: \usepackage[left=1in,right=1in,bottom=1in,top=1in]{geometry}

** Contact info
- Professor: Thomas J. Faulkenberry, Ph.D
- Office: Math 301
- Office hours: /TBA/
- Email: faulkenberry@tarleton.edu
- Website: [[http://tomfaulkenberry.github.io]]
- Phone: 254-968-9816

** Course description

Statistical methods are the primary tool for research in psychology. They are what allow us as researchers to make consistent, data-driven decisions.  As such, this is an extremely important course and one that I take very seriously as your professor. The topics we will cover this semester will include descriptive statistics (how we describe data) and inferential statistics (how we make decisions about data).  Specifically, this includes central tendency, variability, the distinction between populations and samples, hypothesis testing, and a variety of inferential tests that we can apply to data, including t-tests, linear regression, and analysis of variance.

** Course materials
There are many excellent statistics books, but I do not teach from any specific one. For reference, I recommend our book /Learning Statistics with JASP: A Tutorial for Psychology Students and Other Beginners/, by Navarro, Foxcroft, and Faulkenberry (2019), which is a free textbook that can be downloaded from [[http://learnstatswithjasp.com][www.learnstatswithjasp.com]].

We will also begin to use the JASP statistical software package later in the course; this can be freely downloaded from [[http://www.jasp-stats.com][www.jasp-stats.com]]

** Student learning outcomes
1. Identify variables under study (including independent and dependent variables)
2. Choose appropriate measures of descriptive statistics
3. Select and perform appropriate inferential statistics
4. Draw appropriate statistical conclusions from results of analyses

** Course format

This course will be delivered in a hybrid-flexible ("HyFlex") format, giving you the option of attending the course face-to-face and/or online. The basic structure of each week is as follows:

- early in the week, you will watch an online video lecture (given by me) explaining the week's topic and take a short quiz to assess your understanding.

- you can then attend ONE face-to-face course meeting (either Tuesday or Thursday, but not both). The purpose of this course meeting is for me to demonstrate examples of homework problems that are assigned for the given week and give you the opportunity to ask questions. Half the class will be able to attend on Tuesday, and the other half will be able to attend on Thursday. Your specific day of the week will be assigned and communicated to you in Canvas and by email. In this way, each student will have the opportunity to attend class face-to-face once each week.

Note that you are not /required/ to attend the face-to-face class meetings at all! You may certainly wish to attend face-to-face, and I encourage all who can to do so. However, there are other ways to attend the weekly problem sessions:
  - You may attend either session virtually by Zoom (that is, you can watch the problem session /live/ on your computer during class time).
  - You may choose to simply watch the recorded problem sessions at a convenient time later in the week. All class recordings will be posted on Canvas.

It does not matter which mode of attendance you choose -- that is the point of our "Hybrid-Flexible" course format. And, you can change your mind each week. The only thing that is /required/ is that you complete the quizzes, homeworks, and exams, which I'll describe in the next section.

** Requirements and grading
- Exam 1 (100 pts)
- Exam 2 (100 pts)
- Exam 3 (100 pts)
- Weekly quizzes (100 pts)
- Homework exercises (100 pts)
- /Total = 500 points/

Grades will be assigned based on the percentage of points you accumulate out of these 500 points.  I will use the standard grading scale of A=90%, B=80%, etc.

*** Exams
There will be three exams throughout the semester, occurring approximately once every four to five weeks.  They will cover material from lectures, quizzes, and homework exercises. Exams will be "take-home", primarily consisting of short-answer questions. Exams (and homework; see below) will be submitted online on Canvas -- in my experience, it is probably easiest to hand-write your solutions neatly on clean paper and either scan or take a photo of the completed work to submit. 

Tentative exam dates:

- Exam 1 (due Sunday, September 27 at 11:59 pm)
- Exam 2 (due Sunday, November 1 at 11:59 pm)
- Exam 3 (due Sunday, December 6 at 11:59 pm)
  
*** Weekly quizzes 

At the beginning of each non-exam week, you will watch a video posted on Canvas where I introduce the week's concepts. After watching this video, you will complete an online multiple-choice quiz, the aim of which is to check for understanding of the concepts presented. Each quiz counts for 10 possible points. There will be at least 10 of these quizzes, so your 10 highest quiz scores will earn you up to 100 points for your overall quiz grade.

*** Homework exercises 
In order to practice the statistical concepts you learn this semester, you will complete a short homework assignment every week. A set of homework exercises (usually around 4-5 problems) will be provided to you each week. You may work collaboratively on the homework exercises, but any work submitted must reflect your own understanding of the material (in other words, don't just copy someone else's work to submit).  Each homework assignment will be due at 11:59 pm on Sunday immediately following the week it was assigned.

** Fall 2020 Safety Measures
Tarleton State University has adopted policies and practices for the Fall 2020 term to limit transmission of the novel coronavirus. Students are required to observe the following practices while participating in face-to-face courses and course-related activities (office hours, moving between classes, study spaces, academic services, etc.):

  - Self-monitoring – Students should follow CDC recommendations for self-monitoring. Students who exhibit symptoms of COVID-19 (with or without fever) should participate in class remotely and should not participate in face-to-face instruction. See https://www.tarleton.edu/roadmap/personal-responsibilities/ for more information. Students who test positive for COVID-19 or experience symptoms consistent with COVID-19 are required to self-report to Tarleton State University via this [[https://cm.maxient.com/reportingform.php?TarletonStateUniv&layout_id=6.][form]].

  - Face coverings – All students must properly wear face coverings in all public spaces on campus, including classrooms.  If a student refuses to wear a face covering, the instructor will ask the student to leave and join the class remotely. Any student refusing to comply will be reported  to the Dean of Students Administrative Office via the [[https://cm.maxient.com/reportingform.php?TarletonStateUniv&layout_id=0][Student Affairs Incident Reporting Form]]. Additionally, the faculty member may choose to teach that day’s class remotely for all students.

  - Physical Distancing – Physical distancing must be maintained between students, instructors, and others in course and course-related activities.

  - Classroom Entrance and Exit – Students should leave classrooms promptly after class activities have concluded each day. Students should not congregate in hallways or other areas and should maintain a safe physical distance when waiting to enter classrooms and other instructional areas.

*** Personal Illness and Quarantine/Isolation
Students who are required to quarantine (see https://www.tarleton.edu/roadmap/isolation-v-quarantine/) must participate in course and course-related activities remotely and must not attend face-to-face course activities. Students in quarantine are expected to participate in courses and course activities/assignments unless they have symptoms too severe to participate. Students placed in isolation should contact the instructor about individual participation in relation to severity of illness. Students who test positive for COVID-19 or who are experiencing symptoms consistent with COVID-19 are required to self-report to the Dean of Students Administrative Office through the [[https://cm.maxient.com/reportingform.php?TarletonStateUniv&layout_id=6][COVID-19]] Report Form.  For any questions or concerns, please contact the Dean of Students Administrative Office at 254-968-9080. 
 
*** Blended Hybrid-HyFlex Course Delivery
Blended Hybrid-HyFlex courses are designed so that students can choose to attend courses face-to-face (with the potential for rotation to maintain a safe physical distance), at the same time as the face-to-face class meetings but from a different location (remote synchronous), or remotely at a later time by viewing the recorded course meeting (remote asynchronous). All courses will appear in the Canvas Learning Management System (LMS) to maximize access to course materials and other important course related activities. Students can choose to attend via any of the three modalities at any time.

Note, however, that programs governed by licensure and/or accreditation/certification requirements may require students to attend face-to-face laboratories, simulations, and clinical experiences to progress through the program and successfully graduate with eligibility for the licensure or certification examination.
 
To make course meetings accessible asynchronously, class meetings will be recorded and shared. The class recordings will be shared with students only in the individual section in which it was recorded to avoid violations of the Family Educational Rights and Privacy Act (FERPA).

** Course Communication

Email is the primary means of official communication for this course.  If you have questions about the course, always feel free to send me an email at faulkenberry@tarleton.edu.  I only ask that you adhere to two guidelines:
  - please include the course number (PSYC 2317) in the subject line.  For example, one good way to do this is:  Subject: [PSYC 2317] Question about Exam 2
  - please use proper email etiquette.  Include a salutation (e.g., Dear Dr. Faulkenberry), complete sentences, and a closing (e.g., "Regards, Your Name").  You might be surprised how many times I get an email from a nondescript email address with no indication from WHOM the email was sent!

Also, I will send periodic class announcements via email.  Thus, it is imperative that you check your /Tarleton email address/ regularly so that you don't miss any of these messages.

** CV Points for Psychology Majors
Beginning Fall 2019, all Tarleton psychology majors are required to accumulate a certain number of "CV points" as a requirement for graduation. CV is an acronym for "curriculum vitae", which is the traditional name of an academic resume.  No graduating psychology major will receive a diploma without completion/verification of the required 15 CV points. Some classes may build in CV point assignments, but ultimately it is the students’ responsibility to monitor their participation and acquire points during their time at Tarleton.  More information on pre-approved CV points, submission, and tracking of these points can be found in the CV Point Canvas site. Please note that submissions are graded, and may not be approved for points if they do not meet the CV standard.  If a student has a question about CV points, they should send an email to psychcvpointga@tarleton.edu.

** University Policy on "F" Grades
Beginning in Fall 2015, Tarleton will begin differentiating between a failed grade in a class because a student never attended (F0 grade), stopped attending at some point in the semester (FX grade), or because the student did not pass the course (F) but attended the entire semester. These grades will be noted on the official transcript. Stopping or never attending class can result in the student having to return aid monies received.  For more information see the Tarleton Financial Aid website.
** Academic Honesty

Tarleton State University expects its students to maintain high standards of personal and scholarly conduct. Students guilty of academic dishonesty are subject to disciplinary action. Cheating, plagiarism (submitting another person’s materials or ideas as one’s own), or doing work for another person who will receive academic credit are all disallowed. This includes the use of unauthorized books, notebooks, or other sources in order to secure of give help during an examination, the unauthorized copying of examinations, assignments, reports, or term papers, or the presentation of unacknowledged material as if it were the student’s own work. Disciplinary action may be taken beyond the academic discipline administered by the faculty member who teaches the course in which the cheating took place.

In particular, any exam taken online must be completed without the aid of any unauthorized resource (including using any search engine, Google, etc.).  Authorized resources are limited only to the official textbook and any lecture notes from the course.  Any other authorized resources will be provided to you before the exam.  The minimum sanction for violation of this policy is a grade of 0 on the affected exam.

Each student’s honesty and integrity are taken for granted. However, if I find evidence of academic misconduct I will pursue the matter to the fullest extent permitted by the university. ACADEMIC MISCONDUCT OR DISHONESTY WILL RESULT IN A GRADE OF F FOR THE COURSE.  Students are strongly advised to avoid even the /appearance/ of academic misconduct. 

** Academic Affairs Core Value Statements
*** Academic Integrity Statement
Tarleton State University's core values are integrity, leadership, tradition, civility, excellence, and service.  Central to these values is integrity, which is maintaining a high standard of personal and scholarly conduct.  Academic integrity represents the choice to uphold ethical responsibility for one’s learning within the academic community, regardless of audience or situation.

*** Academic Civility Statement 
Students are expected to interact with professors and peers in a respectful manner that enhances the learning environment. Professors may require a student who deviates from this expectation to leave the face-to-face (or virtual) classroom learning environment for that particular class session (and potentially subsequent class sessions) for a specific amount of time. In addition, the professor might consider the university disciplinary process (for Academic Affairs/Student Life) for egregious or continued disruptive behavior.

*** Academic Excellence Statement
Tarleton holds high expectations for students to assume responsibility for their own individual learning. Students are also expected to achieve academic excellence by:
- honoring Tarleton’s core values, upholding high standards of habit and behavior.
- maintaining excellence through class attendance and punctuality, preparing for active participation in all learning experiences. 
- putting forth their best individual effort.
- continually improving as independent learners.
- engaging in extracurricular opportunities that encourage personal and academic growth.
- reflecting critically upon feedback and applying these lessons to meet future challenges.

** Students with Disabilities Policy

It is the policy of Tarleton State University to comply with the Americans with Disabilities  Act (www.ada.gov) and other applicable laws.  If you are a student with a disability seeking accommodations for this course, please contact the Center for Access and Academic Testing, at 254.968.9400 or caat@tarleton.edu. The office is located in Math 201. More information can be found at www.tarleton.edu/caat or in the University Catalog.​
 
*Note:  any changes to this syllabus will be communicated to you by the instructor!*

** Semester Schedule

| Dates        | Topic                                                 |
|--------------+-------------------------------------------------------|
| Aug 20-21    | Course introduction - no homework assignment          |
| Aug 24-28    | Unit 1 - Measures of central tendency and variability |
| Aug 31-Sep 4 | Unit 2 - Transformations of scores / standardization  |
| Sep 7-11     | Unit 3 - The normal distribution                      |
| Sep 14-18    | Unit 4 - Distributions of sample means                |
| Sep 21-25    | *Exam 1* due Sunday, 9/27, at 11:59 pm                |
| Sep 28-Oct 2 | Unit 5 - Estimation and hypothesis testing            |
| Oct 5-9      | Unit 6.1 - Introduction to the \( t \)-test           |
| Oct 12-16    | Unit 6.2 - \( t \)-tests for independent samples      |
| Oct 19-23    | Unit 7 - Confidence intervals for \( t \)-tests       |
| Oct 26-30    | *Exam 2* due Sunday, 11/1, at 11:59 pm                |
| Nov 2-6      | Unit 8 - Analysis of variance                         |
| Nov 9-13     | Unit 9 - Introduction to Bayesian statistics          |
| Nov 16-20    | Unit 10 - Bayesian tests in JASP                      |
| Nov 23-27    | /no class due to Thanksgiving/                        |
| Nov 30-Dec 4 | *Exam 3* due Sunday, Dec 6, at 11:59 am               |


| header A | header B | header C                       |
|----------+----------+--------------------------------|
| cell 1   | cell 2   | cell 3                         |
| cell 4   | cell 5   | cell 6 (this is parenthetical) |
|          |          |                                |
