#+TITLE: PSYC 5303: Theories of Learning
#+AUTHOR: 
#+DATE: Fall 2022
#+OPTIONS: toc:nil
#+OPTIONS: num:nil
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [10pt]
#+LATEX_HEADER: \usepackage[left=1in,right=1in,bottom=1in,top=1in]{geometry}
#+LATEX_HEADER: \setlength{\parindent}{0pt}
#+LATEX_HEADER: \setlength{\parskip}{2mm}

** Contact info
- Professor: Thomas J. Faulkenberry, Ph.D
- Office: Math 301
- Office hours: /TBA/
- Email: faulkenberry@tarleton.edu
- Website: [[http://tomfaulkenberry.github.io]]
- Phone: 254-968-9816
  
** Course description

In this introductory level graduate course, we will survey a wide range of persepectives (both historical and current) on the theoretical principles of learning, memory, and cognition.  To accomplish this, you will read a variety of book chapters and journal articles that are chosen to help you develop a deep knowledge base of the theories, empirical methods, and applications of human learning, memory, and cognition. Additionally, students will get practice in writing and presenting scientific information.

** Course materials

There are several relevant textbooks for this course, but some are hard to find, expensive, or both!  Hence, I will be providing copies of selected chapters as we need them.  However, you are welcome to find your own copies of these books, as they are very good.

- Bower, G. H., & Hilgard, E. R. (1981). *Theories of Learning* (5th ed.). Englewood Cliffs, NJ: Prentice-Hall, Inc. ([[https://www.amazon.com/Theories-Learning-5th-Gordon-Bower/dp/0139144323][Amazon link]])
- Eichenbaum, H. (2008). *Learning & Memory*. New York: W. W. Norton Company. ([[https://www.amazon.com/Learning-Memory-Howard-Eichenbaum/dp/0393924475][Amazon link]])
- Lieberman, D. A. (2021). *Learning and memory* (2nd ed.). Cambridge University press ([[https://www.amazon.com/Learning-Memory-David-Lieberman/dp/1108428614/][Amazon link]])
- Neath, I., & Surprenant, A. M. (2003). *Human memory* (2nd ed.). Belmont, CA: Wadsworth. ([[https://www.amazon.com/Human-Memory-second-Neath-Surprenant/dp/B00BUWB592/][Amazon link]])

** Student learning outcomes

1. Discuss the experimental procedures used to study human learning, memory, and cognition.
2. Demonstrate an understanding of both contemporary and historically important conceptual frameworks in the study of human learning, memory, and cognition.
3. Discuss the theoretical arguments that have motivated research on human learning, memory, and cognition.
4. Write and present summaries of relevant modern research papers in human learning, memory, and cognition.

** Structure of class meetings and grading

This is a graduate-level course. Regular attendance and full participation in each weekly class session are essential requirements. You must carefully, thoroughly, and thoughtfully complete all reading and writing assignments *prior* to each class.  
Each week will be devoted to a single topic, supported by both secondary source material (i.e., textbook chapters) and primary source material (i.e., empirical journal articles). Before attending class any given week, you will need to complete /two readings/ -- one book chapter, and one empirical article.  All reading materials will be provided on Canvas.

I will assess your understanding of these readings two ways. First, at the beginning of class you will complete a short in-class quiz over the textbook reading. Second, you will turn in a one-page article summary (submitted /before/ class starts on Canvas) about *one* of the week's two assigned journal articles.  Your summary must contain the following:
  - describe the motivation for the experiment (i.e., what problem was the paper attempting to solve?)
  - a brief description of the method, particularly describing the key dependent variables (what was measured) and independent variables (what was manipulated)
  - a conceptual description of the results (don't list the statistical results, just tell me the "big picture")

After completing the in-class quiz, we will have a traditional lecture/discussion over the week's textbook reading.

After this lecture, we will take a short break, then conclude each class session with two student-led discussions over the assigned journal article readings. Here, two students will serve as discussion leaders.  This means they will have carefully read their assigned paper, read additional material as necessary, and prepared an oral presentation (with appropriate slides and/or handouts).  Class presentations should be short and to the point (no more than fifteen minutes for the presentation and an additional ten-fifteen minutes for discussion, giving a total of 30 minutes for each presenter).

In addition to the weekly contributions during class, there will be two in-class exams (one during our Week 8 meeting and one during our Week 15 meeting).  The week prior to each exam you will be given a set of 10-15 potential essay questions. Students may work together when preparing for the exam, but the exam will be completed individually. Answers should demonstrate "graduate-level thinking" -- this means that when you answer a question, you will support your arguments with empirical evidence (not just anecdotes or statements of what /you believe/) and give descriptions of specific experiments that lead to your conclusions. Six questions from the original list will be selected for the exam, and you will be asked to answer 5 of them. The questions will be based on material covered in lecture, assigned readings, and class discussions. The exams will be given in class, and you will not be able to consult any external materials. In other words, you will have to retrieve from your memory your responses to the practice exam.  Violations will result in a grade of ZERO on the exam.

These various components of your class performance will contribute to your grade as follows:

- Midterm exam (25%)
- Final exam (25%)
- Weekly quizzes (20%)
- Weekly article summaries (20%)
- Leading discussions of assigned readings (10%)

** Additional notes for Zoom attendees

This class allows Zoom attendance for students outside the Stephenville campus area. Students enrolled in the Stephenville section (010) should plan to attend /in person/. However, students in the Zoom section (011) may attend either in person or by Zoom. The Zoom link is posted prominently on the Canvas page for the course. Attending by Zoom requires that you have access to a computer with a camera, microphone, and speakers/headphones. Please set up a quiet workspace so that you can concentrate fully on the class session. Your camera should be turned ON during the entire class session (except during breaks). All quizzes and exams will be completed on Canvas -- they will be opened at the exact moment that the corresponding "paper" version is handed out in the Stephenville class. Note that the two exams (Midterm and Final) will require the use of the Respondus lock-down browser (i.e., the online equivalent of a "closed book exam"). 

** Course Communication

This course is designed to be an intensive, interactive course on modern statistical methods and experimental design.  That means that I will be available for one-on-one consultation most any time.  Just stop by my office or give me a call.

All official course communication (questions, setting up a meeting, etc.) will be conducted by email.  Any time you need to contact me, feel free to send me an email at faulkenberry@tarleton.edu.  I only ask that you adhere to two guidelines:
  - please include the course number (PSYC 5303) in the subject line.  For example, one good way to do this is:  Subject: [PSYC 5303] Question about week 3 assignment.
  - please use proper email etiquette.  Include a salutation (e.g., Dear Dr. Faulkenberry), complete sentences, and a closing (e.g., "Regards, Your Name").  You might be surprised how many times I get an email from a nondescript email address with no indication from WHOM the email was sent!

Also, I will be sending periodic emails to each of you that update you on course progress, due dates, etc.  It is imperative that you check your /Tarleton email address/ regularly so that you don't miss any of these messages.

** University Policy on "F" Grades
Beginning in Fall 2015, Tarleton will begin differentiating between a failed grade in a class because a student never attended (F0 grade), stopped attending at some point in the semester (FX grade), or because the student did not pass the course (F) but attended the entire semester. These grades will be noted on the official transcript. Stopping or never attending class can result in the student having to return aid monies received.  For more information see the Tarleton Financial Aid website.

** Academic Honesty

Tarleton State University expects its students to maintain high standards of personal and scholarly conduct. Students guilty of academic dishonesty are subject to disciplinary action. Cheating, plagiarism (submitting another person’s materials or ideas as one’s own), or doing work for another person who will receive academic credit are all disallowed. This includes the use of unauthorized books, notebooks, or other sources in order to secure of give help during an examination, the unauthorized copying of examinations, assignments, reports, or term papers, or the presentation of unacknowledged material as if it were the student’s own work. Disciplinary action may be taken beyond the academic discipline administered by the faculty member who teaches the course in which the cheating took place.

In particular, any exam taken online must be completed without the aid of any unauthorized resource (including using any search engine, Google, etc.).  Authorized resources are limited only to the official textbook and any lecture notes from the course.  Any other authorized resources will be provided to you before the exam.  The minimum sanction for violation of this policy is a grade of 0 on the affected exam.

Each student’s honesty and integrity are taken for granted. However, if I find evidence of academic misconduct I will pursue the matter to the fullest extent permitted by the university. ACADEMIC MISCONDUCT OR DISHONESTY WILL RESULT IN A GRADE OF F FOR THE COURSE.  Students are strongly advised to avoid even the /appearance/ of academic misconduct. 

** Academic Affairs Core Value Statements

*** Academic Integrity Statement
Tarleton State University's core values are integrity, leadership, tradition, civility, excellence, and service.  Central to these values is integrity, which is maintaining a high standard of personal and scholarly conduct.  Academic integrity represents the choice to uphold ethical responsibility for one’s learning within the academic community, regardless of audience or situation.

*** Academic Civility Statement 
Students are expected to interact with professors and peers in a respectful manner that enhances the learning environment. Professors may require a student who deviates from this expectation to leave the face-to-face (or virtual) classroom learning environment for that particular class session (and potentially subsequent class sessions) for a specific amount of time. In addition, the professor might consider the university disciplinary process (for Academic Affairs/Student Life) for egregious or continued disruptive behavior.

*** Academic Excellence Statement
Tarleton holds high expectations for students to assume responsibility for their own individual learning. Students are also expected to achieve academic excellence by:
- honoring Tarleton’s core values, upholding high standards of habit and behavior.
- maintaining excellence through class attendance and punctuality, preparing for active participation in all learning experiences. 
- putting forth their best individual effort.
- continually improving as independent learners.
- engaging in extracurricular opportunities that encourage personal and academic growth.
- reflecting critically upon feedback and applying these lessons to meet future challenges.

** Students with Disabilities Policy

It is the policy of Tarleton State University to comply with the Americans with Disabilities  Act (www.ada.gov) and other applicable laws.  If you are a student with a disability seeking accommodations for this course, please contact the Center for Access and Academic Testing, at 254.968.9400 or caat@tarleton.edu. The office is located in Math 201. More information can be found at www.tarleton.edu/caat or in the University Catalog.​
 
*Note:  any changes to this syllabus will be communicated to you by the instructor!*
 
** Semester schedule



- Week 1 (8/23): Introduction and syllabus overview; what is learning?
  - Background reading:
    - Chapter 1 of Eichenbaum
  - Student presentations:
    - *none this week*

- Week 2 (8/30): Mechanisms of classical conditioning
  - Background reading:
    - Chapter 5 of Eichenbaum
  - Student presentations:
    - Clark, R. E., & Squire, L. R. (1998). Classical conditioning and brain systems: The role of awareness. /Science, 280/ (3), 77-81.
    - Orr, S. P., et al. (2000). De novo conditioning in trauma-exposed individuals with and without posttraumatic stress disorder. /Journal of Abnormal Psychology, 109/ (2), 290-298
        
- Week 3 (9/6): Mechanisms of instrumental conditioning
  - Background reading:
    - Chapter 6 of Eichenbaum
  - Student presentations:
    - Skinner, B. F. (1948). Superstition in the pigeon. /Journal of Experimental Psychology, 38/, 168-172.
    - Powell, R. W. (1972). Operant conditioning in the common crow (Corvus brachyrhynchos). /The Auk, 89/ (4), 738-742.

- Week 4 (9/13): Human associative learning
  - Background reading:
    - Chapter 6 of Bower & Hilgard
  - Student presentations:
    - Roediger, H. L., & Karpicke, J. D. (2006). Test-enhanced learning: Taking memory tests improves long-term retention. /Psychological Science, 17/ (3), 249-255.
    - Roediger, H. L., & Crowder, R. G. (1976). A serial position effect in recall of United States presidents. /Bulletin of the Psychonomic Society, 8/ (4), 275-278.

- Week 5 (9/20): The classic multi-store model of human memory
  - Background reading:
    - Chapter 3 of Neath and Surprenant
  - Student presentations:
    - Glanzer, M., & Cunitz, A. R. (1966). Two storage mechanisms in free recall. /Journal of Verbal Learning and Verbal Behavior, 5/ , 351-360.
    - Bjork, R. A., & Whitten, W. B. (1974). Recency-sensitive retrieval processes in long-term free recall. /Cognitive Psychology, 6/, 173-189.

- Week 6 (9/27): Working memory
  - Background reading:
    - Chapter 4 of Neath and Surprenant
  - Student presentations:
    - Trbovich, P. L., & LeFevre, J. (2003). Phonological and visual working memory in mental addition. /Memory & Cognition, 31/ (5), 738-745.
    - Miyake, A., & Friedman, N. P. (2012). The nature and organization of individual differences in executive functions: Four general conclusions. /Current Directions in Psychological Science, 21/ (1), 8-14.

- Week 7 (10/4): Encoding and retrieval processes / *turn in paragraph describing your experimental proposal*
  - Background reading:
    - Chapter 5 of Neath and Surprenant
  - Student presentations:
    - Bjork, R. A., & Allen, T. W. (1970). The spacing effect: Consolidation or differential encoding? /Journal of Verbal Learning and Verbal Behavior, 9/, 567-572.
    - Mulligan, N. W., & Lozito, J. P. (2006). An asymmetry between memory encoding and retrieval: Revelation, generation, and transfer-appropriate processing. /Psychological Science, 17/ (1), 7-11.
        
- Week 8 (10/11): *Midterm exam*

- Week 9 (10/18): Forgetting
  - Background reading:
    - Chapter 6 of Neath and Surprenant
  - Student presentations:
    - Anderson, M. C., Bjork, E. L., & Bjork, R. A. (2000). Retrieval-induced forgetting: Evidence for a recall-specific mechanism. /Psychonomic Bulletin & Review, 7/ (3), 522-530.
    - Campbell, J. I. D., & Thompson, V. A. (2012). Retrieval-induced forgetting of arithmetic facts. /Journal of Experimental Psychology: Learning, Memory, and Cognition, 38/ (1), 118-129.

- Week 10 (10/25):  *Outline of research proposals due, in-class presentations of outlines*

- Week 11 (11/1): Implicit memory 
  - Background reading:
    - Chapter 7 of Neath and Surprenant
  - Student presentations:
    - *coming soon*


- Week 12 (11/8): Knowledge representations in long-term memory
    - Background reading:
        - Chapter 10 of Neath and Surprenant
    - Student presentations:
        - *coming soon*

- Week 13 (11/15): Topic TBA
    - Background reading:
      - *coming soon*
    - Student presentations:
        - *coming soon*

- Week 14 (11/29): *Final exam*
        
- Week 15 (12/7): *In-class presentations of research proposals*

  
