
** Semester schedule

- Week 1 (8/23): Introduction and syllabus overview; what is learning?
  - Background reading:
    - Chapter 1 of Eichenbaum
  - Student presentations:
    - *none this week*

- Week 2 (8/30): Mechanisms of classical conditioning
  - Background reading:
    - Chapter 5 of Eichenbaum
  - Student presentations:
    - Clark, R. E., & Squire, L. R. (1998). Classical conditioning and brain systems: The role of awareness. /Science, 280/ (3), 77-81.
    - Orr, S. P., et al. (2000). De novo conditioning in trauma-exposed individuals with and without posttraumatic stress disorder. /Journal of Abnormal Psychology, 109/ (2), 290-298
        
- Week 3 (9/6): Mechanisms of instrumental conditioning
  - Background reading:
    - Chapter 6 of Eichenbaum
  - Student presentations:
    - Skinner, B. F. (1948). Superstition in the pigeon. /Journal of Experimental Psychology, 38/, 168-172.
    - Powell, R. W. (1972). Operant conditioning in the common crow (Corvus brachyrhynchos). /The Auk, 89/ (4), 738-742.

- Week 4 (9/13): Human associative learning
  - Background reading:
    - Chapter 6 of Bower & Hilgard
  - Student presentations:
    - Roediger, H. L., & Karpicke, J. D. (2006). Test-enhanced learning: Taking memory tests improves long-term retention. /Psychological Science, 17/ (3), 249-255.
    - Roediger, H. L., & Crowder, R. G. (1976). A serial position effect in recall of United States presidents. /Bulletin of the Psychonomic Society, 8/ (4), 275-278.

- Week 5 (9/20): The classic multi-store model of human memory
  - Background reading:
    - Chapter 3 of Neath and Surprenant
  - Student presentations:
    - Glanzer, M., & Cunitz, A. R. (1966). Two storage mechanisms in free recall. /Journal of Verbal Learning and Verbal Behavior, 5/ , 351-360.
    - Bjork, R. A., & Whitten, W. B. (1974). Recency-sensitive retrieval processes in long-term free recall. /Cognitive Psychology, 6/, 173-189.

- Week 6 (9/27): Working memory
  - Background reading:
    - Chapter 4 of Neath and Surprenant
  - Student presentations:
    - Trbovich, P. L., & LeFevre, J. (2003). Phonological and visual working memory in mental addition. /Memory & Cognition, 31/ (5), 738-745.
    - Miyake, A., & Friedman, N. P. (2012). The nature and organization of individual differences in executive functions: Four general conclusions. /Current Directions in Psychological Science, 21/ (1), 8-14.

- Week 7 (10/4): Encoding and retrieval processes / *turn in paragraph describing your experimental proposal*
  - Background reading:
    - Chapter 5 of Neath and Surprenant
  - Student presentations:
    - Bjork, R. A., & Allen, T. W. (1970). The spacing effect: Consolidation or differential encoding? /Journal of Verbal Learning and Verbal Behavior, 9/, 567-572.
    - Mulligan, N. W., & Lozito, J. P. (2006). An asymmetry between memory encoding and retrieval: Revelation, generation, and transfer-appropriate processing. /Psychological Science, 17/ (1), 7-11.
        
- Week 8 (10/11): *Midterm exam*

- Week 9 (10/18): Forgetting
  - Background reading:
    - Chapter 6 of Neath and Surprenant
  - Student presentations:
    - Anderson, M. C., Bjork, E. L., & Bjork, R. A. (2000). Retrieval-induced forgetting: Evidence for a recall-specific mechanism. /Psychonomic Bulletin & Review, 7/ (3), 522-530.
    - Campbell, J. I. D., & Thompson, V. A. (2012). Retrieval-induced forgetting of arithmetic facts. /Journal of Experimental Psychology: Learning, Memory, and Cognition, 38/ (1), 118-129.

- Week 10 (10/25):  *Outline of research proposals due, in-class presentations of outlines*

- Week 11 (11/1): Implicit memory 
  - Background reading:
    - Chapter 7 of Neath and Surprenant
  - Student presentations:
    - *coming soon*


- Week 12 (11/8): Knowledge representations in long-term memory
    - Background reading:
        - Chapter 10 of Neath and Surprenant
    - Student presentations:
        - *coming soon*

- Week 13 (11/15): Topic TBA
    - Background reading:
      - *coming soon*
    - Student presentations:
        - *coming soon*

- Week 14 (11/29): *Final exam*
        
- Week 15 (12/7): *In-class presentations of research proposals*

  
