#+TITLE: PSYC 5316: Advanced Quantitative Methods & Experimental Design
#+AUTHOR: 
#+DATE: Fall 2023
#+OPTIONS: toc:nil
#+OPTIONS: num:nil
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [10pt]
#+LATEX_HEADER: \usepackage[left=1in,right=1in,bottom=1in,top=1in]{geometry}
#+LATEX_HEADER: \setlength{\parindent}{0pt}
#+LATEX_HEADER: \setlength{\parskip}{2mm}

** Contact info
- Professor: Thomas J. Faulkenberry, Ph.D
- Office: Math 301
- Office hours: /TBA/
- Email: faulkenberry@tarleton.edu
- Website: [[http://tomfaulkenberry.github.io]]
- Phone: 254-968-9816
  
** Course description

This course is designed to teach you the advanced quantitative methods and techniques of experimental design that are necessary to read and conduct modern empirical research in the behavioral sciences. We will do this through replicating three classic experiments, each illustrating a unique experimental design and technique for data analysis.  Students taking this course are expected to have *previously* taken a graduate level course in statistics (or equivalent statistical training). 

Some of the specific skills you'll learn this semester are:
- using a computer to program behavioral experiments and collect response time data 
- efficiently pre-processing raw data and implement sophisticated statistical models using R
- writing technical manuscripts to report results of experiments

** Course materials

There is no required textbook for the course. However, I recommend you have access to a good statistics textbook ([[https://www.amazon.com/Psychological-Statistics-Basics-Thomas-Faulkenberry-dp-1032020954/dp/1032020954][mine]] is cheap). In addition, you'll need to have access to a computer (laptop is best) on which you can install the following software packages:

- R statistical software (free download from [[http://www.r-project.org][https://www.r-project.org]])
- RStudio (free download from [[http://www.rstudio.com][https://www.rstudio.com]])
- OpenSesame (free download from https://osdoc.cogsci.nl/

** Student learning outcomes
   
1. perform and interpret basic techniques of statistical inference, both in a frequentist and Bayesian framework
2. program and administer behavioral experiments using computer software
3. understand various methods of cleaning data for analysis in R
4. develop skills for communicating technical material, especially through writing scientific manuscripts in APA format.

** Requirements and grading

You will complete four lab activities throughout the semester. With the exception of the first lab on how to use R, the labs will each take four weeks, following the same basic schedule:

- first week: you will watch a video lecture describing to build the experiment in OpenSesame, then build your own version and submit it to me for a grade (10 points)
- second week: you will ask four friends to participate in your experiment, collect their data, and submit it to me for a grade (20 points)
- third week: you will watch a video lecture describing how to use R to analyze the collected data from the class, then complete and submit a corresponding data analysis assignment for a grade (30 points)
- fourth week: you will write a short APA-formatted manuscript describing the experiment and the results, and submit for a grade (40 points)

The labs I've planned for this semester are as follows:

- Lab 1 - Introduction to R statistical software 
- Lab 2 - flanker task (an experiment on attention)
- Lab 3 - Sternberg memory scanning task (an experiment on short term memory)
- Lab 4 - addition verification task (an experiment on mathematical cognition)

Lab 1 is worth 50 points, and Labs 2-4 are each worth 100 points. Grades will be assigned based on the percentage of points you accumulate out of a total possible 350 points.  I will use the standard grading scale of A=90%, B=80%, etc.

** Course Communication

This course is designed to be an intensive, interactive course on modern statistical methods and experimental design.  That means that I will be available for one-on-one consultation most any time.  Just stop by my office or give me a call.

All official course communication (questions, setting up a meeting, etc.) will be conducted by email.  Any time you need to contact me, feel free to send me an email at faulkenberry@tarleton.edu.  I only ask that you adhere to two guidelines:
  - please include the course number (PSYC 5316) in the subject line.  For example, one good way to do this is:  Subject: [PSYC 5316] Question about problem set 3
  - please use proper email etiquette.  Include a salutation (e.g., Dear Dr. Faulkenberry), complete sentences, and a closing (e.g., "Regards, Your Name").  You might be surprised how many times I get an email from a nondescript email address with no indication from WHOM the email was sent!

Note, I will send periodic class announcements via Canvas messaging. However, I ask that you send your questions by email instead of Canvas messaging. 

** Academic Integrity Statement and Policy

Cheating, plagiarism, or doing work for another person who will receive academic credit is impermissible. This includes the use of unauthorized books, notebooks, or other sources in order to secure or give help during an examination, the unauthorized copying of examinations, assignments, reports, or term papers, or the presentation of unacknowledged material as if it were the own work. Disciplinary action may be taken beyond the academic discipline administered by the faculty member who teaches the course in which the cheating took place. Consult the following links for further information on academic conduct. 
  - Student Judicial Affairs: https://www.tarleton.edu/judicial/academicconduct.html  
  - Student Handbook: https://www.tarleton.edu/studentrules/code-of-student-conduct.html  

** Americans with Disabilities Act (ADA) - Student Success

Tarleton State University is committed to complying with the Americans with Disabilities Act (www.ada.gov) and other applicable laws. If you are a student with a disability seeking accommodation for this course, please contact the Office of Disability Resources at 254.968.9400, disability@tarleton.edu, or visit https://www.tarleton.edu/drt/.  

** Academic Affairs Core Values in the Classroom

*** Academic Integrity
Tarleton State University's core values are integrity, excellence, and respect. Central to these values is integrity, which is maintaining a high standard of personal and scholarly conduct. Academic integrity represents the choice to uphold ethical responsibility for one’s learning within the academic community, regardless of audience or situation.

*** Academic Excellence
Tarleton holds high expectations for students to assume responsibility for their own individual learning.  Students are also expected to achieve academic excellence by:
  - honoring Tarleton’s core values. 
  - upholding high standards of habit and behavior. 
  - maintaining excellence through class attendance and punctuality. 
  - preparing for active participation in all learning experiences. 
  - putting forth their best individual effort. 
  - continually improving as independent learners. 
  - engaging in extracurricular opportunities that encourage personal and academic growth. 
  - reflecting critically upon feedback and applying these lessons to meet future challenges.

*** Academic Respect
Students are expected to interact with professors and peers in a respectful manner that enhances the learning environment. Professors may require a student who deviates from this expectation to leave the face-to-face (or virtual) classroom learning environment for that particular class session (and potentially subsequent class sessions) for a specific amount of time. In addition, the professor might consider the university disciplinary process (for Academic Affairs/Student Life) for egregious or continued disruptive behavior.


*** Student Rules
Students are responsible for knowing and abiding by the policies and information contained in the Tarleton Student Rules - https://www.tarleton.edu/studentrules.  

*Note:  any changes to this syllabus will be communicated to you by the instructor!*
 
** Tentative schedule

| Assignment | Due Date | Topics covered                                              |
|------------+----------+-------------------------------------------------------------|
|          1 | 9/3      | Lab 1.1: installation and the basics of R                   |
|          2 | 9/10     | Lab 1.2: performing basic statistical tests in R            |
|          3 | 9/17     | Lab 2.1: programming the flanker task                       |
|          4 | 9/24     | Lab 2.2: collecting data from the flanker task              |
|          5 | 10/1     | Lab 2.3: analyzing the flanker data                         |
|          6 | 10/8     | Lab 2.4: writing the flanker manuscript                     |
|          7 | 10/15    | Lab 3.1: programming the Sternberg memory scanning task     |
|          8 | 10/22    | Lab 3.2: collecting data from the Sternberg task            |
|          9 | 10/29    | Lab 3.3: analyzing the Sternberg data                       |
|         10 | 11/5     | Lab 3.4: writing the Sternberg manuscript                   |
|         11 | 12/3     | Lab 4.1: collecting data for the addition verification task |
|         12 | 12/10    | Lab 4.2: analyzing the addition data                        |
