#+TITLE: PSYC 3330: Elementary Statistics for the Behavioral Sciences
#+AUTHOR: 
#+DATE: Fall 2018
#+OPTIONS: toc:nil
#+OPTIONS: num:nil
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [10pt]
#+LATEX_HEADER: \usepackage[left=1in,right=1in,bottom=1in,top=1in]{geometry}

** Contact info
- Professor: Thomas J. Faulkenberry, Ph.D
- Office: Math 319
- Office hours: MWF 1-3 pm, TR 9:30-11:30 am (/or by appointment/)
- Email: faulkenberry@tarleton.edu
- Website: [[http://tomfaulkenberry.github.io]]
- Phone: 254-968-9816

** Course description

Statistical methods are the primary tool for research in psychology.  
They are what allow us as researchers to make consistent, data-driven 
decisions.  As such, this is an extremely important course and one that I 
take very seriously as your professor.

The topics we will cover this semester will include descriptive statistics 
(how we describe data) and inferential statistics (how we make decisions 
about data).  Specifically, this includes central tendency, variability, 
correlation, the distinction between populations and samples, hypothesis 
testing, statistical significance, and a variety of inferential tests 
that we can apply to data, including t-tests and analysis of variance.

** Course materials
- /Statistics for the Behavioral Sciences (10th ed.)/ by Gravetter and Wallnau [[http://www.amazon.com/Statistics-Behavioral-Sciences-MindTap-Psychology/dp/1305504917/][Amazon link]]
- Note:  older editions of this textbook are just fine.  Please feel free to find a used copy of an older edition on Amazon; it will save you a LOT of money!
  
** Student learning outcomes
1. Identify variables under study (including independent and dependent variables)
2. Choose appropriate measures of descriptive statistics
3. Select and perform appropriate inferential statistics
4. Draw appropriate statistical conclusions from results of analyses

** Requirements and grading
- Exam 1 (100 pts)
- Exam 2 (100 pts)
- Exam 3 (100 pts)
- Final exam (100 pts)
- Weekly quizzes (100 pts)
- /Total = 500 points/

Grades will be assigned based on the percentage of points you accumulate out of these 500 points.  I will use the standard grading scale of A=90%, B=80%, etc.

*** Exams (80% of grade)
There will be four total exams throughout the semester, occurring approximately once every three to four weeks.  They will cover material from lectures, quizzes, and homework exercises.  Exam questions will be a mix of multiple choice and short answer.  Exams will be completed in class.

Exam dates:

- Exam 1 (Thursday, September 20)
- Exam 2 (Thursday, October 18)
- Exam 3 (Thursday, November 29)
- Final exam (Tuesday, December 11, 8-10:30 am)
  
*** Weekly quizzes (20% of grade)
Before each week's lectures, I will assign a short lecture video for you to watch on Blackboard that will help you to prepare for the content we will be covering. To assess your understanding of the material, I will administer a short in-class quiz at the beginning of class on Tuesday of each week (excluding exam weeks). Each quiz counts for 10 possible points.  Since there are 10 such quizzes, you will earn up to 100 points for your overall quiz grade.

** Course Communication

Email is the primary means of official communication for this course.  If you have questions about the course, always feel free to send me an email at faulkenberry@tarleton.edu.  I only ask that you adhere to two guidelines:
  - please include the course number (PSYC 3330) in the subject line.  For example, one good way to do this is:  Subject: [PSYC 3330] Question about Exam 2
  - please use proper email etiquette.  Include a salutation (e.g., Dear Dr. Faulkenberry), complete sentences, and a closing (e.g., "Regards, Your Name").  You might be surprised how many times I get an email from a nondescript email address with no indication from WHOM the email was sent!

Also, I will send periodic class announcements via email.  Thus, it is imperative that you check your /Tarleton email address/ regularly so that you don't miss any of these messages.

** University Policy on "F" Grades
Beginning in Fall 2015, Tarleton will begin differentiating between a failed grade in a class because a student never attended (F0 grade), stopped attending at some point in the semester (FX grade), or because the student did not pass the course (F) but attended the entire semester. These grades will be noted on the official transcript. Stopping or never attending class can result in the student having to return aid monies received.  For more information see the Tarleton Financial Aid website.

** Academic Honesty

Tarleton State University expects its students to maintain high standards of personal and scholarly conduct. Students guilty of academic dishonesty are subject to disciplinary action. Cheating, plagiarism (submitting another person’s materials or ideas as one’s own), or doing work for another person who will receive academic credit are all disallowed. This includes the use of unauthorized books, notebooks, or other sources in order to secure of give help during an examination, the unauthorized copying of examinations, assignments, reports, or term papers, or the presentation of unacknowledged material as if it were the student’s own work. Disciplinary action may be taken beyond the academic discipline administered by the faculty member who teaches the course in which the cheating took place.

In particular, any exam taken online must be completed without the aid of any unauthorized resource (including using any search engine, Google, etc.).  Authorized resources are limited only to the official textbook and any lecture notes from the course.  Any other authorized resources will be provided to you before the exam.  The minimum sanction for violation of this policy is a grade of 0 on the affected exam.

Each student’s honesty and integrity are taken for granted. However, if I find evidence of academic misconduct I will pursue the matter to the fullest extent permitted by the university. ACADEMIC MISCONDUCT OR DISHONESTY WILL RESULT IN A GRADE OF F FOR THE COURSE.  Students are strongly advised to avoid even the /appearance/ of academic misconduct. 

** Academic Affairs Core Value Statements
*** Academic Integrity Statement
Tarleton State University's core values are integrity, leadership, tradition, civility, excellence, and service.  Central to these values is integrity, which is maintaining a high standard of personal and scholarly conduct.  Academic integrity represents the choice to uphold ethical responsibility for one’s learning within the academic community, regardless of audience or situation.

*** Academic Civility Statement 
Students are expected to interact with professors and peers in a respectful manner that enhances the learning environment. Professors may require a student who deviates from this expectation to leave the face-to-face (or virtual) classroom learning environment for that particular class session (and potentially subsequent class sessions) for a specific amount of time. In addition, the professor might consider the university disciplinary process (for Academic Affairs/Student Life) for egregious or continued disruptive behavior.

*** Academic Excellence Statement
Tarleton holds high expectations for students to assume responsibility for their own individual learning. Students are also expected to achieve academic excellence by:
- honoring Tarleton’s core values, upholding high standards of habit and behavior.
- maintaining excellence through class attendance and punctuality, preparing for active participation in all learning experiences. 
- putting forth their best individual effort.
- continually improving as independent learners.
- engaging in extracurricular opportunities that encourage personal and academic growth.
- reflecting critically upon feedback and applying these lessons to meet future challenges.

** Students with Disabilities Policy

It is the policy of Tarleton State University to comply with the Americans with Disabilities  Act (www.ada.gov) and other applicable laws.  If you are a student with a disability seeking accommodations for this course, please contact the Center for Access and Academic Testing, at 254.968.9400 or caat@tarleton.edu. The office is located in Math 201. More information can be found at www.tarleton.edu/caat or in the University Catalog.​
 
*Note:  any changes to this syllabus will be communicated to you by the instructor!*
 
** Semester Schedule
| Week | Dates        | Topic                                                        |
|------+--------------+--------------------------------------------------------------|
|    1 | Aug 27-31    | Displaying data                                              |
|    2 | Sep 3-7      | Descriptives 1: central tendency, variation, and z-scores    |
|    3 | Sep 10-14    | Descriptives 2: correlation                                  |
|    4 | Sep 17-21    | *Exam 1*                                                     |
|    5 | Sep 24-28    | The normal distribution: measuring likelihood                |
|    6 | Oct 1-5      | The logic of hypothesis testing                              |
|    7 | Oct 8-12     | Testing means of samples of *known* populations: \(z\)-tests |
|    8 | Oct 15-19    | *Exam 2*                                                     |
|    9 | Oct 22-26    | Testing means of samples of *unknown* populations: \(t\)-tests |
|   10 | Oct 29-Nov 2 | More \(t\)-tests (independent samples, etc.)                 |
|   11 | Nov 5-9      | Analysis of variance (ANOVA): one independent variable       |
|   12 | Nov 12-16    | Nonparametric techniques: chi-square and binomial tests      |
|   13 | Nov 19-23    | /No coursework during week of Thanksgiving holiday/          |
|   14 | Nov 26-30    | *Exam 3*                                                     |
|   15 | Dec 3-7      | Course review (no class on Thursday)                         |
|   16 | Dec 10-14    | *Final exam on Tuesday, Dec 11, 8-10:30 am*                  |
