#+TITLE: PSYC 5301: Research Methods
#+AUTHOR: 
#+DATE: Spring 2017
#+OPTIONS: toc:nil
#+OPTIONS: num:nil
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [10pt]
#+LATEX_HEADER: \usepackage[left=1in,right=1in,bottom=1in,top=1in]{geometry}

** Contact info
- Professor: Thomas J. Faulkenberry, Ph.D
- Office: Math 319
- Office hours: MTWRF 1-3 pm
- Email: faulkenberry@tarleton.edu
- Website: [[http://tomfaulkenberry.github.io]]
- Phone: 254-968-9816

** Course description

This course is designed to provide the student with a solid grounding in
the techniques of experimentation and subsequent statistical modeling that
form the empirical basis of modern psychological science.  We will 
accomplish this through lectures, textbook reading, and several hands-on
"laboratory" experiences, each designed to give the student a taste of the
research process, including data collection, analysis, and reporting.
All students enrolled in this course are required to have 
*previously taken* PSYC 5300 (Behavioral Statistics) or have equivalent
statistical background.  Note that we will meet face-to-face approximately 
once every two weeks (see schedule below). 

** Course materials

- /The Design and Conduct of Meaningful Experiments Involving Human Participants: 25 Scientific Principles/ by R. B. Bausell [[https://www.amazon.com/Conduct-Meaningful-Experiments-Involving-Participants/dp/0199385238][Amazon link]]
- /APA Publication Manual/ (6th ed.) [[http://www.amazon.com/Publication-Manual-American-Psychological-Association/dp/1433805618/][Amazon link]]
- JASP statistical software (free download from [[http://jasp-stats.org][jasp-stats.org]]).  Make sure your version is at least 0.8.

** Student learning outcomes

1. Understand the classical frameworks of hypothesis testing in psychological research
2. Develop research questions and translate those to testable hypotheses
3. Collect data using a variety of standard research paradigms
4. Analyze data using computer software
5. Communicate research results as a complete APA style manuscript
6. Develop a complete IRB protocol

** Requirements and grading
- Labs (150 points)
- Online discussions (100 points)
- IRB protocol (100 points)
- Class participation (50 points)
- /Total = 400 points/

Grades will be assigned based on the percentage of points you accumulate 
out of these 400 points.  I will use the standard grading scale of A=90%, 
B=80%, etc.

*** Labs (37.5% of grade)
There will be 3 lab assignments this semester.  The purpose of these 
assignments is to familiarize you with the complete research process, from
collecting data to analyzing the data and writing up the resulting manuscript.
The labs will involve the basic designs used in much of the psychological
literature, including independent groups designs, repeated measures designs,
and factorial designs.  Each lab is worth 50 points (10 points for the data you
collect and 40 points for the resulting manuscript). 

*** Online discussions (25% of grade)
Every online week (see schedule below), you will be given a reading from the textbook and/or other
external papers.  To ensure sufficient understanding of the readings, you will
participate in an online discussion.  These discussions will revolve around a 
small number of prompts, to which you will be required to (1) compose your 
response, and (2) respond to your classmates.  The grades will be assigned
largely on a /completion/ basis, but substantive responses are required.  You
/cannot/ simply respond "I agree" or "I disagree"...you must substantiate
your response(s) with data and/or a logical argument. 

*** IRB protocol (25% of grade)
In order to complete the research component of your MS degree, you will have
to complete an IRB protocol that documents your procedures to ensure that your
research will be conducted in a manner that is considered ethical.  To help with
this process, you will be asked to complete an IRB protocol in this course
using the submission form developed by the IRB at our university. 
The topic that you propose to study and the research questions you ask are up 
to you; the important part is that your study is (1) well-designed, and (2) 
all ethical protocols are prepared and in place.

The assignment for your protocol will be divided into two major portions.  First,
you will complete a protocol and submit it to me (around Week 14).  I will then
assign each protocol to two class members for peer review.  The purpose of this
peer review is to model the process that happens at our university (each protocol
is assigned to two peer reviewers) as well as to give you two sets of feedback
on your protocol that should help with your actual protocols that you submit
to conduct your MS research.

*** Class participation (12.5% of grade)
This is a very active course.  It is essential that you participate in /all/
activities, both online and in our face-to-face sessions.  Your class participation
grade will be reflective of the effort that I've seen you put into the course.
Most people will earn all 50 possible points, but I reserve the right to lower
this grade if you miss excessive class meetings.

** Course Communication

I am your primary resource for this course. I AM an experimental psychologist, so I do the stuff I teach about daily. Hence, my primary interest is for you to learn this material and do well in the course. If you have a question, always feel free to stop by my office and visit.  If you require electronic communication, email is best, but you may also send me a Blackboard message.  Just keep in mind that I don't get any notifications of Blackboard messages, so I may not see your message until I next log into the course.

** University Policy on "F" Grades

Beginning in Fall 2015, Tarleton will begin differentiating between a failed grade in a class because a student never attended (F0 grade), stopped attending at some point in the semester (FX grade), or because the student did not pass the course (F) but attended the entire semester. These grades will be noted on the official transcript. Stopping or never attending class can result in the student having to return aid monies received.  For more information see the Tarleton Financial Aid website.

** Academic Honesty

Cheating, plagiarism (submitting another person’s materials or ideas as one’s own), or doing work for another person who will receive academic credit are all disallowed. This includes the use of unauthorized books, notebooks, or other sources in order to secure of give help during an examination, the unauthorized copying of examinations, assignments, reports, or term papers, or the presentation of unacknowledged material as if it were the student’s own work. Disciplinary action may be taken beyond the academic discipline administered by the faculty member who teaches the course in which the cheating took place.

In particular, any exam taken online must be completed without the aid of any unauthorized resource (including using any search engine, Google, etc.).  Authorized resources are limited only to the official textbook and any lecture notes from the course.  Any other authorized resources will be provided to you before the exam.  The minimum sanction for violation of this policy is a grade of 0 on the affected exam.

** Academic Affairs Core Value Statements

*** Academic Integrity Statement
Tarleton State University's core values are integrity, leadership, tradition, civility, excellence, and service.  Central to these values is integrity, which is maintaining a high standard of personal and scholarly conduct.  Academic integrity represents the choice to uphold ethical responsibility for one’s learning within the academic community, regardless of audience or situation.

*** Academic Civility Statement 
Students are expected to interact with professors and peers in a respectful manner that enhances the learning environment. Professors may require a student who deviates from this expectation to leave the face-to-face (or virtual) classroom learning environment for that particular class session (and potentially subsequent class sessions) for a specific amount of time. In addition, the professor might consider the university disciplinary process (for Academic Affairs/Student Life) for egregious or continued disruptive behavior.

*** Academic Excellence Statement
Tarleton holds high expectations for students to assume responsibility for their own individual learning. Students are also expected to achieve academic excellence by:
- honoring Tarleton’s core values, upholding high standards of habit and behavior.
- maintaining excellence through class attendance and punctuality, preparing for active participation in all learning experiences. 
- putting forth their best individual effort.
- continually improving as independent learners.
- engaging in extracurricular opportunities that encourage personal and academic growth.
- reflecting critically upon feedback and applying these lessons to meet future challenges.

** Students with Disabilities Policy

It is the policy of Tarleton State University to comply with the Americans with Disabilities Act and other applicable laws. If you are a student with a disability seeking accommodations for this course, please contact the Center for Access and Academic Testing, at 254.968.9400 or caat@tarleton.edu. The office is located in Math 201. More information can be found at www.tarleton.edu/caat or in the University Catalog.



**Note:  any changes to this syllabus will be communicated to you by the instructor!**
 
** Tentative weekly schedule
/Note: this schedule will be updated as the semester goes!/
- Week 1: Jan 17 (face-to-face)
  - intro to course
  - review of statistics
  - intro to JASP
- Week 2: Jan 24 (online)
  - read ???
  - online discussion board 
- Week 3: Jan 31 (face-to-face)
  - introduce Lab 1 assignment
  - writing effective intro and method sections 
- Week 4: Feb 7 (online)
  - collect Lab 1 data
  - read ???
  - online discussion board
- Week 5: Feb 14 (face-to-face)
  - Turn in Lab 1 data
  - data analysis techniques
  - writing effective results and discussion sections
- Week 6: Feb 21 (online)
  - work on Lab 1 manuscript
  - read ???
  - online discussion board
- Week 7: Feb 28 (face-to-face)
  - turn in Lab 1 manuscript
  - introduce Lab 2 assignment
- Week 8: Mar 7 (online)
  - collect Lab 2 data
  - read ???
  - online discussion board
- Week 9: Mar 21 (online)
  - continue collecting Lab 2 data
  - read ???
  - online discussion board
- Week 10: Mar 28 (face-to-face)
  - turn in Lab 2 data
  - data analysis techniques
- Week 11: Apr 4 (online)
  - work on Lab 2 manuscrip
  - read ???
  - online discussion board
- Week 12: Apr 11 (face-to-face)
  - Turn in Lab 2 manuscript
  - how to complete IRB protocols
- Week 13: Apr 18 (online)
  - work on IRB protocol
- Week 14: Apr 25 (face-to-face)
  - turn in IRB protocol
  - introduce Lab 3 assignment
- Week 15: May 2 (online)
  - work on IRB reviews
  - work on Lab 3 manuscript
- Week 16: May 9 (face-to-face)
  - turn in IRB reviews
  - turn in Lab 3 manuscript
