#+TITLE: HNRS 3385 - Honors Seminar
#+AUTHOR: 
#+DATE: Fall 2024
#+OPTIONS: toc:nil
#+OPTIONS: num:nil
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [10pt]
#+LATEX_HEADER: \usepackage[left=1in,right=1in,bottom=1in,top=1in]{geometry}
#+LATEX_HEADER: \setlength{\parindent}{0pt}
#+LATEX_HEADER: \setlength{\parskip}{2mm}

** Contact info
- Professor: Thomas J. Faulkenberry, Ph.D
- Office: Admin Annex II, Room 105L
- Office hours: /tba/
- Email: faulkenberry@tarleton.edu
- Website: [[http://tomfaulkenberry.github.io]]
- Phone: 254-968-9816
  
** Course description

The ultimate goal of this course is to produce a thesis proposal. We will achieve several intermediary steps along the way to this goal, including completing required trainings and forms, selecting a topic/committee chair/committee member, creating timelines and outlines, and producing drafts. It is important to note that each thesis looks different, and while fundamental similarities can be identified, each thesis process is also a personal one. My goal is for us to work collectively to identify the similarities and fundamental principles that are shared by research of all areas, while also working with each of you individually to craft /your/ project.

Students enrolling in this course are required to accepted into the Presidential Honors Program, or have permission granted from the Dean of the Honors College.

** Course materials

There is no required textbook for the course. I will provide readings and other resources as needed on Canvas.
  
** Student learning outcomes
   
Students who complete this course successfully will be able to:

1. Formulate research questions within their field of study.
2. Critically analyze publications within their field of study.
3. Design a thesis-level research project within their field.
4. Write a thesis proposal.
5. Defend a thesis proposal.


** Requirements and grading

Grades will be assigned based on the percentage of points you accumulate from the following activities:

- First proposal draft = 20 points
- Final proposal draft = 20 points
- Other assignments = 60 points
- /Total points possible = 100 points/

The category "Other assignments" will include various assignments such as online research training, documentation, timelines, topic summaries, outlines, etc.  These will be explained more as we move through the semester. I will use the standard grading scale of A=90%, B=80%, etc.

*** Grading Feedback Expectations

For assignments submitted on time, you can expect to receive grades and feedback within one week of the due date.

*** Graded Class Participation

Class participation is not graded. However, the structure of the course is such that failure to participate is likely to result in poor performance.

*** Graded Attendance 

All absences should be discussed with me, ideally prior to class. Failure to attend at least 80% of class meetings may result in a dropped letter grade (e.g., an “A” would become a “B”). More importantly, the nature of this course is such that absences will almost certainly be reflected in the quality of your proposal.

*** Late/Make-up Work Policy

Late work will not be accepted in this course, barring certain emergencies. If you experience an emergency that interferes with your ability to submit an assignment on time, please contact me as soon as possible.

*** Use of Artificial Intelligence (AI)

This course is designed to foster the requisite skills needed to comprehend, evaluate, and write about your unique thesis topic. The naïve use of AI tools like ChatGPT can interfere with the development of these skills and is therefore highly discouraged. They can be a good tool for early topic exploration, but any product that you develop in this course should be almost entirely written by you. With all AI tools, "trust but verify" (and edit heavily!).

** Course Communication

This course is designed to be an intensive, interactive course.  That means that I will be available for one-on-one consultation most any time.  Just stop by my office or give me a call.

All official course communication (questions, setting up a meeting, etc.) will be conducted by email.  Any time you need to contact me, feel free to send me an email at faulkenberry@tarleton.edu.  I only ask that you adhere to two guidelines:
  - please include the course number (HNRS 3385) in the subject line. 
  - please use proper email etiquette.  Include a salutation (e.g., Dear Dr. Faulkenberry), complete sentences, and a closing (e.g., "Regards, Your Name").  You might be surprised how many times I get an email from a nondescript email address with no indication from WHOM the email was sent!

Occasionally, I may send a class announcement via Canvas messaging. However, I ask that you send your questions by email instead of Canvas messaging.

** University Policy on "F" Grades
Beginning in Fall 2015, Tarleton will begin differentiating between a failed grade in a class because a student never attended (F0 grade), stopped attending at some point in the semester (FX grade), or because the student did not pass the course (F) but attended the entire semester. These grades will be noted on the official transcript. Stopping or never attending class can result in the student having to return aid monies received.  For more information see the Tarleton Financial Aid website.

** Academic Integrity Statement and Policy

Cheating, plagiarism, or doing work for another person who will receive academic credit is impermissible. This includes the use of unauthorized books, notebooks, or other sources in order to secure or give help during an examination, the unauthorized copying of examinations, assignments, reports, or term papers, or the presentation of unacknowledged material as if it were the own work. Disciplinary action may be taken beyond the academic discipline administered by the faculty member who teaches the course in which the cheating took place. Consult the following links for further information on academic conduct. 
- Student Judicial Affairs: https://www.tarleton.edu/judicial/academicconduct.html  
- Student Handbook: https://www.tarleton.edu/studentrules/code-of-student-conduct.html  

** Americans with Disabilities Act (ADA) - Student Success

Tarleton State University is committed to complying with the Americans with Disabilities Act (www.ada.gov) and other applicable laws. If you are a student with a disability seeking accommodation for this course, please contact the Office of Student Accessibility Services at 254.968.9650, studentaccessibilityservices@tarleton.edu,  or visit https://www.tarleton.edu/sas/ 

** Academic Affairs Core Values in the Classroom

*** Academic Integrity
Tarleton State University's core values are integrity, leadership, tradition, civility, excellence, and service.  Central to these values is integrity, which is maintaining a high standard of personal and scholarly conduct.  Academic integrity represents the choice to uphold ethical responsibility for one’s learning within the academic community, regardless of audience or situation.

*** Academic Civility
Students are expected to interact with professors and peers in a respectful manner that enhances the learning environment. Professors may require a student who deviates from this expectation to leave the face-to-face (or virtual) classroom learning environment for that particular class session (and potentially subsequent class sessions) for a specific amount of time. In addition, the professor might consider the university disciplinary process (for Academic Affairs/Student Life) for egregious or continued disruptive behavior.

*** Academic Excellence
Tarleton holds high expectations for students to assume responsibility for their own individual learning. Students are also expected to achieve academic excellence by:
- honoring Tarleton’s core values, upholding high standards of habit and behavior.
- maintaining excellence through class attendance and punctuality, preparing for active participation in all learning experiences. 
- putting forth their best individual effort.
- continually improving as independent learners.
- engaging in extracurricular opportunities that encourage personal and academic growth.
- reflecting critically upon feedback and applying these lessons to meet future challenges.

*** Student Rules

Students are responsible for knowing and abiding by the policies and information contained in the Tarleton Student Rules - https://www.tarleton.edu/studentrules.  


 
*Note:  any changes to this syllabus will be communicated to you by the instructor!*
 
** Tentative schedule

| Week | Date         | Potential topics covered                       |
|------+--------------+------------------------------------------------|
|    1 | August 28    | What is an honors thesis?                      |
|    2 | September 4  | Elements and structure of a good honors thesis |
|    3 | September 11 | Choosing a thesis topic and committee          |
|    4 | September 18 | Trainings and required documentation           |
|    5 | September 25 | The thesis process and various approaches      |
|    6 | October 2    | Creating a timeline and managing expectations  |
|    7 | October 9    | Reading and writing like a scholar             |
|    8 | October 16   | Tools for reading and writing                  |
|    9 | October 23   | No class -- continue reading and writing       |
|   10 | October 30   | In class writing group / progress check in     |
|   11 | November 6   | Tips and tricks for editing                    |
|   12 | November 13  | The defense -- what and why?                   |
|   13 | November 20  | No class -- continue writing                   |
|   14 | November 27  | No class -- Thanksgiving holiday               |
|   15 | December 4   | Tips for a successful defense                  |
|   16 | December 11  | Final proposal draft due!                      |
