#+TITLE: PSYC 5301: Research Methods
#+AUTHOR: 
#+DATE: Spring 2018
#+OPTIONS: toc:nil
#+OPTIONS: num:nil
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [10pt]
#+LATEX_HEADER: \usepackage[left=1in,right=1in,bottom=1in,top=1in]{geometry}

** Contact info
- Professor: Thomas J. Faulkenberry, Ph.D
- Office: Math 319
- Office hours: MWF 1-3 pm, TR 9-11 am
- Email: faulkenberry@tarleton.edu
- Website: [[http://tomfaulkenberry.github.io]]
- Phone: 254-968-9816

** Course description

This course is designed to provide the student with a solid grounding in the techniques of experimentation and subsequent statistical modeling that form the empirical basis of modern psychological science.  In addition, we will discuss much of the /philosophical/ underpinning of modern scientific inference.  We will accomplish this through lectures, textbook reading, discussions, and several hands-on "laboratory" experiences, each designed to give the student a taste of the research process, including data collection, analysis, and reporting. All students enrolled in this course are required to have *previously taken* PSYC 5300 (Behavioral Statistics) or have equivalent statistical background.  Note that we will meet face-to-face approximately once every two weeks (see schedule below). 

** Course materials

- /Understanding Psychology as a Science: An Introduction to Scientific and Statistical Inference/ by Zoltan Dienes [[https://www.amazon.com/Understanding-Psychology-Science-Introduction-Statistical/dp/023054231X][Amazon link]]
- /APA Publication Manual/ (6th ed.) [[http://www.amazon.com/Publication-Manual-American-Psychological-Association/dp/1433805618/][Amazon link]]
- OpenSesame experiment building software (free download from [[http://osdoc.cogsci.nl/3.1/download/][osdoc.cogsci.nl]].  Make sure your version is at least 3.1.9.
- JASP statistical software (free download from [[http://jasp-stats.org][jasp-stats.org]]).  Make sure your version is at least 0.8.

** Student learning outcomes

1. Understand the classical frameworks of inference in psychological research
2. Develop research questions and translate those to testable hypotheses
3. Collect data using a variety of standard research paradigms
4. Analyze data using computer software
5. Communicate research results as a complete APA style manuscript
6. Develop a research prospectus

** Requirements and grading
- Online quizzes (50 points)
- Labs (100 points)
- Online discussions (100 points)
- Research prospectus (100 points)
- Class participation (50 points)
- /Total = 400 points/

Grades will be assigned based on the percentage of points you accumulate 
out of these 400 points.  I will use the standard grading scale of A=90%, 
B=80%, etc.

*** Online quizzes (12.5% of grade)
As this is a graduate level research methods course, there is some certain prerequisite knowledge that I expect you to have. However, it is possible that certain things may have been forgotten (or never studied) from your undergraduate studies. To help you get up to speed with this basic prerequisite knowledge, I have designed a set of 5 online quizzes that cover this basic content.  There are also lecture videos that accompany these quizzes.  You may progress through the quizzes at your own pace, so long as they are all completed by midterm.  They are also progressive; you must obtain a grade of at least 8/10 to gain access to the next quiz.  You may retake the quizzes as many times as necessary; just be aware that the recorded grade is the /last/ one you take.

*** Labs (25% of grade)
There will be two lab assignments this semester.  The purpose of these assignments is to familiarize you with the complete research process, from collecting data to analyzing the data and writing up the resulting manuscript. The labs will involve the basic designs used in much of the psychological literature, including independent groups designs, repeated measures designs, and factorial designs.  Each lab is worth 50 points (10 points for the data you collect and 40 points for the resulting manuscript). 

*** Online discussions (25% of grade)
Every online week (i.e., weeks we are not meeting in Stephenville; see below), you will be assigned a reading from the textbook and/or other external papers.  To ensure sufficient understanding of the readings, you will participate in an online discussion.  These discussions will revolve around a small number of prompts, to which you will be required to (1) compose your response, and (2) respond to your classmates.  The grades will be assigned largely on a /completion/ basis, but substantive responses are required.  You /cannot/ simply respond "I agree" or "I disagree"...you must substantiate your response(s) with data and/or a logical argument. 

*** Research prospectus (25% of grade)
In order to complete the research component of your MS degree, you will have to complete a thesis or applied project.  To help you in your planning for this work next year, you will complete a /research prospectus/ in this course.  The prospectus (also called a /concept paper/) will describe a research study that you could potentially propose to carry out as your thesis or applied project.  The prospectus will roughly consist of the first three sections of a standard research manuscript: an /introduction/ where you introduce a question for research and review the past research that sets up the question; a /method/ section, where you describe the methods you will use to answer the question; and a /results/ section, where you discuss how you will analyze the results of your study.  The study you propose must be /quantitative/ and use methods that reflect the scientific nature of our discipline. 

*** Class participation (12.5% of grade)
This is a very active course.  It is essential that you participate in /all/ activities, both online and in our face-to-face sessions.  Your class participation grade will be reflective of the effort that I've seen you put into the course. Most people will earn all 50 possible points, but I reserve the right to lower this grade if you miss excessive class meetings. 

Please note that we will meet /in Stephenville/ on the following dates:
  - Jan 16
  - Jan 30
  - Feb 13
  - Feb 27
  - Mar 27
  - Apr 10
  - Apr 24
  - May 8


** Course Communication

Email is the primary means of official communication for this course.  If you have questions about the course, always feel free to send me an email at faulkenberry@tarleton.edu.  I only ask that you adhere to two guidelines:
  - please include the course number (PSYC 5301) in the subject line.  For example, one good way to do this is:  Subject: [PSYC 5301] Question about Lab 2
  - please use proper email etiquette.  Include a salutation (e.g., Dear Dr. Faulkenberry), complete sentences, and a closing (e.g., "Regards, Your Name").  You might be surprised how many times I get an email from a nondescript email address with no indication from WHOM the email was sent!

Also, I will send periodic class announcements via email.  Thus, it is imperative that you check your /Tarleton email address/ regularly so that you don't miss any of these messages.

** University Policy on "F" Grades

Beginning in Fall 2015, Tarleton began differentiating between a failed grade in a class because a student never attended (F0 grade), stopped attending at some point in the semester (FX grade), or because the student did not pass the course (F) but attended the entire semester. These grades will be noted on the official transcript. Stopping or never attending class can result in the student having to return aid monies received.  For more information see the Tarleton Financial Aid website.

** Academic Honesty

Cheating, plagiarism (submitting another person’s materials or ideas as one’s own without proper attribution), or doing work for another person who will receive academic credit are all disallowed. This includes the use of unauthorized books, notebooks, or other sources in order to secure of give help during an examination, the unauthorized copying of examinations, assignments, reports, or term papers, or the presentation of unacknowledged material as if it were the student’s own work. Disciplinary action may be taken beyond the academic discipline administered by the faculty member who teaches the course in which the cheating took place.

In particular, any quiz or exam taken online must be completed without the aid of any unauthorized resource (including using any search engine, Google, etc.).  Authorized resources are limited only to the official textbook and any lecture notes from the course.  Any other authorized resources will be provided to you before the exam.  

The minimum sanction for /any/ act of academic dishonesty is a grade of 0 on the affected assignment; a grade of F for the course may be assigned in severe cases.

** Academic Affairs Core Value Statements
*** Academic Integrity Statement
Tarleton State University's core values are integrity, leadership, tradition, civility, excellence, and service.  Central to these values is integrity, which is maintaining a high standard of personal and scholarly conduct.  Academic integrity represents the choice to uphold ethical responsibility for one’s learning within the academic community, regardless of audience or situation.

*** Academic Civility Statement 
Students are expected to interact with professors and peers in a respectful manner that enhances the learning environment. Professors may require a student who deviates from this expectation to leave the face-to-face (or virtual) classroom learning environment for that particular class session (and potentially subsequent class sessions) for a specific amount of time. In addition, the professor might consider the university disciplinary process (for Academic Affairs/Student Life) for egregious or continued disruptive behavior.

*** Academic Excellence Statement
Tarleton holds high expectations for students to assume responsibility for their own individual learning. Students are also expected to achieve academic excellence by:
- honoring Tarleton’s core values, upholding high standards of habit and behavior.
- maintaining excellence through class attendance and punctuality, preparing for active participation in all learning experiences. 
- putting forth their best individual effort.
- continually improving as independent learners.
- engaging in extracurricular opportunities that encourage personal and academic growth.
- reflecting critically upon feedback and applying these lessons to meet future challenges.

** Students with Disabilities Policy

It is the policy of Tarleton State University to comply with the Americans with Disabilities Act and other applicable laws. If you are a student with a disability seeking accommodations for this course, please contact the Center for Access and Academic Testing, at 254.968.9400 or caat@tarleton.edu. The office is located in Math 201. More information can be found at www.tarleton.edu/caat or in the University Catalog.

**Note:  any changes to this syllabus will be communicated to you by the instructor!**
 
