#+TITLE: PSYC 2317: Statistical Methods for Psychology
#+AUTHOR: 
#+DATE: Fall 2023
#+OPTIONS: toc:nil
#+OPTIONS: num:nil
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [10pt]
#+LATEX_HEADER: \usepackage[left=1in,right=1in,bottom=1in,top=1in]{geometry}

** Contact info
- Professor: Thomas J. Faulkenberry, Ph.D
- Office: Math 301
- Office hours: /TBA/
- Email: faulkenberry@tarleton.edu
- Website: [[http://tomfaulkenberry.github.io]]
- Phone: 254-968-9816

** Course description

Statistical methods are the primary tool for research in psychology. They are what allow us as researchers to make consistent, data-driven decisions.  As such, this is an extremely important course and one that I take very seriously as your professor. The topics we will cover this semester will include descriptive statistics (how we describe data) and inferential statistics (how we make decisions about data).  Specifically, this includes central tendency, variability, the distinction between populations and samples, parameter estimation, and hypothesis testing (both classical and Bayesian).

** Course materials
- Primary textbook: Faulkenberry, T. J. (2022). /Psychological Statistics: The Basics/, published by Routledge. A link to purchase on Amazon is [[https://www.amazon.com/Psychological-Statistics-Basics-Thomas-Faulkenberry/dp/1032020954/][here]]
  - Note - this is a reasonably short and inexpensive book, and can usually be had for around $25. The small commission I make on book sales goes back to support the development and maintenance of the free web-based software tools that we use during the semester. Trust me, I am not "profiting" from book sales. If it feels weird that I am requiring you to buy my book, I understand. However, I hope you'll also realize the value of being taught by the same person who wrote your book!

- Optional reference book: For reference, I recommend our book /Learning Statistics with JASP: A Tutorial for Psychology Students and Other Beginners/ by Navarro, Foxcroft, and Faulkenberry (2019), which is a textbook that can be downloaded (for free!) from [[http://learnstatswithjasp.com][www.learnstatswithjasp.com]].

- Online statistical calculator: throughout the semester, we will use the /PsyStat/ calculator developed over the past few years by me and my former student Keelyn Brennan (now a Ph.D. student at the University of Oklahoma). The calculator can be accessed (for free!) on any computer or mobile device at https://tomfaulkenberry.shinyapps.io/psystat
   
- Statistical software: Later in the course, we will also learn to use the JASP statistical software package; this can be downloaded (you guessed it -- for free!) from [[http://www.jasp-stats.com][www.jasp-stats.com]]

** Student learning outcomes
1. Identify variables under study (including independent and dependent variables)
2. Choose appropriate measures of descriptive statistics
3. Select and perform appropriate inferential statistics
4. Draw appropriate statistical conclusions from results of analyses

** Course format

This course will be delivered in an online format. The basic structure of each week is as follows:

- early in the week, you will watch an introductory video lecture (given by me) explaining the week's topic and take a short quiz to assess your understanding. This quiz will always be due on Tuesday night at 11:59 pm. Quizzes will be multiple choice and will be graded automatically.

- after you finish the introductory video lecture and quiz, you will then be ready to work the week's homework set. To assist with this work, I will publish a video that shows me working and talking through the solutions to a set of practice problems similar to those you'll be working on in the homework set.

- after you watch the practice video, you'll be ready to finish up the week's homework set. These homework sets will always be due on Sunday night at 11:59 pm. Homeworks will be graded during the following week. Note, the labor required to grade homework problems is not insignificant, so I ask that you give me a week to get these grades and feedback posted. Rarely should I ever need to take longer than a week to get things graded.

- three times during the semester, we will pause the typical weekly schedule and have an exam.

More details on the quizzes, homework, and exams are given below.

** Requirements and grading
- Exam 1 (100 pts)
- Exam 2 (100 pts)
- Exam 3 (100 pts)
- Weekly quizzes (100 pts)
- Homework exercises (100 pts)
- /Total = 500 points/

Grades will be assigned based on the percentage of points you accumulate out of these 500 points.  I will use the standard grading scale of A=90%, B=80%, etc.

*** Exams
There will be three exams throughout the semester, occurring approximately once every four to five weeks.  They will cover material from lectures, quizzes, and homework exercises. Exams will be similar in format to homework sets, primarily consisting of short-answer questions. Exams (and homework; see below) will be submitted online on Canvas -- in my experience, it is probably easiest to hand-write your solutions neatly on clean paper and either scan or take a photo of the completed work to submit. Exams may not be done collaboratively; these should be considered as honest assessments of /your/ learning, and as such, should be done independently.

Tentative exam dates:

- Exam 1 (due Sunday, October 1 at 11:59 pm)
- Exam 2 (due Sunday, November 12 at 11:59 pm)
- Exam 3 (due Sunday, December 10 at 11:59 pm)
  
*** Weekly quizzes 

At the beginning of each non-exam week, you will watch a video posted on Canvas where I introduce the week's concepts. After watching this video, you will complete an online multiple-choice quiz, the aim of which is to check for understanding of the concepts presented. Each quiz counts for 10 possible points. There will 10 of these quizzes, and these quiz scores will earn you up to 100 points for your overall quiz grade.

*** Homework exercises 
In order to practice the statistical concepts you learn this semester, you will complete a short homework assignment every week. A set of homework exercises (usually around 4-5 problems) will be provided to you each week. You may work collaboratively on the homework exercises, but any work submitted must reflect your own understanding of the material (in other words, don't just copy someone else's work to submit). /Please note that all work must be shown on computational problems in order to receive full credit./ Each homework assignment will be due at 11:59 pm on Sunday of the week it was assigned. Homework must be submitted in PDF or DOCX format via the assigment link on Canvas; assignments sent by email or as attachments in submission comments will not be accepted.

** Course Communication

Email is the primary means of official communication for this course. If you have questions about the course, always feel free to send me an email at faulkenberry@tarleton.edu.  I only ask that you adhere to two guidelines:
  - please include the course number (PSYC 2317) in the subject line.  For example, one good way to do this is:  Subject: [PSYC 2317] Question about Exam 2
  - please use proper email etiquette.  Include a salutation (e.g., Dear Dr. Faulkenberry), complete sentences, and a closing (e.g., "Regards, Your Name").  You might be surprised how many times I get an email from a nondescript email address with no indication from WHOM the email was sent!

Note, I will send periodic class announcements via Canvas messaging. However, I ask that you send your questions by email instead of Canvas messaging. 

** Academic Integrity Statement and Policy

Cheating, plagiarism, or doing work for another person who will receive academic credit is impermissible. This includes the use of unauthorized books, notebooks, or other sources in order to secure or give help during an examination, the unauthorized copying of examinations, assignments, reports, or term papers, or the presentation of unacknowledged material as if it were the own work. Disciplinary action may be taken beyond the academic discipline administered by the faculty member who teaches the course in which the cheating took place. Consult the following links for further information on academic conduct. 
  - Student Judicial Affairs: https://www.tarleton.edu/judicial/academicconduct.html  
  - Student Handbook: https://www.tarleton.edu/studentrules/code-of-student-conduct.html  

** Americans with Disabilities Act (ADA) - Student Success

Tarleton State University is committed to complying with the Americans with Disabilities Act (www.ada.gov) and other applicable laws. If you are a student with a disability seeking accommodation for this course, please contact the Office of Disability Resources at 254.968.9400, disability@tarleton.edu, or visit https://www.tarleton.edu/drt/.  

** Academic Affairs Core Values in the Classroom

*** Academic Integrity
Tarleton State University's core values are integrity, excellence, and respect. Central to these values is integrity, which is maintaining a high standard of personal and scholarly conduct. Academic integrity represents the choice to uphold ethical responsibility for one’s learning within the academic community, regardless of audience or situation.

*** Academic Excellence
Tarleton holds high expectations for students to assume responsibility for their own individual learning.  Students are also expected to achieve academic excellence by:
  - honoring Tarleton’s core values. 
  - upholding high standards of habit and behavior. 
  - maintaining excellence through class attendance and punctuality. 
  - preparing for active participation in all learning experiences. 
  - putting forth their best individual effort. 
  - continually improving as independent learners. 
  - engaging in extracurricular opportunities that encourage personal and academic growth. 
  - reflecting critically upon feedback and applying these lessons to meet future challenges.

*** Academic Respect
Students are expected to interact with professors and peers in a respectful manner that enhances the learning environment. Professors may require a student who deviates from this expectation to leave the face-to-face (or virtual) classroom learning environment for that particular class session (and potentially subsequent class sessions) for a specific amount of time. In addition, the professor might consider the university disciplinary process (for Academic Affairs/Student Life) for egregious or continued disruptive behavior.


*** Student Rules
Students are responsible for knowing and abiding by the policies and information contained in the Tarleton Student Rules - https://www.tarleton.edu/studentrules.  

*Note:  any changes to this syllabus will be communicated to you by the instructor!*

** Semester Schedule

| Week beginning | Topic                                                 |
|----------------+-------------------------------------------------------|
| Aug 28         | Unit 1 - Measures of central tendency and variability |
| Sep 4          | Unit 2 - Transformations of scores / standardization  |
| Sep 11         | Unit 3 - The normal distribution                      |
| Sep 18         | Unit 4 - Distributions of sample means                |
| Sep 25         | *Exam 1* due Sunday, 10/1, at 11:59 pm                |
| Oct 2          | Unit 5 - Estimation and hypothesis testing            |
| Oct 9          | Unit 6 - Introduction to the \( t \)-test             |
| Oct 16         | Unit 7 - \( t \)-tests for independent samples        |
| Oct 23         | Unit 8 - Confidence intervals for \( t \)-tests       |
| Oct 30         | *Exam 2* due Sunday, 11/12, at 11:59 pm               |
| Nov 13         | Unit 9 - JASP / analysis of variance                  |
| Nov 20         | /no class due to Thanksgiving/                        |
| Nov 27         | Unit 10 - Bayesian hypothesis testing                 |
| Dec 4          | *Exam 3* due Sunday, 12/10, at 11:59 pm               |


