#+TITLE: Week 5 lecture notes - PSYC 5301
#+AUTHOR:
#+DATE: Feb 14, 2017 
#+OPTIONS: toc:nil num:nil

* Review of Question 3 from Week 2 

First, let's define some new (fancy) notation:  $X \sim \mathcal{N}(\mu,\sigma)$ means that $X$ is normally distributed with mean $\mu$ and standard deviation $\sigma$.

Let $X$ be defined as the distribution of IQ scores after some "brain training" program.  Recall that $X \sim \mathcal{N}(100,15)$.

We want to test whether the brain training program had a significant effect on the IQ scores.  So, we will define the following two hypotheses:
- H0: $\mu=100$
- H1: $\mu \neq 100$

Now, let's consider our three discussion questions:

1. suppose H0 true -- how many sig results from 100 replications?
  - 5 said "0 sig results"
  - 2 said "5 or fewer"
  - 1 said "5%"
  - 2 did not specify a clear answer

2. suppose H0 false, with 50% power -- how many sig results from 100 replications?
  - 6 said "50"
  - 3 said "50%"
  - 1 said "45-55%"

3. suppose 80% power, H0 and H1 equally likely -- which is more likely to be found: sig or nonsig?
  - 2 said "sig result"
  - 1 said "nonsig result"
  - 1 said "false result" (what does this mean?)
  - 2 said "50/50"
  - 4 did not specify a clear answer

Answers (using definitions and mathematical reasoning...note that we will also sdo some simulations in R to verify our reasoning):

1. correct answer is 5.  This is because the Type 1 error rate ($\alpha$) is 5%.  So, we should expect to reject a true null hypothesis (Type I error) 5% of the time.  Out of 100 trials, this is 5 "significant" results.

2. correct answer is 50.  This is because power is 50%, so probability of correctly rejecting false H0 is 50%.  So, out of 100 trials, we should expect 50 "significant" results.

3. correct answer is that a "nonsignificant" result is more likely to occur.  This might be a bit counterintuitive.  Suppose that we replicate the experiment 1000 times (let's call these replications "trials").  Then H0 is true on 500 trials, and H0 is false on 500 trials.  Now, based on our values for power (80%) and $\alpha$ (5%), we can complete the following table:

| decision  | HO true    | H0 false   |
|-----------+------------+------------|
| reject H0 | 25 trials  | 400 trials |
| accept H0 | 475 trials | 100 trials |

From this, we see that we reject H0 (a "significant" result) on 425 trials (42.5%), whereas we accept H0 (a "nonsignificant" result) on 575 trials (57.5%).  Thus, finding a nonsignificant result is quite more likely than a sig result!

  - note: this may seem depressing, but consider the following.  Our supposition was that H0 and H1 were "equally likely"...in other words, we had no prior evidence in favor of either hypothesis.  In "real" research situations, past evidence tends to point in favor of one hypothesis over the other.  So, if you start with H0 and H1 being weighted differently, the outcome of this problem will be vastly different.
* Data analysis -- independent samples $t$-test
** Review
** How to structure data
** Performing analysis in JASP
* Assignment

Assignment for next meeting (Feb 14)
1. You will need to put together a brief literature review (2-3 manuscript pages).  Do some background reading and find some papers that will help you address the following:
   - What is meant by the "levels of processing" (LOP) framework?  Craik and Lockhart (1972) will be a good reference here.
   - Find at least three papers that use the LOP paradigm in different applied contexts (e.g., LOP effects on memory for chess positions).  The only requirement is that the papers (1) use LOP manipulation, and (2) are interesting to you.  Devote a paragraph to each of these papers, explaining what the authors did and what they found.
   - Briefly describe the experiment we are conducting.  Be sure to describe the manipulation, and lay out some conceptual predictions.

2. You will need to write a very specific method section.  Specifically, you will need the following sections:
  - Participants: wait until after we've collected data to complete this.
  - Materials: describe the word list and how these words are formatted for display to participants.
  - Design: explain the design of the experiment (independent groups design? repeated measures design?)  Give operational definitions of each variable (both independent variables as well as any dependent variables).
  - Procedure: describe the steps each participant experiences during the experiment.

3. Collect data!  Details are given on the lab assignment sheet.
