#+TITLE: Week 3 lecture notes - PSYC 5301
#+AUTHOR:
#+DATE: Jan 31, 2017 
#+OPTIONS: toc:nil num:nil

* Review of Question 3 from Week 2 
1. suppose H0 true -- how many sig results from 100 replications?
  - 5 said "0 sig results"
  - 2 said "5 or fewer"
  - 1 said "5%"
  - 2 did not specify a clear answer

2. suppose H1 false, with 50% power -- how many sig results from 100 replications?
  - 6 said "50"
  - 3 said "50%"
  - 1 said "45-55%"

3. suppose 80% power, H0 and H1 equally likely -- which is more likely to be found: sig or nonsig?
  - 2 said "sig result"
  - 1 said "nonsig result"
  - 1 said "false result" (what does this mean?)
  - 2 said "50/50"
  - 4 did not specify a clear answer

Answers:

1. correct answer is 5.  This is because the Type 1 error rate ($\alpha$) is 5%.  So, we should expect to reject a true null hypothesis (Type I error) 5% of the time.  Out of 100 trials, this is 5 "significant" results.

2. correct answer is 50.  This is because power is 50%, so probability of correctly rejecting false H0 is 50%.  So, out of 100 trials, we should expect 50 "significant" results.

3. correct answer is that a "nonsignificant" result is more likely to occur.  This might be a bit counterintuitive.  Suppose that we replicate the experiment 1000 times (let's call these replications "trials").  Then H0 is true on 500 trials, and H0 is false on 500 trials.  Now, based on our values for power (80%) and $\alpha$ (5%), we can complete the following table:

| decision  | HO true    | H0 false   |
|-----------+------------+------------|
| reject H0 | 25 trials  | 400 trials |
| accept H0 | 475 trials | 100 trials |

From this, we see that we reject H0 (a "significant" result) on 425 trials (42.5%), whereas we accept H0 (a "nonsignificant" result) on 575 trials (57.5%).  Thus, finding a nonsignificant result is quite more likely than a sig result!

  - note: this may seem depressing, but consider the following.  Our supposition was that H0 and H1 were "equally likely"...in other words, we had no prior evidence in favor of either hypothesis.  In "real" research situations, past evidence tends to point in favor of one hypothesis over the other.  So, if you start with H0 and H1 being weighted differently, the outcome of this problem will be vastly different.
* Review of APA style
** Goals of research paper
- report the research
- explain methods (for further tests/replications)
- convince others
- needs standardization of format (APA style)

** Why APA style?
- eases communication
- forces minimal amount of information
- provides logical framework for argument
- consistent format within a discipline
  - readers know what to expect
  - where to find information in article

** Goals of APA-style writing
- write with clarity
- avoid overstatements (use "hedging" language)
- avoid jargon, slang, bias
- be concise
  - say the most information in the fewest words
  - longer =/= better

** Structure of an APA document
- Title page - title, authors, affiliations
- Abstract - short summary of article
  - this is the first thing most people read, so very important!
- Introduction - gives background that reader needs. 
  - written for broader audience
  - Recipe:
    1. state the issue under current study
    2. review past literature
    3. states purpose of current study
    4. predictions
- Method - tells reader what you did
  - very detailed
  - Recipe:
    1. Participants - who were data collected from?
    2. Materials - what was used to collect data?
    3. Design - describe what/how variables were manipulated
    4. Procedure - what did each participant do?
- Results - tells reader what you found
  - very detailed
  - reports results of statistical tests
- Discussion - tells reader *your* interpretation of results
  - relationship between purpose and results
  - emphasize theoretical contribution
  - broader implications
  - future directions
- The rest
  - references
  - tables
  - figures

* Lab 1 assignment

Assignment for next meeting (Feb 14)
1. You will need to put together a brief literature review (2-3 manuscript pages).  Do some background reading and find some papers that will help you address the following:
   - What is meant by the "levels of processing" (LOP) framework?  Craik and Lockhart (1972) will be a good reference here.
   - Find at least three papers that use the LOP paradigm in different applied contexts (e.g., LOP effects on memory for chess positions).  The only requirement is that the papers (1) use LOP manipulation, and (2) are interesting to you.  Devote a paragraph to each of these papers, explaining what the authors did and what they found.
   - Briefly describe the experiment we are conducting.  Be sure to describe the manipulation, and lay out some conceptual predictions.

2. You will need to write a very specific method section.  Specifically, you will need the following sections:
  - Participants: wait until after we've collected data to complete this.
  - Materials: describe the word list and how these words are formatted for display to participants.
  - Design: explain the design of the experiment (independent groups design? repeated measures design?)  Give operational definitions of each variable (both independent variables as well as any dependent variables).
  - Procedure: describe the steps each participant experiences during the experiment.

3. Collect data!  Details are given on the lab assignment sheet.
