#+TITLE: PSYC 3435: Principles of Research for the Behavioral Sciences
#+AUTHOR: 
#+DATE: Spring 2019
#+OPTIONS: toc:nil
#+OPTIONS: num:nil
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [10pt]
#+LATEX_HEADER: \usepackage[left=1in,right=1in,bottom=1in,top=1in]{geometry}

** Contact info
- Professor: Thomas J. Faulkenberry, Ph.D
- Office: Math 319
- Office hours: MWF 1-3 pm, TR 9-11 am
- Email: faulkenberry@tarleton.edu
- Website: [[http://tomfaulkenberry.github.io]]
- Phone: 254-968-9816

** Course description

This laboratory course is designed to introduce students to the philosophy of scientific inquiry with an emphasis on experimental methodology. This will be accomplished via a combination of traditional lectures along with an application of principles through laboratory experimentation and demonstration. Essentially, we will cover the "nuts and bolts" of putting together and completing a research project in psychology. To this end, we will cover all fourteen chapters of the textbook. All students enrolled in this course are required to have *previously taken* PSYC 3309 (Writing in Psychology) and PSYC 3330 (Statistics). 

** Course materials

- /The Process of Research in Psychology/ (3rd ed.) by McBride (2015) [[https://www.amazon.com/Process-Research-Psychology-Dawn-McBride/dp/1483347605/][Amazon link]]
- /APA Publication Manual/ (6th ed.) [[http://www.amazon.com/Publication-Manual-American-Psychological-Association/dp/1433805618/][Amazon link]]
- JASP statistical software (free download from [[http://jasp-stats.org][jasp-stats.org]])

** Student learning outcomes

1. Describe advantages of the scientific method compared to other approaches
2. Identify various research designs and uses of each
3. Conduct library research
4. Paraphrase and cite material from primary sources 
5. Develop a research question and write hypotheses appropriate for it
6. Design and conduct a research project to test hypotheses
7. Analyze data collected from research using computer software
8. Communicate the findings of research as a complete APA style manuscript

** Requirements and grading

- Exam 1 (100 pts)
- Exam 2 (100 pts)
- Exam 3 (100 pts)
- Final exam (150 pts)
- Unit quizzes (100 pts)
- Lab assignments (100 pts)
- Research participation (50 pts)
- /Total = 700 points/

Grades will be assigned based on the percentage of points you accumulate out of these 700 points.  I will use the standard grading scale of A=90%, B=80%, etc.

*** Exams (64% of grade)
There will be four exams throughout the semester.  They will cover material from the text and the lectures.  Exam questions will be a mix of multiple choice and short answer and will be worth 100 points each.

Dates:

- Exam 1 (Wednesday, Feb 13)
- Exam 2 (Wednesday, March 27)
- Exam 3 (Wednesday, April 24)
- Final exam (Monday, May 6, 3:00-5:30 pm)

*** Unit quizzes (14% of grade)

Every Friday (excluding exam weeks), there will be a short in-class quiz over the material covered in lectures on Monday and Wednesday. Typically, the quizzes will consist of multiple choice questions, although the format may change occasionally depending on material.  Your final quiz average will be scaled to a total of 100 points for the semester (i.e., if you average 8.6/10 points over all quizzes, your final quiz grade will be 86/100).

*** Lab assignments (14% of grade)

There will be four lab assignments this semester.  Each assignment is designed to give you first hand experience with essential research skills, such as conducting an experiment, collecting data, and writing up an APA manuscript.  Except for Lab 1 (an APA exercise), each of you will administer a short experiment, collect some data, analyze the collected data for the class, and compose an APA manuscript based on the experiment and the results. 

Lab Assignments and dates

- Lab 1 – APA formatting (10 points), due Friday, Feb 8
- Lab 2.1 – Chi-squared design, data collection (10 points), due Friday, Feb 22
- Lab 2.2 – Chi-squared design, analysis and report (20 points), due Friday, Mar 8
- Lab 3.1 – Independent groups design, data collection (10 points), due Friday, Mar 22
- Lab 3.2 – Independent groups design, analysis and report (20 points), due Friday, Apr 5
- Lab 4.1 – Factorial design, data collection (10 points), due Friday, Apr 12
- Lab 4.2 – Factorial design, analysis and report (20 points), due Friday, Apr 26 

*** Research participation (8% of grade)

Research is the lifeblood of psychology!  In order to promote your growth as a psychological scientist, you will be required to participate in 2 "units" of research over the course of the semester.  Roughly defined, a "unit" of research consists of either (1) participation in one hour of psychological experiments, usually offered right here in the Psychology department at Tarleton, or (2) a 3-5 page critical reflection of an empirical research article related to human learning and/or cognition, usually chosen by me.  Instructions for participation will be given in class.

** Course Communication

Email is the primary means of communication for this course.  If you have questions about the course, always feel free to send me an email at faulkenberry@tarleton.edu.  I only ask that you adhere to two guidelines:
  - please include the course number (PSYC 3435) in the subject line.  For example, one good way to do this is:  Subject: [PSYC 3435] Question about Lab 2
  - please use proper email etiquette.  Include a salutation (e.g., Dear Dr. Faulkenberry), complete sentences, and a closing (e.g., "Regards, Your Name").  You might be surprised how many times I get an email from a nondescript email address with no indication from WHOM the email was sent!

Also, I will be sending periodic emails to each of you that update you on course progress, due dates, etc.  It is imperative that you check your /Tarleton email address/ regularly so that you don't miss any of these messages.

** University Policy on "F" Grades
Beginning in Fall 2015, Tarleton began differentiating between a failed grade in a class because a student never attended (F0 grade), stopped attending at some point in the semester (FX grade), or because the student did not pass the course (F) but attended the entire semester. These grades will be noted on the official transcript. Stopping or never attending class can result in the student having to return aid monies received.  For more information see the Tarleton Financial Aid website.

** Academic Honesty

Cheating, plagiarism (submitting another person’s materials or ideas as one’s own without proper attribution), or doing work for another person who will receive academic credit are all disallowed. This includes the use of unauthorized books, notebooks, or other sources in order to secure of give help during an examination, the unauthorized copying of examinations, assignments, reports, or term papers, or the presentation of unacknowledged material as if it were the student’s own work. Disciplinary action may be taken beyond the academic discipline administered by the faculty member who teaches the course in which the cheating took place.

The minimum sanction for /any/ act of academic dishonesty is a grade of 0 on the affected assignment; a grade of F for the course may be assigned in severe cases.

** Academic Affairs Core Value Statements

*** Academic Integrity Statement
Tarleton State University's core values are integrity, leadership, tradition, civility, excellence, and service.  Central to these values is integrity, which is maintaining a high standard of personal and scholarly conduct.  Academic integrity represents the choice to uphold ethical responsibility for one’s learning within the academic community, regardless of audience or situation.

*** Academic Civility Statement 
Students are expected to interact with professors and peers in a respectful manner that enhances the learning environment. Professors may require a student who deviates from this expectation to leave the face-to-face (or virtual) classroom learning environment for that particular class session (and potentially subsequent class sessions) for a specific amount of time. In addition, the professor might consider the university disciplinary process (for Academic Affairs/Student Life) for egregious or continued disruptive behavior.

*** Academic Excellence Statement
Tarleton holds high expectations for students to assume responsibility for their own individual learning. Students are also expected to achieve academic excellence by:
- honoring Tarleton’s core values, upholding high standards of habit and behavior.
- maintaining excellence through class attendance and punctuality, preparing for active participation in all learning experiences. 
- putting forth their best individual effort.
- continually improving as independent learners.
- engaging in extracurricular opportunities that encourage personal and academic growth.
- reflecting critically upon feedback and applying these lessons to meet future challenges.

** Students with Disabilities Policy

It is the policy of Tarleton State University to comply with the Americans with Disabilities  Act (www.ada.gov) and other applicable laws.  If you are a student with a disability seeking accommodations for this course, please contact the Center for Access and Academic Testing, at 254.968.9400 or caat@tarleton.edu. The office is located in Math 201. More information can be found at www.tarleton.edu/caat or in the University Catalog.​
 
*Note:  any changes to this syllabus will be communicated to you by the instructor!*
 
** Schedule of lectures
   
| Week | Dates        | Lecture topic                                                           |
|------+--------------+-------------------------------------------------------------------------|
|    1 | Jan 14-18    | Knowing in psychological science (Ch 1)                                 |
|    2 | Jan 21-25    | Reading the literature / APA style (Ch 2,8)                             |
|    3 | Jan 28-Feb 1 | Basic research methods (Ch 3)                                           |
|    4 | Feb 4-8      | Ethics in psychological science (Ch 5)                                  |
|    5 | Feb 11-15    | *Exam 1*                                                                |
|    6 | Feb 18-22    | Experiments: selecting and manipulating variables (Ch 4)                |
|    7 | Feb 25-Mar 1 | Experiments: sampling methods (Ch 6)                                    |
|    8 | Mar 4-8      | Experiments: basic designs (Ch 11)                                      |
|    - | Mar 11-15    | *Spring break!*                                                         |
|    9 | Mar 18-22    | Experiments: factorial designs (Ch 11)                                  |
|   10 | Mar 25-29    | *Exam 2*                                                                |
|   11 | Apr 1-5      | Non-experiments: correlations and regression (Ch 10)                    |
|   12 | Apr 8-12     | Non-experiments: quasi-experiments (Ch 12)                              |
|   13 | Apr 15-19    | Non-experiments: developmental designs (Ch 13)                          |
|   14 | Apr 22-26    | *Exam 3*                                                                |
|   15 | Apr 29-May 1 | Course review                                                           |
|   16 | May 6-10     | *Final exam: Monday, May 6, 3:00-5:30 pm*                              |

