#+TITLE: PSYC 5301: Research Methods
#+AUTHOR: 
#+DATE: Spring 2021
#+OPTIONS: toc:nil
#+OPTIONS: num:nil
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [10pt]
#+LATEX_HEADER: \usepackage[left=1in,right=1in,bottom=1in,top=1in]{geometry}

** Contact info
- Professor: Thomas J. Faulkenberry, Ph.D
- Office: Math 319
- Office hours: /to be announced/
- Email: faulkenberry@tarleton.edu
- Website: [[http://tomfaulkenberry.github.io]]
- Phone: 254-968-9816

** Course description

This course is a continuation of the study of statistics that you have already begun in your graduate studies. It is designed to provide you with a solid grounding in the theory and practice of experimental design and statistical modeling that form the empirical basis of modern psychological science. In addition, we will discuss some of the /philosophical/ underpinning of modern scientific inference and wade into the debate on frequentist versus Bayesian approaches to inference.  We will accomplish this through weekly lectures, quizzes, homework exercises, and periodic exams. All students enrolled in this course are required to have *previously taken* PSYC 5300 (Behavioral Statistics) or have equivalent statistical background.

** Course materials

- Textbook
  - there is no specific textbook for this course. I will provide you with detailed lecture notes and a variety of readings from primary sources (i.e., journal articles). All materials will be available on Canvas. If you need a review of basic statistics, I would recommend the free textbook /Learning Statistics with JASP/ by Navarro, Foxcroft, and Faulkenberry, which you can download from https://www.learnstatswithjasp.com.
- Software
  - we will regularly use JASP, which is a free software package for doing both conventional and Bayesian statistics. You can download it for free from https://jasp-stats.org (you must have a computer running MacOS, Windows, or Linux -- it does not work well on "thin client" systems such as Chromebooks or tablets).   
- Calculator
  - you should have a standalone calculator that is capable of performing the most basic scientific computations (exponents, square roots, logarithms, etc.). A graphing calculator is /not/ required, though I will be using one (TI-84) when I demonstrate calculations. Find a calculator you like using!

** Student learning outcomes

1. Understand the classical elements of inference in psychological research, including hypothesis testing and \(p\)-values.
2. Know the basic elements of experimental design (e.g., measurement, random assignment, etc.)
3. Understand the mechanics of classical analysis of variance in single-factor and two-factor designs
4. Know how to adapt inferential procedures for within-subjects designs and, more generally, designs with covariates
5. Understand the differences between frequentist and Bayesian approaches to hypothesis testing
6. Use appropriate software packages to perform both frequentist and Bayesian hypothesis tests for a variety of experimental designs

** Course format

This course will be delivered in a hybrid-flexible ("HyFlex") format, giving you the option of attending the course face-to-face and/or online. The basic structure of each week is as follows:

- early in the week, you will watch an online video lecture (given by me) explaining the week's topic and take a short quiz to assess your understanding.

- you can then attend our course meeting Tuesday night either /in-person/ or /virtually/ via Zoom. The purpose of this course meeting is for me to demonstrate examples of homework problems that are assigned for the given week and give you the opportunity to ask questions. 
Note that you are not /required/ to attend the class meetings at all! You may certainly wish to attend synchronously (i.e., either in-person or via Zoom), and I encourage all who can to do so. However, you may instead choose to simply watch the recorded problem sessions at a convenient time later in the week. All class recordings will be posted on Canvas.

It does not matter which mode of attendance you choose -- that is the point of our "Hybrid-Flexible" course format. And, you can change your mind each week. The only thing that is /required/ is that you complete the quizzes, homeworks, and exams, which I'll describe in the next section.
** Requirements and grading
- Exam 1 (100 points)
- Exam 2 (100 points)
- Exam 3 (100 points)
- Homework exercises (100 points)
- Weekly quizzes (100 points)
- /Total = 500 points/

Grades will be assigned based on the percentage of points you accumulate out of these 500 points.  I will use the standard grading scale of A=90%, B=80%, etc.

*** Exams (60% of grade)
There will be three exams throughout the semester, occurring approximately once every four to five weeks.  They will cover material from lectures, quizzes, and homework exercises. Exams will be "take-home", primarily consisting of short-answer questions. Exams (and homework; see below) will be submitted online on Canvas -- in my experience, it is probably easiest to hand-write your solutions neatly on clean paper and either scan or take a photo of the completed work to submit. 

Tentative exam dates:

- Exam 1 (due Sunday, February 21 at 11:59 pm)
- Exam 2 (due Sunday, April 4 at 11:59 pm)
- Exam 3 (due Sunday, May 2 at 11:59 pm)

*** Weekly quizzes (20% of grade)

At the beginning of each non-exam week, you will watch a video posted on Canvas where I introduce the week's concepts. After watching this video, you will complete an online multiple-choice quiz, the aim of which is to check for understanding of the concepts presented. Each quiz counts for 10 possible points. There will be at least 10 of these quizzes, so your 10 highest quiz scores will earn you up to 100 points for your overall quiz grade.

*** Homework exercises (20% of grade)
In order to practice the concepts you learn this semester, you will complete a short homework assignment every week. A set of homework exercises (usually around 4-5 problems) will be provided to you each week. You may work collaboratively on the homework exercises, but any work submitted must reflect your own understanding of the material (in other words, don't just copy someone else's work to submit).  Each homework assignment will be due at 11:59 pm on Sunday immediately following the week it was assigned.

** Course Communication

Email is the primary means of official communication for this course.  If you have questions about the course, always feel free to send me an email at faulkenberry@tarleton.edu.  I only ask that you adhere to two guidelines:
  - please include the course number (PSYC 5301) in the subject line.  For example, one good way to do this is:  Subject: [PSYC 5301] Question about HW 3
  - please use proper email etiquette.  Include a salutation (e.g., Dear Dr. Faulkenberry), complete sentences, and a closing (e.g., "Regards, Your Name").  You might be surprised how many times I get an email from a nondescript email address with no indication from WHOM the email was sent!

Also, I will send periodic class announcements via email.  Thus, it is imperative that you check your /Tarleton email address/ regularly so that you don't miss any of these messages.

** University Policy on "F" Grades

Beginning in Fall 2015, Tarleton began differentiating between a failed grade in a class because a student never attended (F0 grade), stopped attending at some point in the semester (FX grade), or because the student did not pass the course (F) but attended the entire semester. These grades will be noted on the official transcript. Stopping or never attending class can result in the student having to return aid monies received.  For more information see the Tarleton Financial Aid website.

** Academic Honesty

Cheating, plagiarism (submitting another person’s materials or ideas as one’s own without proper attribution), or doing work for another person who will receive academic credit are all disallowed. This includes the use of unauthorized books, notebooks, or other sources in order to secure of give help during an examination, the unauthorized copying of examinations, assignments, reports, or term papers, or the presentation of unacknowledged material as if it were the student’s own work. Disciplinary action may be taken beyond the academic discipline administered by the faculty member who teaches the course in which the cheating took place.

The minimum sanction for /any/ act of academic dishonesty is a grade of 0 on the affected assignment; a grade of F for the course may be assigned in severe cases.

** Academic Affairs Core Value Statements
*** Academic Integrity Statement
Tarleton State University's core values are integrity, leadership, tradition, civility, excellence, and service.  Central to these values is integrity, which is maintaining a high standard of personal and scholarly conduct.  Academic integrity represents the choice to uphold ethical responsibility for one’s learning within the academic community, regardless of audience or situation.

*** Academic Civility Statement 
Students are expected to interact with professors and peers in a respectful manner that enhances the learning environment. Professors may require a student who deviates from this expectation to leave the face-to-face (or virtual) classroom learning environment for that particular class session (and potentially subsequent class sessions) for a specific amount of time. In addition, the professor might consider the university disciplinary process (for Academic Affairs/Student Life) for egregious or continued disruptive behavior.

*** Academic Excellence Statement
Tarleton holds high expectations for students to assume responsibility for their own individual learning. Students are also expected to achieve academic excellence by:
- honoring Tarleton’s core values, upholding high standards of habit and behavior.
- maintaining excellence through class attendance and punctuality, preparing for active participation in all learning experiences. 
- putting forth their best individual effort.
- continually improving as independent learners.
- engaging in extracurricular opportunities that encourage personal and academic growth.
- reflecting critically upon feedback and applying these lessons to meet future challenges.

** Students with Disabilities Policy

It is the policy of Tarleton State University to comply with the Americans with Disabilities Act and other applicable laws. If you are a student with a disability seeking accommodations for this course, please contact the Center for Access and Academic Testing, at 254.968.9400 or caat@tarleton.edu. The office is located in Math 201. More information can be found at www.tarleton.edu/caat or in the University Catalog.

**Note:  any changes to this syllabus will be communicated to you by the instructor!**
 
** Schedule of class meetings

 | Week | Date   | Topic                                 |
 |------+--------+---------------------------------------|
 |    1 | Jan 19 | Introduction to the course            |
 |    2 | Jan 26 | Review of classical inference         |
 |    3 | Feb 2  | Introduction to Bayesian inference    |
 |    4 | Feb 9  | Single-factor designs                 |
 |    5 | Feb 16 | No class meeting - complete *Exam 1*  |
 |    6 | Feb 23 | Repeated-measures designs             |
 |    7 | Mar 2  | Two-factor designs                    |
 |    8 | Mar 9  | Covariate designs                     |
 |    9 | Mar 16 | /No class meeting -- Spring Break/    |
 |   10 | Mar 23 | Contrasts and comparisons among means |
 |   11 | Mar 30 | No class meeting - complete *Exam 2*  |
 |   12 | Apr 6  | Regression models                     |
 |   13 | Apr 13 | Classical model selection techniques  |
 |   14 | Apr 20 | Bayesian model selection              |
 |   15 | Apr 27 | No class meeting - complete *Exam 3*  |
 
