#+TITLE: Maximum Likelihood Estimation
#+AUTHOR: Week 2 - PSYC 5316
#+DATE: September 4, 2017 
#+OPTIONS: toc:nil num:nil
#+LaTeX_CLASS: beamer
#+LaTEX_HEADER: \setbeamertemplate{navigation symbols}{}

** Recall

Last time, we gave a formal definition for a *probability function*.  An example was the /binomial/ distribution for $N$ independent Bernoulli trials (e.g., coin flips):

\[
f(x\mid \theta) = {N\choose x} \theta^x(1-\theta)^{N-x}
\]

where $x$ = # of successes, and $\theta$ = probability of success.

** Probability function

Suppose $N=20$ and $\theta=0.7$.  

#+BEGIN_SRC
barplot(dbinom(0:20,size=20,prob=0.7),
        names.arg=0:20,
        ylab="p(x)",
        xlab="x")
#+END_SRC

file:figures/week2/binom.png

** Data and parameters

\[
f(x\mid \theta) = {N\choose x} \theta^x(1-\theta)^{N-x}
\]

\vspace{1cm}

This function gives us the probability of *data*, /given/ a specific *parameter*


** Data and parameters

What if we switched these?

\[
f(\theta \mid x) = {N\choose x} \theta^x(1-\theta)^{N-x}
\]

\vspace{1cm}

This function then gives us the likelihood of a range of *parameters*, /given/ a specific *data point*

** Likelihood function
Suppose we observed 12 successes in 20 trials:

#+BEGIN_SRC
theta=seq(from=0, to=1, by=0.01)
plot(theta, dbinom(x=12, size=20, prob=theta), 
     type="l",ylab="likelihood")
#+END_SRC

file:figures/week2/likelihood.png


** Likelihood function
Suppose we observed 12 successes in 20 trials:

\vspace{1cm}

Natural question -- what value of $\theta$ is *most likely*, given the data?

file:figures/week2/likelihood.png


** Likelihood function
Suppose we observed 12 successes in 20 trials:

\vspace{1cm}

Natural question -- what value of $\theta$ is *most likely*, given the data?

Answer: $\theta=0.6$

file:figures/week2/maxLikelihood.png

** Maximum likelihood estimation

A key problem in statistical inference is how to infer from *sample data* to *population parameters*.

\vspace{1cm}

Maximum likelihood estimation is one solution to this problem

** Maximum likelihood estimation

Basic workflow:
1. collect data
2. decide on a "model" for the data (e.g., binomial, normal, etc.)
3. define a likelihood function based on the underlying model
4. find the parameter value(s) that *maximize* the likelihood function

