#+TITLE: PSYC 4301: Psychological Tests and Measurements
#+AUTHOR: 
#+DATE: Spring 2021
#+OPTIONS: toc:nil
#+OPTIONS: num:nil
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [10pt]
#+LATEX_HEADER: \usepackage[left=1in,right=1in,bottom=1in,top=1in]{geometry}

** Contact info
- Professor: Thomas J. Faulkenberry, Ph.D
- Office: Math 319
- Office hours: /to be announced/
- Email: faulkenberry@tarleton.edu
- Website: [[http://tomfaulkenberry.github.io]]
- Phone: 254-968-9816

** Course description

This course will provide students with an introduction to the fundamental concepts of psychological testing and measurement. It is roughly divided into three parts. In Part 1, we introduce the basic statistical concepts underlying psychological measurement, including score transformations, composite scores, and issues with dichotomous scales. In Part 2, we learn how to estimate reliability and validity of tests. Finally, in Part 3, we dive into construct validity and learn the modern techniques of factor analysis and structural equation modeling. All students are expected to have some background in basic statistical methods (PSYC 2317 or equivalent). 

** Course materials
- Textbook
  - there is no specific textbook for this course. I will provide you with detailed lecture notes and some readings from primary sources (i.e., journal articles). All materials will be available on Canvas. If you need a review of basic statistics, I would recommend the free textbook /Learning Statistics with JASP/ by Navarro, Foxcroft, and Faulkenberry, which you can download from https://www.learnstatswithjasp.com.
- Software
  - we will regularly use JASP, which is a free software package for doing both conventional and Bayesian statistics. You can download it for free from https://jasp-stats.org (you must have a computer running MacOS, Windows, or Linux -- it does not work well on "thin client" systems such as Chromebooks or tablets).   
- Calculator
  - you should have a standalone calculator that is capable of performing the most basic scientific computations (exponents, square roots, logarithms, etc.). A graphing calculator is /not/ required, though I will be using one (TI-84) when I demonstrate calculations. Find a calculator you like using!

** Student learning outcomes
1. Understand the basic statistical concepts that underly psychological measurement, including transformations, variance of composite scores, and how to deal with dichotomous scales
2. Apply classical test theory to various methods of estimating reliability
3. Understand the differences among content validity, criterion-related validity, and construct validity.
4. Apply methods of factor analysis and structural equation modeling to uncover latent structure of psychological constructs.

** Course format

This course will be delivered in a hybrid-flexible ("HyFlex") format, giving you the option of attending the course face-to-face and/or online. The basic structure of each week is as follows:

- early in the week, you will watch an online video lecture (given by me) explaining the week's topic and take a short quiz to assess your understanding.

- you can then attend ONE in-person course meeting (either Tuesday or Thursday, but not both). The purpose of this course meeting is for me to demonstrate examples of homework problems that are assigned for the given week and give you the opportunity to ask questions. Half the class will be able to attend on Tuesday, and the other half will be able to attend on Thursday. Your specific day of the week will be assigned and communicated to you in Canvas and by email. In this way, each student will have the opportunity to attend class in-person once each week.

Note that you are not /required/ to attend the face-class meetings at all! You may certainly wish to attend face-to-face, and I encourage all who can to do so. However, there are other ways to attend the weekly problem sessions:
  - You may attend either session virtually by Zoom (that is, you can watch the problem session /live/ on your computer during class time).
  - You may choose to simply watch the recorded problem sessions at a convenient time later in the week. All class recordings will be posted on Canvas.

It does not matter which mode of attendance you choose -- that is the point of our "Hybrid-Flexible" course format. And, you can change your mind each week. The only thing that is /required/ is that you complete the quizzes, homeworks, and exams, which I'll describe in the next section.

** Requirements and grading
- Exam 1 (100 points)
- Exam 2 (100 points)
- Exam 3 (100 points)
- Homework exercises (100 points)
- Weekly quizzes (100 points)
- /Total = 500 points/

Grades will be assigned based on the percentage of points you accumulate out of these 500 points.  I will use the standard grading scale of A=90%, B=80%, etc.

*** Exams (60% of grade)
There will be three exams throughout the semester, occurring approximately once every four to five weeks.  They will cover material from lectures, quizzes, and homework exercises. Exams will be "take-home", primarily consisting of short-answer questions. Exams (and homework; see below) will be submitted online on Canvas -- in my experience, it is probably easiest to hand-write your solutions neatly on clean paper and either scan or take a photo of the completed work to submit. 

Exam dates:

- Exam 1 (due Sunday, February 21 at 11:59 pm)
- Exam 2 (due Sunday, April 4 at 11:59 pm)
- Exam 3 (due Sunday, May 2 at 11:59 pm)

*** Weekly quizzes (20% of grade)

At the beginning of each non-exam week, you will watch a video posted on Canvas where I introduce the week's concepts. After watching this video, you will complete an online multiple-choice quiz, the aim of which is to check for understanding of the concepts presented. Each quiz counts for 10 possible points. There will be at least 10 of these quizzes, so your 10 highest quiz scores will earn you up to 100 points for your overall quiz grade.
  
*** Homework exercises (20% of grade) 
In order to practice the concepts you learn this semester, you will complete a short homework assignment every week. A brief set of homework exercises will be provided to you each week. You may work collaboratively on the homework exercises, but any work submitted must reflect your own understanding of the material (in other words, don't just copy someone else's work to submit). Completed exercises should be handwritten neatly on clean paper. Each homework assignment will be due at the beginning of class on Tuesday of the week after it is assigned.

** Course Communication

Email is the primary means of official communication for this course.  If you have questions about the course, always feel free to send me an email at faulkenberry@tarleton.edu.  I only ask that you adhere to two guidelines:
  - please include the course number (PSYC 4301) in the subject line.  For example, one good way to do this is:  Subject: [PSYC 4301] Question about Exam 2
  - please use proper email etiquette.  Include a salutation (e.g., Dear Dr. Faulkenberry), complete sentences, and a closing (e.g., "Regards, Your Name").  You might be surprised how many times I get an email from a nondescript email address with no indication from WHOM the email was sent!

Also, I will send periodic class announcements via email.  Thus, it is imperative that you check your /Tarleton email address/ regularly so that you don't miss any of these messages.

** CV Points for Psychology Majors
All Tarleton psychology majors will be required to accumulate a certain number of "CV points" as a pass/fail component of their senior capstone course. CV is an acronym for "curriculum vitae", which is the traditional name of an academic resume. Because it is a requirement of senior capstone, no psychology major will be able to graduate without completion/verification of the required 15 CV points. Some classes may build in CV point assignments, but ultimately it is the students’ responsibility to monitor their participation and acquire points during their time at Tarleton. More information on pre-approved CV points, submission, and tracking of these points can be found in the CV Point Canvas site. Please note that submissions are graded, and may not be approved for points if they do not meet the CV standard.  If a student has a question about CV points, they should send an email to psychcvpointga@tarleton.edu.

** University Policy on "F" Grades
Beginning in Fall 2015, Tarleton will begin differentiating between a failed grade in a class because a student never attended (F0 grade), stopped attending at some point in the semester (FX grade), or because the student did not pass the course (F) but attended the entire semester. These grades will be noted on the official transcript. Stopping or never attending class can result in the student having to return aid monies received.  For more information see the Tarleton Financial Aid website.

** Academic Honesty

Tarleton State University expects its students to maintain high standards of personal and scholarly conduct. Students guilty of academic dishonesty are subject to disciplinary action. Cheating, plagiarism (submitting another person’s materials or ideas as one’s own), or doing work for another person who will receive academic credit are all disallowed. This includes the use of unauthorized books, notebooks, or other sources in order to secure of give help during an examination, the unauthorized copying of examinations, assignments, reports, or term papers, or the presentation of unacknowledged material as if it were the student’s own work. Disciplinary action may be taken beyond the academic discipline administered by the faculty member who teaches the course in which the cheating took place.

In particular, any exam taken online must be completed without the aid of any unauthorized resource (including using any search engine, Google, etc.).  Authorized resources are limited only to the official textbook and any lecture notes from the course.  Any other authorized resources will be provided to you before the exam.  The minimum sanction for violation of this policy is a grade of 0 on the affected exam.

Each student’s honesty and integrity are taken for granted. However, if I find evidence of academic misconduct I will pursue the matter to the fullest extent permitted by the university. ACADEMIC MISCONDUCT OR DISHONESTY WILL RESULT IN A GRADE OF F FOR THE COURSE.  Students are strongly advised to avoid even the /appearance/ of academic misconduct. 

** Academic Affairs Core Value Statements
*** Academic Integrity Statement
Tarleton State University's core values are integrity, leadership, tradition, civility, excellence, and service.  Central to these values is integrity, which is maintaining a high standard of personal and scholarly conduct.  Academic integrity represents the choice to uphold ethical responsibility for one’s learning within the academic community, regardless of audience or situation.

*** Academic Civility Statement 
Students are expected to interact with professors and peers in a respectful manner that enhances the learning environment. Professors may require a student who deviates from this expectation to leave the face-to-face (or virtual) classroom learning environment for that particular class session (and potentially subsequent class sessions) for a specific amount of time. In addition, the professor might consider the university disciplinary process (for Academic Affairs/Student Life) for egregious or continued disruptive behavior.

*** Academic Excellence Statement
Tarleton holds high expectations for students to assume responsibility for their own individual learning. Students are also expected to achieve academic excellence by:
- honoring Tarleton’s core values, upholding high standards of habit and behavior.
- maintaining excellence through class attendance and punctuality, preparing for active participation in all learning experiences. 
- putting forth their best individual effort.
- continually improving as independent learners.
- engaging in extracurricular opportunities that encourage personal and academic growth.
- reflecting critically upon feedback and applying these lessons to meet future challenges.

** Students with Disabilities Policy

It is the policy of Tarleton State University to comply with the Americans with Disabilities  Act (www.ada.gov) and other applicable laws.  If you are a student with a disability seeking accommodations for this course, please contact the Center for Access and Academic Testing, at 254.968.9400 or caat@tarleton.edu. The office is located in Math 201. More information can be found at www.tarleton.edu/caat or in the University Catalog.​
 
*Note:  any changes to this syllabus will be communicated to you by the instructor!*

** Schedule of class meetings

 | Week | Dates        | Topic                                      |
 |------+--------------+--------------------------------------------|
 |    1 | Jan 19,21    | Introduction to the course                 |
 |    2 | Jan 26,28    | Transformations of test scores             |
 |    3 | Feb 2,4      | Statistical properties of composite scores |
 |    4 | Feb 9,11     | Issues with dichotomous scales             |
 |    5 | Feb 16,18    | No class meetings - complete *Exam 1*      |
 |    6 | Feb 23,25    | Classical test theory                      |
 |    7 | Mar 2,4      | Estimating reliability of tests            |
 |    8 | Mar 9,11     | Criterion-related validity                 |
 |    9 | Mar 16,18    | /No class meeting -- Spring Break/         |
 |   10 | Mar 23,25    | Introduction to construct validity         |
 |   11 | Mar 30,Apr 1 | No class meeting - complete *Exam 2*       |
 |   12 | Apr 6,8      | Exploratory factor analysis                |
 |   13 | Apr 13,15    | Confirmatory factor analysis               |
 |   14 | Apr 20,22    | Structural equation modeling               |
 |   15 | Apr 27,29    | No class meeting - complete *Exam 3*       |
 

