#+TITLE: PSYC 4301: Psychological Tests and Measurements
#+AUTHOR: 
#+DATE: Spring 2021
#+OPTIONS: toc:nil
#+OPTIONS: num:nil
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [10pt]
#+LATEX_HEADER: \usepackage[left=1in,right=1in,bottom=1in,top=1in]{geometry}

** Contact info
- Professor: Thomas J. Faulkenberry, Ph.D
- Office: Math 319
- Office hours: /to be announced/
- Email: faulkenberry@tarleton.edu
- Website: [[http://tomfaulkenberry.github.io]]
- Phone: 254-968-9816

** Course description

This course will provide students with an introduction to the fundamental concepts of psychological testing and measurement. It is roughly divided into three parts. In Part 1, we introduce the basic theoretical concepts underlying psychological measurement, including psychological scaling, covariance/correlation. In Part 2, we take a hands-on approach and learn how to estimate reliability and validity. Finally, in Part 3, we cover some practical issues with test development and evaluation, including factor analysis and structural equation modeling. All students are expected to have some background in basic statistical methods (PSYC 2317 or equivalent). 

** Course materials
- /Textbook/: There are a lot of very good textbooks in psychological testing and measurement theory. However, I do not lecture directly from any specific textbook. I do recommend the following as a good reference to follow this semester, as it does a good job of bridging the theory of psychometrics with hands-on, practical examples.
  - /Measurement Theory in Action/ (2nd edition) by Shultz, Whitney, and Zickar ([[https://www.amazon.com/Measurement-Theory-Action-Studies-Exercises/dp/0415644798][Amazon link]])

- /Calculator/: you will need a basic scientific calculator to perform various calculations on homework and exams. I use a TI-84 (mine is over 20 years old and still works!), but any calculator with square roots and logarithms will suffice.

- /JASP statistical software/: some of the exercises we do this semester will be done on the computer, and we will use JASP, which is freely downloadable from [[http://www.jasp-stats.com][www.jasp-stats.com]]. JASP should be installed on all campus computers, but if you have a personal computer/laptop, go ahead and install it there...it is free, so why not?

** Student learning outcomes
1. Understand the basic concepts of psychological scaling, covariance, and test dimensionality
2. Apply classical test theory to various methods of estimating reliability
3. Understand the differences among content validity, criterion-related validity, and construct validity.
4. Know the basics of test construction, including item analysis and scoring.

** Requirements and grading
- Exam 1 (100 pts)
- Exam 2 (100 pts)
- Exam 3 (100 pts)
- Final exam (100 pts)
- Homework exercises (100 pts)
- /Total = 500 points/

Grades will be assigned based on the percentage of points you accumulate out of these 500 points.  I will use the standard grading scale of A=90%, B=80%, etc.

*** Exams
There will be 3 exams throughout the semester, occurring approximately once every four weeks.  They will cover material from lectures and homework exercises. Exams will be completed in class.

Exam dates:

- Exam 1 (Thursday, February 13)
- Exam 2 (Thursday, March 26)
- Exam 3 (Thursday, April 23)
- Final exam (Tuesday, May 5, 1-3 pm)

/Note: after March 23, all activities shifted to online.  All assessment will be done with "take-home" homework exercises. There will be no in-class exams for the remaining of the semester./
  
*** Homework exercises 
In order to practice the concepts you learn this semester, you will complete a short homework assignment every week. A brief set of homework exercises will be provided to you each week. You may work collaboratively on the homework exercises, but any work submitted must reflect your own understanding of the material (in other words, don't just copy someone else's work to submit). Completed exercises should be handwritten neatly on clean paper. Each homework assignment will be due at the beginning of class on Tuesday of the week after it is assigned.

** Course Communication

Email is the primary means of official communication for this course.  If you have questions about the course, always feel free to send me an email at faulkenberry@tarleton.edu.  I only ask that you adhere to two guidelines:
  - please include the course number (PSYC 4301) in the subject line.  For example, one good way to do this is:  Subject: [PSYC 4301] Question about Exam 2
  - please use proper email etiquette.  Include a salutation (e.g., Dear Dr. Faulkenberry), complete sentences, and a closing (e.g., "Regards, Your Name").  You might be surprised how many times I get an email from a nondescript email address with no indication from WHOM the email was sent!

Also, I will send periodic class announcements via email.  Thus, it is imperative that you check your /Tarleton email address/ regularly so that you don't miss any of these messages.

** CV Points for Psychology Majors
All Tarleton psychology majors will be required to accumulate a certain number of "CV points" as a pass/fail component of their senior capstone course. CV is an acronym for "curriculum vitae", which is the traditional name of an academic resume. Because it is a requirement of senior capstone, no psychology major will be able to graduate without completion/verification of the required 15 CV points. Some classes may build in CV point assignments, but ultimately it is the students’ responsibility to monitor their participation and acquire points during their time at Tarleton. More information on pre-approved CV points, submission, and tracking of these points can be found in the CV Point Canvas site. Please note that submissions are graded, and may not be approved for points if they do not meet the CV standard.  If a student has a question about CV points, they should send an email to psychcvpointga@tarleton.edu.

** University Policy on "F" Grades
Beginning in Fall 2015, Tarleton will begin differentiating between a failed grade in a class because a student never attended (F0 grade), stopped attending at some point in the semester (FX grade), or because the student did not pass the course (F) but attended the entire semester. These grades will be noted on the official transcript. Stopping or never attending class can result in the student having to return aid monies received.  For more information see the Tarleton Financial Aid website.

** Academic Honesty

Tarleton State University expects its students to maintain high standards of personal and scholarly conduct. Students guilty of academic dishonesty are subject to disciplinary action. Cheating, plagiarism (submitting another person’s materials or ideas as one’s own), or doing work for another person who will receive academic credit are all disallowed. This includes the use of unauthorized books, notebooks, or other sources in order to secure of give help during an examination, the unauthorized copying of examinations, assignments, reports, or term papers, or the presentation of unacknowledged material as if it were the student’s own work. Disciplinary action may be taken beyond the academic discipline administered by the faculty member who teaches the course in which the cheating took place.

In particular, any exam taken online must be completed without the aid of any unauthorized resource (including using any search engine, Google, etc.).  Authorized resources are limited only to the official textbook and any lecture notes from the course.  Any other authorized resources will be provided to you before the exam.  The minimum sanction for violation of this policy is a grade of 0 on the affected exam.

Each student’s honesty and integrity are taken for granted. However, if I find evidence of academic misconduct I will pursue the matter to the fullest extent permitted by the university. ACADEMIC MISCONDUCT OR DISHONESTY WILL RESULT IN A GRADE OF F FOR THE COURSE.  Students are strongly advised to avoid even the /appearance/ of academic misconduct. 

** Academic Affairs Core Value Statements
*** Academic Integrity Statement
Tarleton State University's core values are integrity, leadership, tradition, civility, excellence, and service.  Central to these values is integrity, which is maintaining a high standard of personal and scholarly conduct.  Academic integrity represents the choice to uphold ethical responsibility for one’s learning within the academic community, regardless of audience or situation.

*** Academic Civility Statement 
Students are expected to interact with professors and peers in a respectful manner that enhances the learning environment. Professors may require a student who deviates from this expectation to leave the face-to-face (or virtual) classroom learning environment for that particular class session (and potentially subsequent class sessions) for a specific amount of time. In addition, the professor might consider the university disciplinary process (for Academic Affairs/Student Life) for egregious or continued disruptive behavior.

*** Academic Excellence Statement
Tarleton holds high expectations for students to assume responsibility for their own individual learning. Students are also expected to achieve academic excellence by:
- honoring Tarleton’s core values, upholding high standards of habit and behavior.
- maintaining excellence through class attendance and punctuality, preparing for active participation in all learning experiences. 
- putting forth their best individual effort.
- continually improving as independent learners.
- engaging in extracurricular opportunities that encourage personal and academic growth.
- reflecting critically upon feedback and applying these lessons to meet future challenges.

** Students with Disabilities Policy

It is the policy of Tarleton State University to comply with the Americans with Disabilities  Act (www.ada.gov) and other applicable laws.  If you are a student with a disability seeking accommodations for this course, please contact the Center for Access and Academic Testing, at 254.968.9400 or caat@tarleton.edu. The office is located in Math 201. More information can be found at www.tarleton.edu/caat or in the University Catalog.​
 
*Note:  any changes to this syllabus will be communicated to you by the instructor!*


** Semester Schedule
| Unit | Dates        | Topic                                                  |
|------+--------------+--------------------------------------------------------|
|      | Jan 13-17    | (no class -- I will be at Joint Mathematics Meetings)  |
|      |              | /Part 1 - Basic concepts in psychological measurement/ |
|    1 | Jan 20-24    | Psychological scaling                                  |
|    2 | Jan 27-31    | Individual differences and covariance/correlation      |
|    3 | Feb 3-7      | Dimensionality and factor analysis                     |
|      | *Feb 10-14*  | *Exam 1*                                               |
|------+--------------+--------------------------------------------------------|
|      |              | /Part 2 -- Estimating reliability and validity/        |
|    4 | Feb 17-21    | Classical test theory                                  |
|    5 | Feb 24-28    | Estimating reliability                                 |
|    6 | Mar 2-6      | Estimating criterion-related validity                  |
|      | Mar 9-13     | (no class -- Spring Break)                             |
|      | Mar 16-20    | (no class -- extended break due to COVID-19)           |
|    7 | Mar 23-27    | Estimating construct validity                          |
|------+--------------+--------------------------------------------------------|
|      |              | /Part 3 -- Practical issues in testing/measurement/    |
|    8 | Mar 30-Apr 3 | Exploratory factor analysis in JASP                    |
|    9 | Apr 6-10     | Item analysis                                          |
|   10 | Apr 13-17    | Item response theory                                   |
|   11 | Apr 20-24    | Confirmatory factor analysis                           |
|------+--------------+--------------------------------------------------------|

/Note: beginning March 23, all activities are shifted to online. See Canvas page for more details./
