#+TITLE: PSYC 3330: Elementary Statistics for the Behavioral Sciences
#+AUTHOR: 
#+DATE: Spring 2017
#+OPTIONS: toc:nil
#+OPTIONS: num:nil
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [10pt]
#+LATEX_HEADER: \usepackage[left=1in,right=1in,bottom=1in,top=1in]{geometry}

** Contact info
- Professor: Thomas J. Faulkenberry, Ph.D
- Office: Math 319
- Office hours: MTWRF 1-3 pm
- Email: faulkenberry@tarleton.edu
- Website: [[http://tomfaulkenberry.github.io]]
- Phone: 254-968-9816

** Course description

Statistical methods are the primary tool for research in psychology.  
They are what allow us as researchers to make consistent, data-driven 
decisions.  As such, this is an extremely important course and one that I 
take very seriously as your professor.

The topics we will cover this semester will include descriptive statistics 
(how we describe data) and inferential statistics (how we make decisions 
about data).  Specifically, this includes central tendency, variability, 
correlation, the distinction between populations and samples, hypothesis 
testing, statistical significance, and a variety of inferential tests 
that we can apply to data, including t-tests and analysis of variance.

** Course materials
- /Statistics for the Behavioral Sciences (10th ed.)/ by Gravetter and Wallnau [[http://www.amazon.com/Statistics-Behavioral-Sciences-MindTap-Psychology/dp/1305504917/][Amazon link]]
- Note:  older editions of this textbook are just fine.  Please feel free to find a used copy of an older edition on Amazon; it will save you a LOT of money!

** Student learning outcomes
1. Identify variables under study (including independent and dependent variables)
2. Choose appropriate measures of descriptive statistics
3. Select and perform appropriate inferential statistics
4. Draw appropriate statistical conclusions from results of analyses

** Requirements and grading
- Exam 1 (100 pts)
- Exam 2 (100 pts)
- Exam 3 (100 pts)
- Final exam (150 pts)
- Unit quizzes (100 pts)
- Homework exercises (50 pts)
- /Total = 600 points/

Grades will be assigned based on the percentage of points you accumulate out of these 600 points.  I will use the standard grading scale of A=90%, B=80%, etc.

*** Exams (75% of grade)
There will be four total exams throughout the semester, occurring 
approximately once every three to four weeks.  They will cover material 
from lectures, quizzes, and homework exercises.  Exam questions will be a mix of multiple choice and short answer.  Exams are due by 11:59 pm on 
Sunday of the given week.  Each exam will have a time limit and may only 
be attempted once.

Due dates:

- Exam 1 (Feb 12 at 11:59 pm)
- Exam 2 (Mar 12 at 11:59 pm)
- Exam 3 (Apr 23 at 11:59 pm)
- Final exam (April 30 at 11:59 pm)
  
*** Unit quizzes (17% of grade)
At the end of each unit, you will complete a quiz over the content of that 
unit. Each quiz counts for 10 possible points.  Since there are 10 units, 
you will earn up to 100 points for your quiz grade.

*** Homework exercises (8% of grade)
In order to practice the statistical concepts you learn this semester, you will complete short homework assignments for every unit.  A set of homework exercises (no more than 10 exercises per unit) will be provided to you on Blackboard.  You may work collaboratively on the homework exercises, but any work submitted must reflect your own understanding of the material (in other words, don't just copy someone else's work to submit).  Completed exercises should be handwritten and scanned to submit on Blackboard.  Note that if you do not have access to a good scanner, you may instead just take photos of the completed pages with your phone and upload these photos.  Please just make sure that your submitted photo files are not too large (e.g., use the "small" or "medium" size setting on your phone).

** Course Communication

I am your primary resource for this course. I AM an experimental psychologist, so I do the stuff I teach about daily. Hence, my primary interest is for you to learn this material and do well in the course. If you have a question, always feel free to stop by my office and visit.  If you require electronic communication, email is best, but you may also send me a Blackboard message.  Just keep in mind that I don't get any notifications of Blackboard messages, so I may not see your message until I next log into the course.

** University Policy on "F" Grades
Beginning in Fall 2015, Tarleton will begin differentiating between a 
failed grade in a class because a student never attended (F0 grade), 
stopped attending at some point in the semester (FX grade), or because 
the student did not pass the course (F) but attended the entire semester. 
These grades will be noted on the official transcript. Stopping or never 
attending class can result in the student having to return aid monies 
received.  For more information see the Tarleton Financial Aid website.

** Academic Honesty

Tarleton State University expects its students to maintain high standards of
personal and scholarly conduct. Students guilty of academic dishonesty are
subject to disciplinary action. Cheating, plagiarism (submitting another person’s materials or ideas as one’s own), or doing work for another person who will receive academic credit are all disallowed. This includes the use of unauthorized books, notebooks, or other sources in order to secure of give help during an examination, the unauthorized copying of examinations, assignments, reports, or term papers, or the presentation of unacknowledged material as if it were the student’s own work. Disciplinary action may be taken beyond the academic discipline administered by the faculty member who teaches the course in which the cheating took place.

In particular, any exam taken online must be completed without the aid of any unauthorized resource (including using any search engine, Google, etc.).  Authorized resources are limited only to the official textbook and any lecture notes from the course.  Any other authorized resources will be provided to you before the exam.  The minimum sanction for violation of this policy is a grade of 0 on the affected exam.

Each student’s honesty and integrity are taken for granted. However, if I find
evidence of academic misconduct I will pursue the matter
to the fullest extent permitted by the university. ACADEMIC MISCONDUCT OR
DISHONESTY WILL RESULT IN A GRADE OF F FOR THE COURSE.  Students are
strongly advised to avoid even the /appearance/ of academic misconduct. 

** Academic Affairs Core Value Statements

*** Academic Integrity Statement
Tarleton State University's core values are integrity, leadership, tradition, civility, excellence, and service.  Central to these values is integrity, which is maintaining a high standard of personal and scholarly conduct.  Academic integrity represents the choice to uphold ethical responsibility for one’s learning within the academic community, regardless of audience or situation.

*** Academic Civility Statement 
Students are expected to interact with professors and peers in a respectful manner that enhances the learning environment. Professors may require a student who deviates from this expectation to leave the face-to-face (or virtual) classroom learning environment for that particular class session (and potentially subsequent class sessions) for a specific amount of time. In addition, the professor might consider the university disciplinary process (for Academic Affairs/Student Life) for egregious or continued disruptive behavior.

*** Academic Excellence Statement
Tarleton holds high expectations for students to assume responsibility for their own individual learning. Students are also expected to achieve academic excellence by:
- honoring Tarleton’s core values, upholding high standards of habit and behavior.
- maintaining excellence through class attendance and punctuality, preparing for active participation in all learning experiences. 
- putting forth their best individual effort.
- continually improving as independent learners.
- engaging in extracurricular opportunities that encourage personal and academic growth.
- reflecting critically upon feedback and applying these lessons to meet future challenges.

** Students with Disabilities Policy

It is the policy of Tarleton State University to comply with the Americans
with Disabilities Act and other applicable laws. If you are a student with a
disability seeking accommodations for this course, please contact Trina
Geye, Director of Student Disability Services, at 254.968.9400 or
geye@tarleton.edu. Student Disability Services is
located in Math 201. More information can be found at www.tarleton.edu/sds or in the University Catalog.


**Note:  any changes to this syllabus will be communicated to you by the instructor!**
 
** Semester Schedule
| Unit | Dates        | Topic                                                        |
|------+--------------+--------------------------------------------------------------|
|    1 | Jan 16-22    | Displaying data                                              |
|    2 | Jan 23-29    | Descriptives 1: central tendency, variation, and z-scores    |
|    3 | Jan 30-Feb 5 | Descriptives 2: correlation                                  |
|      | Feb 6-12     | *Exam 1 (due February 12)*                                   |
|    4 | Feb 13-19    | The normal distribution: measuring likelihood                |
|    5 | Feb 20-26    | The logic of hypothesis testing                              |
|    6 | Feb 27-Mar 5 | Testing means of samples of *known* populations: $z$-tests   |
|      | Mar 6-12     | *Exam 2 (due March 12)*                                      |
|      | Mar 13-19    | /Spring break!/                                              |
|    7 | Mar 20-26    | Testing means of samples of *unknown* populations: $t$-tests |
|    8 | Mar 27-Apr 2 | More $t$-tests (independent samples, etc.)                   |
|    9 | Apr 3-9      | Analysis of variance (ANOVA): one independent variable       |
|   10 | Apr 10-16    | Analysis of variance (ANOVA): two independent variables      |
|      | Apr 17-23    | *Exam 3 (due April 23)*                                      |
|      | Apr 24-30    | *Final exam (due April 30)*                                  |
