#+TITLE: PSYC 5316: Advanced Quantitative Methods
#+AUTHOR: 
#+DATE: Fall 2017
#+OPTIONS: toc:nil
#+OPTIONS: num:nil
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [10pt]
#+LATEX_HEADER: \usepackage[left=1in,right=1in,bottom=1in,top=1in]{geometry}

** Contact info
- Professor: Thomas J. Faulkenberry, Ph.D
- Office: Math 319
- Office hours: /TBA/
- Email: faulkenberry@tarleton.edu
- Website: [[http://tomfaulkenberry.github.io]]
- Phone: 254-968-9816
  
** Course description and outline

This course is designed to teach you the advanced quantitative methods necessary to read and conduct modern empirical research.  Our discipline focus is on applied psychology, but the methods we discuss will be applicable to a wide range of disciplines.  Students taking this course are expected to have *previously* taken a graduate level course in statistics (or equivalent statistical training).  

Tentatively, I expect that we will cover the following topics:

**** Review of classical statistical methods (5 weeks)
- Basic notions of probability, including expected value, conditional probability, and independence
- Probability distributions commonly used for applied work, including discrete distributions (e.g., binomial, geometric, and Poisson distributions) and continuous distributions (e.g., normal, exponential, Gamma, and chi-square distributions)
- sampling distributions and confidence intervals
- hypothesis testing
- common hypothesis tests (including t-test, anova, chi-square, etc.)

**** Robust methods (3 weeks)
- bootstrapping
- robust measures of location (including trimmed means, Winsorized means, $M$-estimators, etc.) 
- inferences based on robust measures

**** Bayesian methods (5 weeks)
- Bayes' Theorem, priors, likelihoods
- estimating proportions and rates (using both exact methods via conjugate priors and simulation-based Markov chain Monte Carlo (MCMC) methods)
- fitting models with JAGS and R
- Bayesian hypothesis testing

** Course materials

- /Fundamentals of Modern Statistical Methods/ (2nd ed.) by Wilcox (2010) ([[https://www.amazon.com/Fundamentals-Modern-Statistical-Methods-Substantially/dp/1441955240/][Amazon link)]]
- /Bayesian Statistical Inference/ by Iversen (1984) ([[https://www.amazon.com/Bayesian-Statistical-Inference-Quantitative-Applications/dp/0803923287/][Amazon link)]]
- R statistical software (free download from [[http://www.r-project.org][www.r-project.org]])
- RStudio (free download from [[http://www.rstudio.com][www.rstudio.com]])
- JAGS (free download from [[http://mcmc-jags.sourceforge.net][mcmc-jags.sourceforge.net]])

** Student learning outcomes

1. 

** Requirements and grading

- Exam 1 (100 pts)
- Exam 2 (100 pts)
- Exam 3 (100 pts)
- Weekly problem sets (100 pts)
- /Total = 400 points/

Grades will be assigned based on the percentage of points you accumulate out of these 400 points.  I will use the standard grading scale of A=90%, B=80%, etc.

*** Exams (75% of grade)
There will be three exams throughout the semester.  Exams will be performed in class.  Unless otherwise specified, students may use class notes, but exams must be completed /individually/.  

Tentative exam dates:

- Exam 1: October 2 (during week 6)
- Exam 2: October 30 (during week 10)
- Exam 3: December 11 (during week 16)

*** Weekly problem sets (25% of grade)
At the end of each weekly lecture, a set of problems will be distributed to students for completion during the subsequent week.  Students may work collaboratively, but all final work submitted for credit must be the student's /own/ interpretation of the collaborative work.

** Course Communication

This course is designed to be an intensive, interactive seminar on modern statistical methods.  That means that I will be available for one-on-one consultation most any time.  Just stop by my office or give me a call.

All official course communication (questions, setting up a meeting, etc.) will be conducted by email.  Any time you need to contact me, feel free to send me an email at faulkenberry@tarleton.edu.  I only ask that you adhere to two guidelines:
  - please include the course number (PSYC 5316) in the subject line.  For example, one good way to do this is:  Subject: [PSYC 5316] Question about problem set 3
  - please use proper email etiquette.  Include a salutation (e.g., Dear Dr. Faulkenberry), complete sentences, and a closing (e.g., "Regards, Your Name").  You might be surprised how many times I get an email from a nondescript email address with no indication from WHOM the email was sent!

Also, I will be sending periodic emails to each of you that update you on course progress, due dates, etc.  It is imperative that you check your /Tarleton email address/ regularly so that you don't miss any of these messages.

** University Policy on "F" Grades
Beginning in Fall 2015, Tarleton will begin differentiating between a failed grade in a class because a student never attended (F0 grade), stopped attending at some point in the semester (FX grade), or because the student did not pass the course (F) but attended the entire semester. These grades will be noted on the official transcript. Stopping or never attending class can result in the student having to return aid monies received.  For more information see the Tarleton Financial Aid website.

** Academic Honesty

Tarleton State University expects its students to maintain high standards of personal and scholarly conduct. Students guilty of academic dishonesty are subject to disciplinary action. Cheating, plagiarism (submitting another person’s materials or ideas as one’s own), or doing work for another person who will receive academic credit are all disallowed. This includes the use of unauthorized books, notebooks, or other sources in order to secure of give help during an examination, the unauthorized copying of examinations, assignments, reports, or term papers, or the presentation of unacknowledged material as if it were the student’s own work. Disciplinary action may be taken beyond the academic discipline administered by the faculty member who teaches the course in which the cheating took place.

In particular, any exam taken online must be completed without the aid of any unauthorized resource (including using any search engine, Google, etc.).  Authorized resources are limited only to the official textbook and any lecture notes from the course.  Any other authorized resources will be provided to you before the exam.  The minimum sanction for violation of this policy is a grade of 0 on the affected exam.

Each student’s honesty and integrity are taken for granted. However, if I find evidence of academic misconduct I will pursue the matter to the fullest extent permitted by the university. ACADEMIC MISCONDUCT OR DISHONESTY WILL RESULT IN A GRADE OF F FOR THE COURSE.  Students are strongly advised to avoid even the /appearance/ of academic misconduct. 

** Academic Affairs Core Value Statements

*** Academic Integrity Statement
Tarleton State University's core values are integrity, leadership, tradition, civility, excellence, and service.  Central to these values is integrity, which is maintaining a high standard of personal and scholarly conduct.  Academic integrity represents the choice to uphold ethical responsibility for one’s learning within the academic community, regardless of audience or situation.

*** Academic Civility Statement 
Students are expected to interact with professors and peers in a respectful manner that enhances the learning environment. Professors may require a student who deviates from this expectation to leave the face-to-face (or virtual) classroom learning environment for that particular class session (and potentially subsequent class sessions) for a specific amount of time. In addition, the professor might consider the university disciplinary process (for Academic Affairs/Student Life) for egregious or continued disruptive behavior.

*** Academic Excellence Statement
Tarleton holds high expectations for students to assume responsibility for their own individual learning. Students are also expected to achieve academic excellence by:
- honoring Tarleton’s core values, upholding high standards of habit and behavior.
- maintaining excellence through class attendance and punctuality, preparing for active participation in all learning experiences. 
- putting forth their best individual effort.
- continually improving as independent learners.
- engaging in extracurricular opportunities that encourage personal and academic growth.
- reflecting critically upon feedback and applying these lessons to meet future challenges.

** Students with Disabilities Policy

It is the policy of Tarleton State University to comply with the Americans
with Disabilities Act and other applicable laws. If you are a student with a
disability seeking accommodations for this course, please contact Trina
Geye, Director of Student Disability Services, at 254.968.9400 or
geye@tarleton.edu. Student Disability Services is
located in Math 201. More information can be found at www.tarleton.edu/sds or in the University Catalog.


**Note:  any changes to this syllabus will be communicated to you by the instructor!**
 
