#+TITLE: Week 12 lecture notes - PSYC 3330
#+AUTHOR:
#+DATE: Nov 13-17, 2017 
#+OPTIONS: toc:nil num:nil

* The Chi-Square Test for Goodness of Fit

This week, we will talk about hypothesis testing for situations where the dependent variable is a *count* or a *proportion*, neither of which can be described as as normal distribution.

** Example 1
A researcher presented $n=50$ participants with an abstract painting (with no obvious top/bottom) and asked each participant to hang the painting in the orientation that looked correct.  The data are below:

| Top up | Bottom up | Left side up | Right side up |
|--------+-----------+--------------+---------------|
| 18     | 17        | 7            | 8             |

Is there any preference among the four options?  That is, are any of the orientations selected more often than would be expected by chance alone?

Step 1 - state null hypothesis

If there were NO preference, the proportions in each category would be equivalent.  Thus the null hypothesis would be that the expected count in each category would be 1/4 (25%) of the sample (that is, a /uniform/ distribution of counts):

| Top up | Bottom up | Left side up | Right side up |
|--------+-----------+--------------+---------------|
|    25% |       25% |          25% |           25% |
|   12.5 |      12.5 |         12.5 |          12.5 |

So, the technical definitions would be:

- $H_0$: all options are selected equally often
- $H_1$: some options are selected more often than others

As usual, we will use $\alpha=0.05$.

Step 2 - the Chi-Square statistic

In developing a statistic, we need something that will index how far away our distribution of counts is from a uniform distribution of counts.  That statistic is the /Chi-square/ statistic:

\[
\chi^2 = \sum \frac{(f_o-f_e)^2}{f_e}
\]

where:
  - f_o = observed count
  - f_e = expected count

As usual, this statistic has a table of critical values in the back of your textbook.  The table is based on $\alpha$ and $df$, which in this case represents the number of categories minus one.

So, based on our null hypothesis (with $df=3$) and choosing $\alpha=0.05$, we have $\chi^2_{\text{crit}}=7.81$.

Now, lets compute $\chi^2$:

\begin{align*}
\chi^2 &= \sum \frac{(f_o-f_e)^2}{f_e}\\
&= \frac{(18-12.5)^2}{12.5} + \frac{(17-12.5)^2}{12.5} + \frac{(7-12.5)^2}{12.5} + \frac{(8-12.5)^2}{12.5}\\
&= \frac{30.25}{12.5} + \frac{20.25}{12.5} + \frac{30.25}{12.5} + \frac{20.25}{12.5}\\
&= 2.42 + 1.62 + 2.42 + 1.62\\
&= 8.08
\end{align*}

Since $\chi^2_{\text{sample}} = 8.08$, which exceeds $\chi^2_{\text{crit}}$, we reject the null and conclude that some of the options are selected more frequently than others.

** Example 2
A researcher is interested in pizza preference. A sample of $n=45$ students is obtained and fresh pizza is ordered from each of 3 shops in town. Each student tastes all three pizzas and then selects a favorite. The observed frequencies are:

| Shop A | Shop B | Shop C |
|--------+--------+--------|
|     13 |     24 |      8 |

Is there a preference for one or more shops that exceeds chance?

Step 1: define null hypothesis

- $H_0$: each shop is chosen equally often
- $H_1$: one or more shops is selected more often than the others

If we choose $\alpha=0.05$, and we have $df=2$, we note from the table that $\chi^2_{\text{crit}}= 5.99$.

Step 2: compute $\chi^2$ statistic

Note that $f_e=15$ for each category.  Thus, we have 

\begin{align*}
\chi^2_{\text{samp}} &= \sum \frac{(f_o-f_e)^2}{f_e} \\
&= \frac{(13-15)^2}{15} + \frac{(24-15)^2}{15} + \frac{(8-15)^2}{15}\\
&= \frac{4}{15} + \frac{81}{15} + \frac{49}{15}\\
&= 0.267 + 5.4 + 3.267\\
&= 8.93\\
\end{align*}

Since $\chi^2_{\text{samp}}=8.93$ which exceeds $\chi^2_{\text{crit}}$, we reject $H_0$ and conclude that there is a preference among the three options.

* The Chi-Square Test for Independence
The chi-square test can also be used to test for relationships between *two* variables.

** Example 1
Suppose $n=200$ students are grouped according to personality (introvert, extrovert) and color preference (red, yellow, green, or blue).  The data are below:

|           | Red | Yellow | Green | Blue |
|-----------+-----+--------+-------+------|
| Introvert |  10 |      3 |    15 |   22 |
| Extrovert |  90 |     17 |    25 |   18 |

Are these data sufficient to conclude that there is a significant relationship between personality and color preference?

To answer this question, we will use the /chi-square test for independence/.

Step 1: define the null hypothesis

There are two ways to define this null.  
  - there is no relationship between color preference and personality
  - the proportions of color preferences among introverts are no different from the proportions of color preferences among extroverts

While longer, this second version is more useful!

Step 2: compute chi-squared statistic.

This step is no different from last time.  However, it may not immediately be clear HOW to define the /expected frequencies/.  To figure these out, let's consider our null hypothesis: there is no difference in proportions of color preferences between introverts and extroverts.

Let's start with an empty table with same row and column totals as our data:

|           | Red | Yellow | Green | Blue |     |
|-----------+-----+--------+-------+------+-----|
| Introvert |     |        |       |      |  50 |
| Extrovert |     |        |       |      | 150 |
|           | 100 |     20 |    40 |   40 | 200 |

From these totals, we can see the following:
- 100/200 = 50% prefer red
- 20/200 = 10% prefer yellow
- 40/200 = 20% prefer green
- 40/200 = 20% prefer blue

Now, we know that we have 50 introverts.  Based on these percentages, we know:
- 50% of 50 = 25 prefer red
- 10% of 50 = 5 prefer yellow
- 20% of 50 = 10 prefer green
- 20% of 50 = 10 prefer blue

Similarly, since we have 150 extroverts, we would have:
- 50% of 150 = 75 prefer red
- 10% of 150 = 15 prefer yellow
- 20% of 150 = 30 prefer green
- 20% of 150 = 30 prefer blue

Thus, the following table summarizes our findings (written as "observed (expected)"):

|           | Red     | Yellow  | Green   | Blue    |
|-----------+---------+---------+---------+---------|
| Introvert | 10 (25) | 3 (5)   | 15 (10) | 22 (10) |
| Extrovert | 90 (75) | 17 (15) | 25 (30) | 18 (30) |

We can now compute chi-squared:

\begin{align*}
\chi^2_{\text{samp}} &= \sum \frac{(f_o-f_e)^2}{f_e}\\
&= \frac{(10-25)^2}{25} + \frac{(3-5)^2}{5} + \frac{(15-10)^2}{10} + \frac{(22-10)^2}{10} + \frac{(90-75)^2}{75} + \frac{(17-15)^2}{15} + \frac{(25-30)^2}{30} + \frac{(18-30)^2}{30}\\
&= \frac{225}{25} + \frac{4}{5} + \frac{25}{10} + \frac{144}{10} + \frac{225}{75} + \frac{4}{15} + \frac{25}{30} + \frac{144}{30}\\
&= 9 + 0.8 + 2.5 + 14.4 + 0.33 + 0.83 + 4.8\\
&= 32.66\\
\end{align*}

Now, we need to know $\chi^2_{\text{crit}}$.  As before, we get this from the table, but how do we find $df$? 

For the chi-squared test of independence, we find $df$ via the following:

\[
df = (\text{# rows - 1})\cdot (\text{# columns - 1})
\]

Thus, for our example, 

\[
df = (2-1)\cdot (4-1) = 1\cdot 3 = 3
\]

From the table, if we assume $\alpha=0.05$, we see $\chi^2_{\text{crit}}=7.81$.  Thus, since $\chi^2_{\text{samp}}=32.66$ exceeds $\chi^2_{\text{crit}}$, we reject $H_0$ and conclude that the groups are not independent.  That is, the proportion of color preferences depends on the personality group.

** Example 2
A manufacturer of watches takes a sample of 200 people.  Each person is
classified by age and watch type preference (digital vs. analog).  The data are as follows:

|          | Digital | Analog | No preference |
|----------+---------+--------+---------------|
| Under 30 | 90      | 40     | 10            |
| Over 30  | 10      | 40     | 10            |

Is there a relationship between age and watch preference?

Step 1 - define the null

We set $H_0$: the proportion of watch preferences for "under 30" group is the same as the proportion of watch preferences for the "over 30" group.

As usual, we will use $\alpha=0.05$.  We compute $df=(3-1)(2-1)=2$, so we see that $\chi^2_{\text{crit}}=5.99$.

Step 2 - compute chi-squared

As before, we first need to compute expected frequencies.  Fortunately, there is an easy formula that we can use:

\[
f_e = \frac{f_{\text{column}}f_{\text{row}}}{n}
\]

It is fairly easy to show that this is an equivalent method to what we did above.

So, we first need to compute the column and row totals:

|          | Digital | Analog | No preference |     |
|----------+---------+--------+---------------+-----|
| Under 30 |      90 |     40 |            10 | 140 |
| Over 30  |      10 |     40 |            10 |  60 |
|          |     100 |     80 |            20 | 200 |

Now, we can compute the expected frequencies.  For example, for the first entry (top left), we have:

\[
f_e = \frac{f_{\text{column}}f_{\text{row}}}{n} = \frac{100\cdot 140}{200} = 70
\]

Continuing in this manner, we can compute the expected frequencies for the table (shown in parentheses):

|          | Digital | Analog  | No preference |
|----------+---------+---------+---------------|
| Under 30 | 90 (70) | 40 (56) | 10 (14)       |
| Over 30  | 10 (30) | 40 (24) | 10 (6)        |

Now we can compute chi-squared as before:

\begin{align*}
\chi^2_{\text{samp}} &= \sum \frac{(f_o-f_e)^2}{f_e}\\
&= \frac{(90-70)^2}{70} + \frac{(40-56)^2}{56} + \frac{(10-14)^2}{14} + \frac{(10-30)^2}{30} + \frac{(40-24)^2}{24} + \frac{(10-6)^2}{6}\\
&= \frac{400}{70} + \frac{256}{56} + \frac{16}{14} + \frac{400}{30} + \frac{256}{24} + \frac{16}{6}\\
&= 5.71 + 4.57 + 1.14 + 13.33 + 10.67 + 2.67\\
&= 38.09\\
\end{align*}

As before, since $\chi^2_{\text{samp}}$ exceeds $\chi^2_{\text{crit}}$, we reject $H_0$ and conclude that there is a relationship between age and watch preference..that is, age and watch preference are NOT independent.
