#+TITLE: Week 6 lecture notes - PSYC 3330
#+AUTHOR:
#+DATE: Oct 2-6, 2017 
#+OPTIONS: toc:nil num:nil

Last week, we talked about the probability of finding a particular score (or set of scores) in the population.  This week we will discuss probabilities of /sample means/.  In particular, we are interested in answering questions like the following:

  - What is the probability of obtaining a sample mean greater than X?

Also: 
  - with inferential statistics, we try to infer a population mean from a sample mean.  
  - since this is just an estimate, there is a certain amount of /sampling error/
  - how do we measure this sampling error?

* Distribution of sample means

To motivate the next definition, lets think about how we do research.  We take a sample, then we compute the mean.  How does our sample mean relate to the collection of /all possible sample means/? 

Definition: the /distribution of sample means/ is the collection of sample means for all the possible random samples of a particular size $n$ that can be obtained from a population.

** Example:
In a small box, place a bunch of slips of paper, each of which is labeled with 2, 4, 6, or 8.  Have each member of the class randomly select two slips of paper and write down the numbers, then return the slips of paper in the box.

After everyone has recorded their "sample", ask each member of the class to compute the /sample mean/.  Write down the sample means on the board, then complete the probability distribution:

| $\overline{X}$ | f | p |
|----------------+---+---|
| 2              |   |   |
| 3              |   |   |
| 4              |   |   |
| 5              |   |   |
| 6              |   |   |
| 7              |   |   |
| 8              |   |   |

This is the /distribution of sample means/.  We can use it to ask questions like:

  - What is the probability of obtaining a sample mean of 7 or greater?
  - What is the probability of obtaining a sample mean less than 3?

** Computer simulation
The idea from our class activity can be visualized on a larger scale using a neat web applet:
  - [[http://onlinestatbook.com/stat_sim/sampling_dist/]]
 
* Central Limit Theorem

From the applet demo in class, we can see the following properties of the distribution of sample means:
1. it is *normally distributed*
2. its mean (denoted $\mu_{\overline{x}}$) is the same as the population mean $\mu$
3. its standard deviation (denoted $\sigma_{\overline{x}}$) is equal to $\displaystyle{\frac{\sigma}{\sqrt{n}}}$.  This is called the *standard error* 

In fact, what this means is the following:  no matter what your population looks like (normally distributed or NOT), the distribution of sample means will be normally distributed with mean $\mu$ and standard deviation $\sigma/\sqrt{n}$.

* Some examples

*Example 1*: An instructor is interested in the IQ of her students.  She has 9 students in her class and thinks that they are, on average, really smart.  What is the probability that the group of students has a mean greater than or equal to 112?

  - We can use the standard normal table as in the last unit.  However, since this is a /sample/, we need to compute a $z$ score on the /distribution of samples means/.  So we get:

\[
z = \frac{\overline{x}-\mu}{\sigma_{\overline{x}}} = \frac{\overline{x}-\mu}{\sigma/\sqrt{n}} = \frac{112-100}{15/\sqrt{9}} = 2.4
\]

From the table, we compute $P(z\geq 2.4) = 0.0082$

*Example 2*. A random sample of $n=9$ scores is obtained from a normal distribution with $\mu=75$ and $\sigma=6$.  What is the probability that the sample mean is greater than $78$?

*Example 3*. A random sample of $n=16$ scores is obtained from a normal distribution with $\mu=50$ and $\sigma=10$.  What is the probability that the sample mean will be between 48 and 52?

*Example 4*. A researcher is interested in whether people can identify emotions in other people when they are extremely tired.  It is known that accuracy ratings of people in the general population are normally distributed with $\mu=82$ and $\sigma=7$.  The researcher arranges to test 50 people who had no sleep the previous night.  The mean accuracy for these 50 people was 80.  What is the probability of having a sample mean no larger than 80?

  - We compute the $z$ score on the distribution of means:

\[
z = \frac{\overline{x}-\mu}{\sigma_{\overline{x}}} = \frac{\overline{x}-\mu}{\sigma/\sqrt{n}} = \frac{80-82}{7/\sqrt{50}} = -2.02
\]

Thus, we compute $P(z\leq -2.02)=0.022$


*Example 5*. How high would a group of 25 have to score (on average) to be in the top 10% of IQ scores for groups of this size?

  - Recall that we can solve the $z$-score formula for $\overline{x}$ to get:

\[
\overline{x} = \mu + z \cdot \sigma_{\overline{x}} = \mu + z\cdot \frac{\sigma}{\sqrt{n}}
\]

Looking at the table, we see that $z=1.28$ is required to be in top 10%.  So

\[
\overline{x} = \mu + z \cdot \sigma_{\overline{x}} = \mu + z\cdot \frac{\sigma}{\sqrt{n}} = 100 + 1.28 \frac{15}{\sqrt{25}} = 103.84
\]

 
