#+TITLE: Week 1 lecture notes - PSYC 3330
#+AUTHOR:
#+DATE: August 28-Sept 1, 2017 
#+OPTIONS: toc:nil num:nil

* Why do we need to learn statistics?

- Goals:
  1.  to *describe* data (descriptive statistics)
  2.  to *make inferences* about a /population/, given data from a /sample/ (inferential statistics)

After studying statistics, we learn how to say things like:
  - "We are /95% confident/ that between 65 and 75 percent of voters will turn out for the upcoming election"
  - "The repeated testing group scored /significantly better/ than the repeated study group on a subsequent memory test."

What do these things mean, exactly?  We'll find out!

* What kinds of data do we deal with?

Data are classified by their /scale of measurement/:

*Categorical* data (also called /discrete/) -- measurements consists of separate categories, with no values existing /between/ any two categories
  1. nominal scale -- measurements correspond to categories with different /names/
    - no logical relation /between/ categories
    - examples -- gender, meal preference, religious preference

  2. ordinal scale -- measurements correspond to /ordered/ categories
    - "nominal + ordering"
    - examples -- position in a race, student classification, level of agreement

*Continuous* data -- measurements take on an infinite set of possible values.  Measurements are usually numeric
  3. interval scale -- measurements consist of numbers where equal differences in measurement reflect equal differences in represented quantity.
    - measurements /don't/ represent an amount (or magnitude)
    - example: temperature scale:  the difference between 10 deg F and 40 deg F is the same as the difference between 50 deg F and 80 deg F (namely, the latter in each pair is 30 degrees warmer).
    - note: ratios DON'T make sense (40 deg F is not "twice as warm" as 20 deg F..it is not clear what this would even mean). 

  4. ratio scale -- interval scale + an absolute zero point
    - can represent magnitude
    - ratios make sense
    - example: any measurement of a "quantity" (weight, response time, etc.)

** class exercise

Identify the scale of measurement for each of the following:

1. ethnic group to which a person belongs
2. number of times a mouse takes a wrong turn in a maze
3. position one finishes in a race
4. a person's score on an IQ test


* Displaying data

For now, we'll focus on how to display /frequency/ -- that is, how often certain measurements show up in the data.

Important -- the type of graph used depends on the scale of measurement:

Categorical data:
  - bar graph
  - pie chart

Continuous data:
  - histogram
