#+TITLE: Week 5 lecture notes - PSYC 3330
#+AUTHOR:
#+DATE: Sept 25-29, 2017 
#+OPTIONS: toc:nil num:nil

So far this semester, we have used statistics to *describe* data.  Now, we will begin using statistics as an *inference tool*.  To do this, we need to discuss *probability*.

* Definition

Suppose we have a list of possible /outcomes/, labeled A, B, C, D, and so on.  Then:

\[
p(A) = \text{ "the probability of A" }=\frac{\text{number of outcomes classified as A}}{\text{total number of possible outcomes}}
\]

Example: What is the probability of picking a king of spades from a standard deck of 52 cards?

Answer:

\[
p(\text{king of spades}) = \frac{\text{# of times king of spades appears}}{\text{number of cards in the deck}} = \frac{1}{52}
\]

Example: What is the probability of picking a heart from a deck?

Answer:

\[
p(\text{heart}) = \frac{\text{# hearts in a deck}}{\text{number of cards in the deck}} = \frac{13}{52} =\frac{1}{4} = 0.25
\]

The more common way we will encounter probability is as part of a /probability distribution/.

Example: Suppose we have 40 slips of paper, each labeled with one of the numbers 1,2,3,4,5.  Specifically, assume they are labeled with the following frequencies:

| X |  f |    p |
|---+----+------|
| 5 |  2 | 0.05 |
| 4 | 10 | 0.25 |
| 3 | 16 | 0.40 |
| 2 |  8 | 0.20 |
| 1 |  4 | 0.10 | 

Visually, this distribution looks like the following graph:

file:figures/week5/plot1.png

Now, suppose our task is to randomly select a slip of paper.  We can then ask lots of questions, such as:

  - What is the probability of selecting a 3?
    - Answer: $p(3) = 0.40$
  - What is the probability of selecting a 5?
    - Answer: $p(5) = 0.05$

We can also ask more complex questions:

  - What is the probability of selecting a slip of paper with a value greater than 2?
    - Answer: $p(x>2) = 0.40 + 0.25 + 0.05 = 0.70$

file:figures/week5/plot2.png

  - What is the probability of selecting a slip of paper with a value less than 5?
    - Answer: $p(x<5) = 0.10 + 0.20 + 0.40 + 0.25 = 0.95$

file:figures/week5/plot3.png

  - What is the probability of selecting a value greater than 1 and less than 4?
    - Answer: $p(1 < x < 4) = 0.20 + 0.40 = 0.60$

file:figures/week5/plot4.png  
