#+TITLE: Week 1 lecture notes - PSYC 3330
#+AUTHOR:
#+DATE: August 28-Sept 1, 2017 
#+OPTIONS: toc:nil num:nil

* Why do we need to learn statistics?

Goals:
  1.  to *describe* data (descriptive statistics)
  2.  to *make inferences* about a /population/, given data from a /sample/ (inferential statistics)

After studying statistics, we learn how to say things like:
  - "We are /95% confident/ that between 65 and 75 percent of voters will turn out for the upcoming election"
  - "The repeated testing group scored /significantly better/ than the repeated study group on a subsequent memory test."

What do these things mean, exactly?  We'll find out!

/Note:/ in our next course (PSYC 3435), you'll learn that much of what we know about psychology (human behavior) comes from /experiments/ 
  - how does systematic manipulation of some variable (*independent variable*) affect measurements on some outcome variable (*dependent variable*)?


* What kinds of data do we deal with?

Data are classified by their /scale of measurement/:

*Categorical* data (also called /discrete/) -- measurements consists of separate categories, with no values existing /between/ any two categories
  1. nominal scale -- measurements correspond to categories with different /names/
    - no logical relation /between/ categories
    - examples -- gender, meal preference, religious preference

  2. ordinal scale -- measurements correspond to /ordered/ categories
    - "nominal + ordering"
    - examples -- position in a race, student classification, level of agreement

*Continuous* data -- measurements take on an infinite set of possible values.  Measurements are usually numeric
  3. interval scale -- measurements consist of numbers where equal differences in measurement reflect equal differences in represented quantity.
    - measurements /don't/ represent an amount (or magnitude)
    - example: temperature scale:  the difference between 10 deg F and 40 deg F is the same as the difference between 50 deg F and 80 deg F (namely, the latter in each pair is 30 degrees warmer).
    - note: ratios DON'T make sense (40 deg F is not "twice as warm" as 20 deg F..it is not clear what this would even mean). 

  4. ratio scale -- interval scale + an absolute zero point
    - can represent magnitude
    - ratios make sense
    - example: any measurement of a "quantity" (weight, response time, etc.)

** class exercise

Identify the scale of measurement for each of the following:

1. ethnic group to which a person belongs
2. number of times a mouse takes a wrong turn in a maze
3. position one finishes in a race
4. a person's score on an IQ test

* Displaying data

For now, we'll focus on how to display /frequency/ for numerical data-- that is, how often certain measurements show up in the data.

** Frequency tables

A frequency table presents the *frequency* of each score 

Example: $N=20$ scores on a 10 point quiz

Raw data:
8, 9, 8, 7, 10
9, 6, 4, 9, 8
7, 8, 10, 8, 8
6, 9, 7, 8, 8

Frequency table:

|  X | f |
|----+---|
|  4 | 1 |
|  5 | 0 |
|  6 | 2 |
|  7 | 3 |
|  8 | 7 |
|  9 | 5 |
| 10 | 2 |

Note: the sum of the "f" column = 20, which is the total number of scores!

** Grouped frequency tables

Grouped frequency tables are used whenever we have a large range of scores.  Instead of representing each score separately, we tabulate scores within specified *intervals*

Example: $N=25$ scores on an exam

82, 75, 88, 93, 53
84, 87, 58, 72, 94
69, 84, 61, 91, 64
87, 84, 70, 76, 89
75, 80, 73, 78, 60

However, it is not clear what the intervals should be.  Here are some guidelines:
1. should have about 10 intervals
2. width of each interval should be simple (e.g., whole number)
3. bottom score of each interval should be multiple of the width
4. all intervals should be same width

Now, let's apply these to the data:

- smallest score is 53, largest is 94, so range covers 42 points.  If we used 9 intervals of width 5 (total width 45), this would work
- lowest interval should contain smallest score (53), and starting point of interval should be multiple of width (5).  So, we'll start with 50

Finally, we can construct the table:

|     X | f |
|-------+---|
| 50-54 | 1 |
| 55-59 | 1 |
| 60-64 | 3 |
| 65-69 | 1 |
| 70-74 | 3 |
| 75-79 | 4 |
| 80-84 | 5 |
| 85-89 | 4 |
| 90-94 | 3 |

** Histograms

A histogram is a graphical representation of a grouped frequency table.

- x-axis: score intervals
- y-axis: frequency
  
Example in class: make a histogram of the data from the grouped frequency table above.

Example: the normal distribution
  - bell shaped
  - symmetric around the center

file:figures/week1/normal.jpg

Example: skewed distribution
  - positive skew - scores bunched at *low* values with a tail pointing toward higher values
  - negative skew - scores bunched at *high* values with a tail pointing toward lower values

file:figures/week1/skew.jpg
