#+TITLE: PSYC 2317: Statistical Methods for Psychology
#+AUTHOR: 
#+DATE: Fall 2019
#+OPTIONS: toc:nil
#+OPTIONS: num:nil
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [10pt]
#+LATEX_HEADER: \usepackage[left=1in,right=1in,bottom=1in,top=1in]{geometry}

** Contact info
- Professor: Thomas J. Faulkenberry, Ph.D
- Office: Math 319
- Office hours: MTWRF 1-3pm (/or by appointment/)
- Email: faulkenberry@tarleton.edu
- Website: [[http://tomfaulkenberry.github.io]]
- Phone: 254-968-9816

** Course description

Statistical methods are the primary tool for research in psychology. They are what allow us as researchers to make consistent, data-driven decisions.  As such, this is an extremely important course and one that I take very seriously as your professor. The topics we will cover this semester will include descriptive statistics (how we describe data) and inferential statistics (how we make decisions about data).  Specifically, this includes central tendency, variability, the distinction between populations and samples, hypothesis testing, and a variety of inferential tests that we can apply to data, including t-tests, linear regression, and analysis of variance.

** Course materials
- /Learning Statistics with JASP: A Tutorial for Psychology Students and Other Beginners/, by Navarro, Foxcroft, and Faulkenberry (2019). 
  - This is a free textbook which can be downloaded from [[http://learnstatswithjasp.com][www.learnstatswithjasp.com]]
- JASP statistical software, freely downloadable from [[http://www.jasp-stats.com][www.jasp-stats.com]]
** Student learning outcomes
1. Identify variables under study (including independent and dependent variables)
2. Choose appropriate measures of descriptive statistics
3. Select and perform appropriate inferential statistics
4. Draw appropriate statistical conclusions from results of analyses

** Requirements and grading
- Exam 1 (100 pts)
- Exam 2 (100 pts)
- Exam 3 (100 pts)
- Final exam (100 pts)
- Weekly quizzes (100 pts)
- Homework exercises (100 pts)
- /Total = 600 points/

Grades will be assigned based on the percentage of points you accumulate out of these 600 points.  I will use the standard grading scale of A=90%, B=80%, etc.

*** Exams
There will be four total exams throughout the semester, occurring approximately once every three to four weeks.  They will cover material from lectures, quizzes, and homework exercises. Exams will be completed in class.

Exam dates:

- Exam 1 (Thursday, September 26)
- Exam 2 (Thursday, October 24)
- Exam 3 (Thursday, November 21)
- Final exam (Friday, December 6, 8-10:00 am)
  
*** Weekly quizzes 
I will administer a short in-class quiz at the beginning of class on Tuesday of each week (excluding Tuesdays immediately following exam weeks). The quiz will cover content from the previous week's lecture and homework exercises. Each quiz counts for 10 possible points.  There will be 10 of these quizzes, so you will earn up to 100 points for your overall quiz grade.

*** Homework exercises 
In order to practice the statistical concepts you learn this semester, you will complete a short homework assignment every week.  A set of homework exercises (usually between 5 and 10 problems) will be provided to you each week.  You may work collaboratively on the homework exercises, but any work submitted must reflect your own understanding of the material (in other words, don't just copy someone else's work to submit).  Completed exercises should be handwritten neatly on clean paper.  Each homework assignment will be due at the beginning of class on Tuesday of the week after it is assigned.

** Course Communication

Email is the primary means of official communication for this course.  If you have questions about the course, always feel free to send me an email at faulkenberry@tarleton.edu.  I only ask that you adhere to two guidelines:
  - please include the course number (PSYC 2317) in the subject line.  For example, one good way to do this is:  Subject: [PSYC 2317] Question about Exam 2
  - please use proper email etiquette.  Include a salutation (e.g., Dear Dr. Faulkenberry), complete sentences, and a closing (e.g., "Regards, Your Name").  You might be surprised how many times I get an email from a nondescript email address with no indication from WHOM the email was sent!

Also, I will send periodic class announcements via email.  Thus, it is imperative that you check your /Tarleton email address/ regularly so that you don't miss any of these messages.

** CV Points for Psychology Majors
Beginning Fall 2019, all Tarleton psychology majors are required to accumulate a certain number of "CV points" as a requirement for graduation. CV is an acronym for "curriculum vitae", which is the traditional name of an academic resume.  No graduating psychology major will receive a diploma without completion/verification of the required 15 CV points. Some classes may build in CV point assignments, but ultimately it is the students’ responsibility to monitor their participation and acquire points during their time at Tarleton.  More information on pre-approved CV points, submission, and tracking of these points can be found in the CV Point Canvas site, as well in the video at the following link: https://bit.ly/2L52r21. Please note that submissions are graded, and may not be approved for points if they do not meet the CV standard.  If a student has a question about CV points, they should send an email to psychcvpointga@tarleton.edu.

** University Policy on "F" Grades
Beginning in Fall 2015, Tarleton will begin differentiating between a failed grade in a class because a student never attended (F0 grade), stopped attending at some point in the semester (FX grade), or because the student did not pass the course (F) but attended the entire semester. These grades will be noted on the official transcript. Stopping or never attending class can result in the student having to return aid monies received.  For more information see the Tarleton Financial Aid website.

** Academic Honesty

Tarleton State University expects its students to maintain high standards of personal and scholarly conduct. Students guilty of academic dishonesty are subject to disciplinary action. Cheating, plagiarism (submitting another person’s materials or ideas as one’s own), or doing work for another person who will receive academic credit are all disallowed. This includes the use of unauthorized books, notebooks, or other sources in order to secure of give help during an examination, the unauthorized copying of examinations, assignments, reports, or term papers, or the presentation of unacknowledged material as if it were the student’s own work. Disciplinary action may be taken beyond the academic discipline administered by the faculty member who teaches the course in which the cheating took place.

In particular, any exam taken online must be completed without the aid of any unauthorized resource (including using any search engine, Google, etc.).  Authorized resources are limited only to the official textbook and any lecture notes from the course.  Any other authorized resources will be provided to you before the exam.  The minimum sanction for violation of this policy is a grade of 0 on the affected exam.

Each student’s honesty and integrity are taken for granted. However, if I find evidence of academic misconduct I will pursue the matter to the fullest extent permitted by the university. ACADEMIC MISCONDUCT OR DISHONESTY WILL RESULT IN A GRADE OF F FOR THE COURSE.  Students are strongly advised to avoid even the /appearance/ of academic misconduct. 

** Academic Affairs Core Value Statements
*** Academic Integrity Statement
Tarleton State University's core values are integrity, leadership, tradition, civility, excellence, and service.  Central to these values is integrity, which is maintaining a high standard of personal and scholarly conduct.  Academic integrity represents the choice to uphold ethical responsibility for one’s learning within the academic community, regardless of audience or situation.

*** Academic Civility Statement 
Students are expected to interact with professors and peers in a respectful manner that enhances the learning environment. Professors may require a student who deviates from this expectation to leave the face-to-face (or virtual) classroom learning environment for that particular class session (and potentially subsequent class sessions) for a specific amount of time. In addition, the professor might consider the university disciplinary process (for Academic Affairs/Student Life) for egregious or continued disruptive behavior.

*** Academic Excellence Statement
Tarleton holds high expectations for students to assume responsibility for their own individual learning. Students are also expected to achieve academic excellence by:
- honoring Tarleton’s core values, upholding high standards of habit and behavior.
- maintaining excellence through class attendance and punctuality, preparing for active participation in all learning experiences. 
- putting forth their best individual effort.
- continually improving as independent learners.
- engaging in extracurricular opportunities that encourage personal and academic growth.
- reflecting critically upon feedback and applying these lessons to meet future challenges.

** Students with Disabilities Policy

It is the policy of Tarleton State University to comply with the Americans with Disabilities  Act (www.ada.gov) and other applicable laws.  If you are a student with a disability seeking accommodations for this course, please contact the Center for Access and Academic Testing, at 254.968.9400 or caat@tarleton.edu. The office is located in Math 201. More information can be found at www.tarleton.edu/caat or in the University Catalog.​
 
*Note:  any changes to this syllabus will be communicated to you by the instructor!*
 
\newpage

** Semester Schedule
| Unit | Dates        | Topic                                                      | Chapter |
|------+--------------+------------------------------------------------------------+---------|
|    1 | Aug 26-30    | Introduction to statistical methods / describing data      |     1-4 |
|    2 | Sep 2-6      | Displaying data                                            |       5 |
|    3 | Sep 9-13     | Introduction to probability                                |       6 |
|    4 | Sep 16-20    | Estimation from samples                                    |       7 |
|      | *Sep 23-27*  | *Exam 1*                                                   |         |
|    5 | Sep 30-Oct 4 | Hypothesis testing                                         |       8 |
|    6 | Oct 7-11     | Analyzing categorical data                                 |       9 |
|    7 | Oct 14-18    | Comparing two means                                        |      10 |
|      | *Oct 21-25*  | *Exam 2*                                                   |         |
|    8 | Oct 28-Nov 1 | Correlation and linear regression                          |      11 |
|    9 | Nov 4-8      | Analysis of variance (ANOVA) with one independent variable |      12 |
|   10 | Nov 11-15    | ANOVA with two independent variables                       |      13 |
|      | *Nov 18-22*  | *Exam 3*                                                   |         |
|      | Dec 2-4      | Wrapup and intro to Bayesian statistics                    |      14 |
|      | *Dec 11*     | *Final exam on Friday, Dec 6, 8-10:00 am*                  |         |

** Open Educational Resources
The development of the textbook for this course was supported by an Open Educational Resources grant awarded to Dr. Tom Faulkenberry from the Tarleton State University Center for Instructional Innovation. Open educational resources (OER) are textbooks and learning materials that are available at no cost to students, accessible from mobile devices, and available from class day one. Research has shown that OER can improve student engagement and course outcomes. This course is part of Tarleton’s OER initiative, to encourage faculty adoption of free and low-cost instructional materials.


#+ATTR_LATEX: :width 5cm
file:oerLogo.png
