#+TITLE: PSYC 5301: Research Methods
#+AUTHOR: 
#+DATE: Spring 2019
#+OPTIONS: toc:nil
#+OPTIONS: num:nil
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [10pt]
#+LATEX_HEADER: \usepackage[left=1in,right=1in,bottom=1in,top=1in]{geometry}

** Contact info
- Professor: Thomas J. Faulkenberry, Ph.D
- Office: Math 319
- Office hours: MWF 1-3 pm, TR 9-11 am
- Email: faulkenberry@tarleton.edu
- Website: [[http://tomfaulkenberry.github.io]]
- Phone: 254-968-9816

** Course description

This course is essentially a continuation of the study of statistics that you have already begun in your graduate studies. It is designed to provide you with a solid grounding in the theory and practice of experimental design and subsequent statistical modeling that form the empirical basis of modern psychological science. In addition, we will discuss some of the /philosophical/ underpinning of modern scientific inference and wade into the debate on frequentist versus Bayesian approaches to inference.  We will accomplish this through weekly lectures, textbook reading, homework exercises, and periodic exams. All students enrolled in this course are required to have *previously taken* PSYC 5300 (Behavioral Statistics) or have equivalent statistical background.

** Course materials

- Textbook
  - /Experiment design for the social and behavioural sciences/ by Boniface
- Software
  - R (free download from r-project.org)
  - RStudio (free download from rstudio.org)
  - JASP (free download from [[http://jasp-stats.org][jasp-stats.org]]).  
- Calculator
  - though, strictly speaking, you can use R for all of your calculation needs, you should have a standalone calculator that is capable of performing the most basic scientific computations (exponents, square roots, logarithms, etc.). A graphing calculator is /not/ required, though I will be using one (TI-84) when I demonstrate calculations. Find one you like using!

** Student learning outcomes

1. Understand the classical elements of inference in psychological research, including basic probability theory, hypothesis testing, and error control
2. Know the basic elements of experimental design (e.g., measurement, random assignment, etc.)
3. Understand the mechanics of classical analysis of variance in single-factor and two-factor design
4. Know how to adapt inferential procedures for within-subjects designs and, more generally, designs with covariates
5. Understand the differences between frequentist and Bayesian approaches to hypothesis testing
6. Use appropriate software packages to perform both frequentist and Bayesian hypothesis tests for a variety of experimental designs

** Requirements and grading
- Exam 1 (100 points)
- Exam 2 (100 points)
- Exam 3 (100 points)
- Homework exercises (100 points)
- Class participation (100 points)
- /Total = 500 points/

Grades will be assigned based on the percentage of points you accumulate out of these 500 points.  I will use the standard grading scale of A=90%, B=80%, etc.

*** Exams (60% of grade)
There will be three regular exams throughout the semester, tentatively scheduled for Week 5 (Feb 11), Week 11 (Apr 2), and Week 16 (May 7). Exams will be completed in class on these dates, and you will have the entire class period (6:30-9:15 pm) to complete the exam. All work will be submitted in a bluebook, and no collaboration will be allowed. Generally speaking, no textbooks or lecture notes may be used on exams, but reasonable relaxations of this rule will be provided on a per-exam basis (depending on difficulty of content, etc.).

*** Homework exercises (20% of grade)
Each week at the end of lecture, you will be given a set of exercises that will provide you with an opportunity to practice the concepts you've learned. You may collaborate on these exercises, but I ask that anything turned in represents your own understanding of the collaborative work. Please write neatly, and clearly label each problem. Homework will be turned in at the beginning of the next class (i.e., you'll have exactly one week to complete the problems).

*** Class participation (20% of grade)
This is a very active course, and we will learn a lot every week. It is essential that you participate in /all/ class sessions. Your class participation grade will be reflective of the effort that I've seen you put into the course. Most people will earn all 100 possible points, but I reserve the right to lower this grade if you miss excessive class meetings. 

** Course Communication

Email is the primary means of official communication for this course.  If you have questions about the course, always feel free to send me an email at faulkenberry@tarleton.edu.  I only ask that you adhere to two guidelines:
  - please include the course number (PSYC 5301) in the subject line.  For example, one good way to do this is:  Subject: [PSYC 5301] Question about HW 3
  - please use proper email etiquette.  Include a salutation (e.g., Dear Dr. Faulkenberry), complete sentences, and a closing (e.g., "Regards, Your Name").  You might be surprised how many times I get an email from a nondescript email address with no indication from WHOM the email was sent!

Also, I will send periodic class announcements via email.  Thus, it is imperative that you check your /Tarleton email address/ regularly so that you don't miss any of these messages.

** University Policy on "F" Grades

Beginning in Fall 2015, Tarleton began differentiating between a failed grade in a class because a student never attended (F0 grade), stopped attending at some point in the semester (FX grade), or because the student did not pass the course (F) but attended the entire semester. These grades will be noted on the official transcript. Stopping or never attending class can result in the student having to return aid monies received.  For more information see the Tarleton Financial Aid website.

** Academic Honesty

Cheating, plagiarism (submitting another person’s materials or ideas as one’s own without proper attribution), or doing work for another person who will receive academic credit are all disallowed. This includes the use of unauthorized books, notebooks, or other sources in order to secure of give help during an examination, the unauthorized copying of examinations, assignments, reports, or term papers, or the presentation of unacknowledged material as if it were the student’s own work. Disciplinary action may be taken beyond the academic discipline administered by the faculty member who teaches the course in which the cheating took place.

The minimum sanction for /any/ act of academic dishonesty is a grade of 0 on the affected assignment; a grade of F for the course may be assigned in severe cases.

** Academic Affairs Core Value Statements
*** Academic Integrity Statement
Tarleton State University's core values are integrity, leadership, tradition, civility, excellence, and service.  Central to these values is integrity, which is maintaining a high standard of personal and scholarly conduct.  Academic integrity represents the choice to uphold ethical responsibility for one’s learning within the academic community, regardless of audience or situation.

*** Academic Civility Statement 
Students are expected to interact with professors and peers in a respectful manner that enhances the learning environment. Professors may require a student who deviates from this expectation to leave the face-to-face (or virtual) classroom learning environment for that particular class session (and potentially subsequent class sessions) for a specific amount of time. In addition, the professor might consider the university disciplinary process (for Academic Affairs/Student Life) for egregious or continued disruptive behavior.

*** Academic Excellence Statement
Tarleton holds high expectations for students to assume responsibility for their own individual learning. Students are also expected to achieve academic excellence by:
- honoring Tarleton’s core values, upholding high standards of habit and behavior.
- maintaining excellence through class attendance and punctuality, preparing for active participation in all learning experiences. 
- putting forth their best individual effort.
- continually improving as independent learners.
- engaging in extracurricular opportunities that encourage personal and academic growth.
- reflecting critically upon feedback and applying these lessons to meet future challenges.

** Students with Disabilities Policy

It is the policy of Tarleton State University to comply with the Americans with Disabilities Act and other applicable laws. If you are a student with a disability seeking accommodations for this course, please contact the Center for Access and Academic Testing, at 254.968.9400 or caat@tarleton.edu. The office is located in Math 201. More information can be found at www.tarleton.edu/caat or in the University Catalog.

**Note:  any changes to this syllabus will be communicated to you by the instructor!**
 
** Schedule of lectures

 | Week | Date   | Topic                                                | Reading                  |
 |------+--------+------------------------------------------------------+--------------------------|
 |    1 | Jan 15 | Review of basic statistical inference                | Boniface, Ch 1-3         |
 |    2 | Jan 22 | Single-factor independent group design               | Boniface, Ch 4           |
 |    3 | Jan 29 | Single-factor repeated measures design               | Boniface, Ch 5           |
 |    4 | Feb 4  | Two-factor independent groups design                 | Boniface, Ch 6           |
 |    5 | Feb 11 | *Exam 1*                                             |                          |
 |    6 | Feb 18 | Single-factor independent groups design w/ covariate | Boniface, Ch 7           |
 |    7 | Feb 25 | Contrasts and comparisons among means                | Boniface, Ch 8           |
 |    8 | Mar 5  | Unbalanced and confounded designs                    | Boniface, Ch 10          |
 |    9 | Mar 19 | Multiple regression                                  | Boniface, Ch 11          |
 |   10 | Mar 26 | Mixed designs                                        | Boniface, Ch 12          |
 |   11 | Apr 2  | *Exam 2*                                             |                          |
 |   12 | Apr 9  | Introduction to Bayesian inference                   | Wagenmakers (2007, 2010) |
 |   13 | Apr 16 | Bayesian \(t\)-tests                                 | Rouder et al. (2007)     |
 |   14 | Apr 23 | Bayesian analysis of single- and two-factor designs  | Rouder et al. (2016)     |
 |   15 | Apr 30 | Bayesian analysis with inequality contraints         | Klugkist et al. (2005)   |
 |   16 | May 7  | *Exam 3*                                             |                          |
